# depth_python.py — extended teaching content for the python track.
# Auto-attached by depth.py. One entry per lesson id.

DEPTH = {

    "py-1": {
        "title_check": "Building from a blank file",
        "sections": [
            {"h": "STATEMENTS EXECUTE IN ORDER - EVEN def AND class", "body": r"""In Python, def and class are not declarations a compiler files away before your program starts running - they are executable statements, run top to bottom exactly like an assignment or a call to print. When the interpreter reaches def greet(name): ..., it builds a function object at that moment and binds the name greet to it in the current namespace; before that line runs, the name greet does not exist at all. This is the biggest structural difference from Java, where a method is visible throughout its class the instant the class file loads, no matter where in the source it happens to be written - you can call a method defined near the bottom of a Java class from code near the top with zero problem. Do the equivalent in a Python script - call a function on line 3 that is not def'd until line 40 - and you get a NameError, not because Python could not locate it by name, but because the function object genuinely does not exist yet when line 3 executes. This is exactly why script SHAPE matters: helper functions must be executed (their def statements run) before the code that calls them, and main() is conventionally placed last and called only once, after every def above it has already populated the module's namespace. A class body behaves identically - it is a small block of statements executed once, top to bottom, to build the namespace that becomes the class's attributes."""},

            {"h": "MECHANISM: NAMESPACES, LEGB, AND WHY FUNCTIONS FORGET NOTHING BUT ALSO SEE NOTHING", "body": r"""Every time a function is called, Python creates a fresh local namespace living inside a frame object, and discards it when the call returns. Name lookup inside a function follows the LEGB rule: Local names first, then any Enclosing function's locals, then the Global (module-level) namespace, then Built-in names like len or print. The trap beginners hit constantly is this: if a name is assigned ANYWHERE inside a function body, Python decides at compile time that the name is local for the ENTIRE function, even on lines before the assignment - so count = count + 1 inside a function that never received count as a parameter, and never declared global count, raises UnboundLocalError on the read, not a fallback to some global count sitting right there in the module. This is not a bug; it is the compiler resolving scope statically from the function's text before a single line executes, and it is precisely why decomposition into small functions matters: each function should receive what it needs as parameters and return what it computes, rather than reaching sideways into module-level variables and hoping the LEGB chain finds something sensible. A function that only touches its own parameters and locals is far easier to reason about, move, and test than one silently coupled to global state through the E and G scopes."""},

            {"h": "WORKED EXAMPLE: DECOMPOSING stats.py INTO HONEST FUNCTIONS", "body": r"""Take the doThis task for this lesson - stats.py, which reads numbers until a blank line and prints count, sum, average, min, and max. A beginner's instinct is one long main() mixing input, computation, and printing; the fix decomposes along exactly those three seams:

    def read_numbers():
        nums = []
        while True:
            line = input()
            if line == '':
                break
            nums.append(float(line))
        return nums

    def summarize(nums):
        return {'count': len(nums), 'sum': sum(nums),
                'avg': sum(nums) / len(nums) if nums else 0,
                'min': min(nums) if nums else None,
                'max': max(nums) if nums else None}

    def main():
        stats = summarize(read_numbers())
        print(stats)

read_numbers only ever produces data, summarize only ever transforms data into other data, and main is the sole place touching both input() and print(). Each of the first two functions can now be called from a unit test with a plain list literal, no terminal attached at all - decomposition is not a style preference, it is what makes a function testable in isolation."""},

            {"h": "FAILURE MODES: THE MUTABLE DEFAULT ARGUMENT AND THE LATE-BINDING CLOSURE", "body": r"""Two Python-specific bugs ambush people who skip a mental model of function definition. First, default argument values are evaluated exactly ONCE, at def time, not fresh on every call - def add_item(item, bucket=[]): bucket.append(item); return bucket looks harmless, but that empty list literal is created a single time when the def statement runs, and every call that omits bucket reuses the SAME list object, silently accumulating items across unrelated calls. The fix is a sentinel default: def add_item(item, bucket=None): if bucket is None: bucket = []. Second, closures capture VARIABLES, not the values they held at definition time - build a list of functions in a loop, fns = [lambda: i for i in range(3)], and calling fns[0](), fns[1](), fns[2]() prints 2, 2, 2, because all three lambdas share the same enclosing i, and by the time any is called, the loop has finished and i is 2. This is late binding, and it surprises people who expect each lambda to have captured the value of i at creation time - it captured the variable itself, a live reference into the enclosing scope, not a snapshot. Both bugs are silent: no error, no warning, just quietly wrong behavior discovered only when you inspect results."""},

            {"h": "HOW A PROFESSIONAL GROWS A SCRIPT WITHOUT IT BECOMING SPAGHETTI", "body": r"""A professional does not let a script grow by accretion until it is unreadable - there are concrete signals for when and how to restructure. Once a function's body no longer fits on one screen, or a script accumulates more than four or five top-level functions, group related ones and consider splitting into modules that main.py imports from. Functions should return values rather than print them directly whenever there is any chance the value will be reused, tested, or fed into another function - a function that prints instead of returning is a dead end that can only ever be a leaf in your call graph, never a building block. Command-line arguments deserve argparse rather than manually parsing sys.argv once you have more than one flag, because argparse gives you --help output, type conversion, and error messages for free. Type hints (def summarize(nums: list[float]) -> dict) cost nothing at runtime - Python does not enforce them - but they document intent for you and for tools like mypy, and make a decomposed function's contract legible at a glance six months later when you have forgotten why you wrote it. A short docstring under each def, one sentence on what it takes and returns, is the cheapest documentation you will ever write and the one you will thank yourself for first."""},

            {"h": "WHERE THIS IS GOING: FUNCTIONS ARE THE UNIT EVERYTHING ELSE IS BUILT FROM", "body": r"""Every later lesson in this track assumes you can already decompose a problem into small, honest functions, because that is the raw material everything else reshapes. Object-oriented programming, covered next, is really just functions bundled together with the data they operate on, given a shared namespace called self - a method is a function that receives an implicit first argument. Generators are functions with different execution rules (a yield instead of a return suspends rather than ends), but you still design them by decomposing a problem into one meaningful step at a time. Testing your own code is only pleasant when a function does one clear thing and returns a value you can assert against - a function that only prints cannot be tested without capturing stdout, exactly the kind of avoidable friction good decomposition prevents from the start. And in security-relevant code specifically, small single-purpose functions are what make an input-validation or sanitization routine auditable in isolation - a reviewer, or you months later, can look at one ten-line function and be confident what it does, which is impossible when the same logic is buried inline inside a larger block that also handles I/O, formatting, and error recovery all at once."""},
        ],
    },

    "py-2": {
        "title_check": "OOP the way GAMA asks it",
        "sections": [
            {"h": "MENTAL MODEL: A METHOD CALL IS A DISGUISED FUNCTION CALL", "body": r"""When you write car.describe(), Python is not doing anything magical - it finds describe on the class (or up the class's inheritance chain) and calls it as Car.describe(car), passing car in as the first argument automatically. This works because functions are descriptors: a plain function object defines a __get__ method, and when you look up an attribute on an instance and Python finds a function on the CLASS instead, it invokes that descriptor protocol to produce a "bound method" - a small object remembering both the function and the instance, injecting the instance as the first argument when called. This is why self is not a keyword, just a convention - it is genuinely the first parameter of an ordinary function, and car.describe() with zero explicit arguments is exactly equivalent to Car.describe(car) with one. Java hides this machinery entirely behind syntax; Python exposes it, which is why you CAN call Car.describe(car) directly, why @staticmethod exists to opt a method OUT of this injection, and why @classmethod injects the class itself (cls) instead of an instance - three variations on the same descriptor mechanism, not three unrelated features."""},

            {"h": "MECHANISM: __new__, __init__, AND HOW self GETS BOUND", "body": r"""Object construction is a two-step handshake between two dunder methods beginners usually only meet one of. __new__(cls, ...) runs first - its job is to actually ALLOCATE the new, empty instance and return it; only then does Python call __init__(self, ...) on that freshly allocated object to populate its attributes. For ordinary classes you almost never override __new__, because object.__new__ allocates correctly and __init__ is where setup logic belongs - but immutable types (str, int, tuple, frozen dataclasses) must override __new__ instead, because by the time __init__ would run the object is already supposed to be fully formed and unchangeable. Once __init__ finishes, attribute assignment self.name = name is just a dictionary write into the instance's own __dict__ (a real, inspectable dict on almost every object) unless the class defines __slots__, in which case there is no per-instance __dict__ at all and attributes live in fixed, pre-allocated slots instead - trading the flexibility of adding arbitrary attributes later for lower memory use and faster attribute access, since no hash lookup is involved."""},

            {"h": "WORKED EXAMPLE: A DUNDER-RICH Vector CLASS", "body": r"""Consider a small Vector class that needs to behave like a built-in number where it makes sense:

    class Vector:
        __slots__ = ('x', 'y')
        def __init__(self, x, y):
            self.x, self.y = x, y
        def __add__(self, other):
            return Vector(self.x + other.x, self.y + other.y)
        def __eq__(self, other):
            return isinstance(other, Vector) and (self.x, self.y) == (other.x, other.y)
        def __repr__(self):
            return f'Vector({self.x}, {self.y})'

Vector(1, 2) + Vector(3, 4) works because Python translates a + b into a.__add__(b) automatically; if that returned NotImplemented, Python would then try b.__radd__(a) before raising TypeError. print(Vector(1,2)) calls __repr__ (there is no __str__ here, and __repr__ is the fallback __str__ uses when absent). Defining __eq__ but NOT __hash__ makes instances unhashable by default in Python 3 - object supplied a working identity-based __hash__ automatically, but overriding __eq__ removes it, because two "equal" objects MUST have equal hashes, and Python cannot guess how to reconcile your custom equality with the inherited identity hash, so it deletes the inherited one."""},

            {"h": "FAILURE MODES: SHARED MUTABLE CLASS ATTRIBUTES AND THE __eq__/__hash__ TRAP", "body": r"""A class-level attribute written directly in the class body, class Player: inventory = [], is NOT reset per instance - it is one single list object stored on the class, and every instance that has not shadowed it with its own instance attribute of the same name shares that exact object. p1.inventory.append('sword') silently also affects p2.inventory, because reading an attribute falls through to the class when the instance's own __dict__ has no entry, so both instances mutate the SAME shared list - the class-level cousin of the mutable-default-argument bug from the previous lesson, same root cause (one object, created once, referenced from many places), different syntax. The __eq__/__hash__ trap compounds this: once you define __eq__ without __hash__, putting instances into a set or using them as dict keys raises TypeError: unhashable type, which looks unrelated to the equality change you actually made, until you remember Python's rule that equal objects must hash equally and refuses to leave a stale, now-incorrect inherited hash lying around. A third common trap: comparing with is instead of == on freshly built objects equal in value but two DISTINCT objects - Vector(1,2) is Vector(1,2) is False even with __eq__ defined, because is checks identity, never routed through __eq__ at all."""},

            {"h": "HOW A PROFESSIONAL CHOOSES __slots__, DATACLASSES, AND is VS ==", "body": r"""Professionals treat __slots__, dataclasses, and is/== as three separate, deliberate decisions rather than defaults. __slots__ is worth adding to classes instantiated by the thousands (parser nodes, particles, small value-like records) because it removes each instance's __dict__, cutting memory per instance and catching accidental-typo attribute creation as an AttributeError instead of silently creating a new attribute - the tradeoff is losing the ability to add arbitrary attributes later, and losing easy multiple inheritance from more than one slotted base. @dataclass generates __init__, __repr__, and __eq__ from type-annotated fields alone, exactly what the Vector class above spells out by hand - reach for it whenever a class is mostly a bag of fields with little custom behavior, and reserve hand-written classes for real invariants enforced in __init__ or non-trivial methods. On is versus ==: use is exclusively for identity checks that are supposed to be about identity - is None, checking two variables are literally the same object - and use == for everything about value equality, because is on two separately-constructed equal-looking objects can silently return False even when a human would call them "the same"."""},

            {"h": "WHERE THIS IS GOING: OOP AS THE VOCABULARY FOR EVERYTHING YOU'LL DESIGN", "body": r"""Everything downstream in the track leans on this lesson's vocabulary. Testing your own code often means asserting that two objects compare equal (assert Vector(1,1) + Vector(2,2) == Vector(3,3)), which only works because you defined __eq__ - a test using is instead would fail even on completely correct code, so knowing which operator means what is a prerequisite for writing tests that verify what you intend. Exceptions ARE objects, instances of classes inheriting from BaseException, constructed and raised exactly like any object you build here - a custom exception class is just a subclass with maybe an extra __init__ to hold context, no new mechanism to learn. And when this track eventually touches security-relevant code, object design choices have real consequences: a class holding a password or key as a plain attribute is trivially inspectable via vars(obj) or __dict__, while __slots__ at least prevents accidental new attributes from leaking data by typo, and a deliberately overridden __repr__ that never prints a secret field is a small, real habit keeping sensitive data out of logs and stack traces the moment someone calls print(obj) or repr(obj) while debugging."""},
        ],
    },

    "py-3": {
        "title_check": "The stdlib you keep forgetting",
        "sections": [
            {"h": "MENTAL MODEL: THE STDLIB AS THIN WRAPPERS OVER OS PRIMITIVES", "body": r"""socket, threading, json, sqlite3, and hashlib all share a design philosophy: each is a thin, fairly direct Python wrapper around an operating-system or well-established C-library primitive, not a from-scratch Python reinvention. socket.socket(...) maps closely onto the BSD sockets API your OS course will eventually name explicitly (socket/bind/listen/accept/connect/send/recv exist in C with nearly identical names and argument order); threading.Thread wraps native OS threads; sqlite3 embeds an actual copy of the SQLite C library inside the standard library, not a pure-Python reimplementation; hashlib exposes OpenSSL's (or a bundled equivalent's) hash implementations. Knowing this changes how you read stdlib docs: instead of memorizing Python-specific behavior, you are learning the underlying OS or protocol concept through a thin, forgiving skin, which is also why these modules transfer almost unchanged in spirit to C, C#, or any other language you use for the same job later - the socket lifecycle, the SQL injection risk, and the one-way nature of a hash function are not Python facts, they are universal facts Python happens to expose directly."""},

            {"h": "MECHANISM: THE GIL, THREADING, AND WHY IT HELPS SOCKETS BUT NOT MATH", "body": r"""CPython's Global Interpreter Lock (GIL) is a single mutex allowing only ONE thread to execute Python bytecode at any instant, even on a multi-core machine - it exists because CPython's memory management (reference counting on every object) is not thread-safe without some serialization, and the GIL is the blunt, simple solution CPython has used since its creation. This means threading.Thread does NOT give true parallel execution of Python code - two CPU-bound threads doing pure arithmetic run no faster than one, because they take turns holding the GIL. What threading DOES genuinely help is I/O-bound work: when a thread calls a blocking operation like socket.recv() or file I/O, CPython releases the GIL for the duration of that OS-level wait, letting another thread run Python code during exactly the time the first thread does nothing but wait on the kernel. This is precisely why a threaded echo server scales reasonably (each connection spends most of its time blocked on recv, not computing), while CPU-heavy work (hashing millions of passwords, image processing) needs multiprocessing instead, sidestepping the GIL entirely by running separate OS processes, each with its own interpreter and its own GIL."""},

            {"h": "WORKED EXAMPLE: A THREADED ECHO SERVER", "body": r"""    import socket, threading

    def handle(conn):
        with conn:
            while True:
                data = conn.recv(1024)
                if not data:
                    break
                conn.sendall(data)   # echo it back

    def serve(port=5050):
        srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        srv.bind(('0.0.0.0', port))
        srv.listen()
        while True:
            conn, addr = srv.accept()
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

Each accept() blocks until a client connects, at which point a brand new thread is spun up just for that connection, and the main thread loops back to accept() immediately, ready for the next client - the classic "thread per connection" server shape. The with conn: block guarantees conn.close() runs even if handle raises partway through, because socket objects implement the context manager protocol themselves. daemon=True on the thread means these handler threads will not prevent the whole process from exiting if the main thread ends - without it, one hung client connection could keep the entire server process alive indefinitely."""},

            {"h": "FAILURE MODES: RACE CONDITIONS, SQL INJECTION, AND FAST-BUT-WRONG HASHING", "body": r"""Three stdlib-adjacent bugs recur constantly in student networking and database code. First, a race condition: two threads incrementing a shared counter with count += 1 looks atomic but is not - it is a read, an add, and a write as three separate bytecode steps, and the GIL can switch threads BETWEEN any of them, so two threads can both read the same old value before either writes back, silently losing an increment; the fix is a threading.Lock wrapped around the read-modify-write so the three steps complete as one uninterrupted unit. Second, SQL injection from building queries with an f-string: con.execute(f"SELECT * FROM users WHERE name='{name}'") lets an attacker supply a name like x' OR '1'='1 and rewrite your query's logic entirely, because the database cannot tell your intended SQL apart from data that happens to look like SQL - a parameterized query, execute(sql, (name,)), sends the value through a completely separate channel the engine never parses as code. Third, hashlib.sha256(password).hexdigest() alone for password storage is fast BY DESIGN (SHA-256 exists partly to verify file integrity quickly), exactly the wrong property for a password hash - an attacker holding a stolen hash database can try billions of guesses per second on ordinary hardware."""},

            {"h": "HOW A PROFESSIONAL USES sqlite3 AND hashlib SAFELY", "body": r"""A professional's sqlite3 code wraps every mutating block so either all changes commit or none do: use the connection as a context manager (with con: cursor.execute(...)) so an exception mid-transaction rolls back automatically rather than leaving the database half-updated, and always parameterize with ? placeholders, never string formatting, regardless of whether a value "looks safe" - the rule has no exceptions, because the one time you skip it for a value you assumed was safe is the one time it will not be. For passwords, professionals reach for a purpose-built slow hash - bcrypt, scrypt, or PBKDF2 - never a bare cryptographic hash function like sha256 or md5, because these algorithms deliberately cost meaningful CPU time and memory per guess (often building in a per-password random salt automatically), turning an attacker's billion-guesses-per-second into a few dozen, which is the entire point. Python's hashlib exposes hashlib.pbkdf2_hmac directly for exactly this purpose, with an explicit iteration count you should set high enough to be slow (hundreds of thousands of rounds, tuned against your own hardware) - the count is not a magic number, it is a dial you turn until hashing one password takes a deliberately noticeable fraction of a second."""},

            {"h": "WHERE THIS IS GOING: THE STDLIB MODULES THAT BUILD YOUR CS PROJECT'S PROTOCOL", "body": r"""These five modules are not independent trivia - together they are the exact toolkit your CS project's client-server protocol needs. socket gives you the raw transport; threading lets your server handle more than one client without one slow connection blocking every other; json gives both sides of that connection a shared, language-neutral way to serialize a request or response into bytes that cross the wire and back into a dict on the other end; sqlite3 gives the server somewhere durable to persist state between runs; hashlib, used properly, is how you store credentials without ever keeping a plaintext password on disk. Every one of these also reappears, conceptually unchanged, later in your studies: sockets and threading are the exact ideas the OS and networking material formalizes with kernel-level detail, SQL injection is the canonical example the security track uses to teach "never trust input that crosses a trust boundary," and password hashing is a recurring theme anywhere authentication is discussed. Learning these five stdlib modules well now is really learning five small, self-contained previews of material you will see again in much greater depth."""},
        ],
    },

    "py-4": {
        "title_check": "Generators & context managers",
        "sections": [
            {"h": "MENTAL MODEL: A GENERATOR IS A FUNCTION WHOSE FRAME SURVIVES ON THE HEAP", "body": r"""An ordinary function call creates a stack frame, runs to completion or an exception, and that frame is gone - its local variables simply cease to exist the instant the function returns. A generator function (any def containing yield anywhere in its body) behaves completely differently: calling it does not run any of its code at all, it immediately returns a generator object holding a SUSPENDED frame - locals, the instruction pointer, everything - parked on the heap instead of the call stack. Each call to next() on that generator resumes the frame exactly where it left off, runs until the next yield (or a return, which raises StopIteration), and suspends again, preserving every local variable's value across the suspension. This is why a generator can maintain state - a running total, a position in a file, an index into a sequence - without a single instance attribute or class: the state lives in the suspended frame itself, a genuinely different execution model from a normal function, not just a convenient way to write a loop that produces values lazily. It is the closest thing Python has to a lightweight coroutine, implemented with real, first-class frame objects you can inspect."""},

            {"h": "MECHANISM: __iter__, __next__, send, throw, close - THE FULL PROTOCOL", "body": r"""The full iterator protocol underlying every for loop has two dunder methods: __iter__(self) returns an iterator (often self), and __next__(self) produces the next value or raises StopIteration when exhausted - a for x in obj: loop is sugar for calling iter(obj) once, then repeatedly calling next() on the result until StopIteration, caught internally so you never see it. A generator object satisfies this protocol automatically: gen.__next__() (or next(gen)) resumes the frame to the next yield. Three additional methods make a generator a genuine two-way channel, not just a one-way producer: gen.send(value) resumes the frame AND makes that value the result of the paused yield expression (x = yield now receives value into x); gen.throw(exc) resumes the frame by raising exc at the paused point, letting the generator's own try/except catch and react to an externally injected error; gen.close() raises GeneratorExit at the paused point, which a generator can catch (typically in a finally block) to run cleanup before being discarded, and if it does not exit promptly after that, Python raises RuntimeError. This send/throw/close trio is the low-level machinery async/await was later built on top of."""},

            {"h": "WORKED EXAMPLE: A CUSTOM CONTEXT MANAGER VIA contextlib.contextmanager", "body": r"""A generator function decorated with @contextlib.contextmanager becomes a full context manager without writing a class - the code before the yield is __enter__, the yielded value is what "as x" binds to, and the code after the yield is __exit__:

    from contextlib import contextmanager
    import time

    @contextmanager
    def timer(label):
        start = time.perf_counter()
        try:
            yield
        finally:
            elapsed = time.perf_counter() - start
            print(f'{label}: {elapsed:.3f}s')

    with timer('parse step'):
        do_parsing()

When the with block starts, the generator runs up to yield (recording start); when the block ends (normally OR via an exception), Python resumes the generator past the yield, running the finally clause exactly once regardless of how the block exited. This decorator is a direct illustration of the previous section's protocol: contextlib is not new magic, it is send/throw/close wired up automatically so you never write __enter__ and __exit__ by hand for the common case of "setup, then guaranteed teardown"."""},

            {"h": "FAILURE MODES: EXHAUSTED ITERATORS, LEAKY GENERATORS, AND __exit__ SWALLOWING ERRORS", "body": r"""Generators are single-pass and stateful, which creates bugs that look like logic errors but are really exhaustion errors: once a generator has been fully consumed, calling next() again does not restart it, it raises StopIteration immediately forever - unlike a list, which you can iterate as many times as you like, a generator represents ONE journey through the data, and for x in gen: followed by a second for x in gen: on the same object silently does nothing the second time, a common source of "why is my second loop empty" bugs. A generator abandoned without being closed - a partially-consumed generator that goes out of scope - can leak: any resource opened before its first yield (a file, a lock) is only guaranteed to be released if the generator's finally clause runs, and if it is garbage-collected without close() ever being called, cleanup depends on CPython's reference counting eventually reaching it, not guaranteed timing in general. Separately, a hand-written __exit__(self, exc_type, exc_val, exc_tb) that returns True SUPPRESSES whatever exception was in flight - a common mistake is returning a truthy cleanup-status value when you only meant to log the error, silently swallowing real exceptions the with block's caller never learns about."""},

            {"h": "HOW A PROFESSIONAL COMPOSES GENERATORS AND CONTEXT MANAGERS TOGETHER", "body": r"""Professionals compose generators and context managers constantly, usually to stream data through a temporary resource without holding the whole thing in memory: a function that opens a file (via with, guaranteeing the handle closes), then yields one processed line at a time, lets a caller do for record in stream_records(path): ... and get both the memory-efficiency of lazy iteration AND the safety of guaranteed cleanup, with neither concern visible in the caller's code. Chaining generators - one reading lines, feeding a second that parses them, feeding a third that filters - builds a lazy pipeline where nothing downstream runs until something pulls a value from the very end, exactly the model itertools and much of pandas' internals rely on for processing data larger than memory. For context managers specifically, professionals reach for contextlib.contextmanager for simple setup/teardown pairs and only write a full class with __enter__/__exit__ when it needs to hold meaningfully complex state across multiple methods, or needs to be reentrant/reusable across multiple with blocks, which a single generator-based context manager is NOT safely - it is exhausted after one use, exactly like any other generator."""},

            {"h": "WHERE THIS IS GOING: THIS PROTOCOL IS ALSO async/await's FOUNDATION", "body": r"""The send/throw/close protocol from this lesson is not a dead end - it is literally the mechanism CPython later repurposed to build async/await. An async function compiles into something structurally close to a generator: awaiting a coroutine is implemented in terms of the same suspend-and-resume-a-frame machinery, and early Python codebases, before async/await existed as dedicated syntax, implemented asynchronous code using exactly yield-based generators decorated with @asyncio.coroutine - a fossil of exactly this connection, later replaced by cleaner keywords but not by a different underlying execution model. Context managers reappear constantly once you touch a real resource: a socket connection, a database transaction, a threading.Lock, a temporary file - the pattern "acquire, guarantee release even on error" is the single most common resource-safety idiom in the language, and it is exactly as important in security-sensitive code, where failing to release a lock or leaving a file handle open under an exception path is not just untidy, it is a resource-exhaustion bug an attacker can potentially trigger deliberately, causing the exceptional path again and again until the process runs out of file descriptors or connections."""},
        ],
    },

    "py-5": {
        "title_check": "Errors, exceptions & debugging",
        "sections": [
            {"h": "MENTAL MODEL: RAISING UNWINDS THE STACK LOOKING FOR A HANDLER", "body": r"""When a raise statement executes, Python does not know yet where, or whether, a handler exists - it starts unwinding the call stack one frame at a time, checking each enclosing try block in the CURRENT frame first, then popping to the calling frame and checking there, and so on, until it finds a matching except clause or reaches the top of the program with no handler found (which is what actually prints the traceback and terminates the process). Every frame the exception passes through on its way up gets its finally block run, if it has one, before the unwinding continues - this is guaranteed, not incidental, which is exactly why finally is the right place for cleanup that absolutely must happen regardless of which code path triggered it. This "search upward through frames" model is why a try/except placed far from where an error actually occurs still works (an exception raised three function calls deep is perfectly happy to be caught by a try at the top), but it also means a broad except clause placed too high up the call stack can catch and mask an error that really originated from a completely different, unrelated piece of code several frames below - matching on TYPE, not on where in the program you expected the failure to come from."""},

            {"h": "MECHANISM: EXCEPTION CHAINING - __context__, __cause__, AND raise X from Y", "body": r"""Every exception object automatically records how it came to exist relative to any exception already being handled, via two hidden attributes you rarely set directly. __context__ is set automatically whenever you raise a NEW exception while already inside an except block handling a different one - Python remembers "this happened while handling that other one" even if you never intended any connection, which is why an unrelated bug inside an except clause still shows both tracebacks chained together with "During handling of the above exception, another exception occurred." __cause__ is set deliberately, by writing raise NewError('...') from original_error, telling Python this chaining IS intentional - the new exception presents a higher-level explanation of exactly why the lower-level one happened, and Python's default traceback printer changes its wording to "The above exception was the direct cause of the following exception" instead. raise ... from None explicitly suppresses chaining entirely, telling Python to discard whatever context exists, useful when the original low-level exception would only be confusing noise to whoever reads the final traceback."""},

            {"h": "WORKED EXAMPLE: WRAPPING A LOW-LEVEL ERROR WITHOUT LOSING THE ORIGINAL", "body": r"""Suppose a config-loading function wants to translate a low-level parsing failure into a message meaningful to its caller, without discarding the original evidence:

    import json

    class ConfigError(Exception):
        pass

    def load_config(path):
        try:
            with open(path) as f:
                return json.load(f)
        except FileNotFoundError as e:
            raise ConfigError(f'no config file at {path}') from e
        except json.JSONDecodeError as e:
            raise ConfigError(f'{path} is not valid JSON') from e

Both except clauses catch a specific, low-level exception and re-raise a higher-level ConfigError with a message meaningful to load_config's caller, who should not need to know JSON parsing is involved internally, while from e attaches the original exception as __cause__ so nothing is lost - anyone debugging later, or any logging call printing the full traceback, still sees the FileNotFoundError or JSONDecodeError underneath, chained beneath the friendlier ConfigError. This is the right middle ground between letting a confusing low-level exception leak through unexplained, and swallowing it entirely with a bare raise that discards the real cause forever."""},

            {"h": "FAILURE MODES: bare except:, finally SWALLOWING RETURNS, AND OVER-BROAD CATCHES", "body": r"""A bare except: (no exception type) catches EVERYTHING inheriting from BaseException, not just ordinary errors - that includes KeyboardInterrupt (raised on Ctrl+C) and SystemExit (raised by sys.exit()), both deliberately inheriting directly from BaseException rather than Exception precisely so a bare except: or even except Exception: leaves them alone; a bare except: does NOT leave them alone, so a program with one buried inside a loop can become literally uninterruptible by Ctrl+C, silently swallowing the very signal meant to stop it. Second, return inside a finally block is a genuinely dangerous, little-known trap: if finally contains its own return (or break, or continue), it UNCONDITIONALLY overrides any exception propagating through the try block, or any return value the try block already produced - the exception is discarded entirely, not merely delayed, with zero warning. Third, except Exception: is meaningfully narrower and safer than bare except: (it excludes KeyboardInterrupt/SystemExit/GeneratorExit), but it is still broad enough to hide programming mistakes like a typo'd variable name (NameError) or a wrong-type argument (TypeError) behind the same handler meant only for an expected, specific failure like a missing file."""},

            {"h": "HOW A PROFESSIONAL LOGS AND FAILS SECURELY", "body": r"""Professional error handling logs the FULL exception object, not just its message string - logging.exception('failed to process order'), called from inside an except block, automatically captures and formats the complete traceback, because str(ex) alone throws away exactly the frame-by-frame information needed to find the real cause later, especially for a bug that only reproduces in production. Re-raising deliberately (a bare raise inside an except block, naming no exception) preserves the ORIGINAL traceback untouched, different from raise ex, a common mistake that resets where Python thinks the exception "started" to the re-raise line itself, hiding the true origin from anyone reading the traceback afterward. Beyond logging, security-conscious code follows a fail-SECURE default: an authorization check wrapped in a try/except should treat any unexpected exception during the check as "deny," never "allow" - a bug or unanticipated edge case in the permission logic should never accidentally fail open just because some unrelated exception interrupted the check before it reached an explicit "allow" statement."""},

            {"h": "WHERE THIS IS GOING: ERROR HANDLING AS A SECURITY BOUNDARY", "body": r"""Exception handling is not just about keeping a program from crashing - it is a real security boundary, because what an exception reveals or does under failure is frequently the difference between a robust system and an exploitable one. A raw traceback shown to an end user, a classic debug page left enabled in production, discloses file system paths, library versions, sometimes literal source code or configuration values - information an attacker uses to fingerprint your stack and target known vulnerabilities in the exact versions revealed, precisely why production deployments must catch broadly at the outermost boundary, show a generic message, and log the real detail somewhere the attacker cannot see. The fail-secure principle generalizes far beyond authorization checks: parsing untrusted input, verifying a cryptographic signature, checking a rate limit - any of these should treat an unexpected internal error as "reject," never "proceed as if it succeeded," because an attacker who can reliably trigger the exceptional path can otherwise turn your own defensive code into the very bypass it was meant to prevent. Reading tracebacks correctly and chaining exceptions honestly is also simply what makes YOUR OWN debugging sessions faster, the more immediate payoff long before any of this becomes about an adversary at all."""},
        ],
    },

    "py-6": {
        "title_check": "Testing your own code",
        "sections": [
            {"h": "MENTAL MODEL: A TEST IS CODE THAT MAKES A CLAIM AND CHECKS IT IMMEDIATELY", "body": r"""An assert statement is a claim about your code stated as an executable sentence: assert add(2, 3) == 5 literally means "I claim this expression is true; if it is not, stop everything right now and tell me exactly which line lied." This is a fundamentally different mode from print-and-eyeball debugging, where YOU compare output to what you expected, silently, in your head, and can simply be wrong or inattentive with no signal - an assert makes the comparison mechanical and impossible to skim past, because a failed assertion halts the program immediately with an AssertionError naming the exact expression that failed. The discipline this enables is writing the claim BEFORE you fully trust the code, not after - deciding what add(2,3) should equal, and what add(-1,1) and add(0,0) should equal, is a way of specifying behavior in executable form, which is a large part of why tests are often described as a specification the computer can check for you, rather than merely a check you write after the fact once the code already seems to work."""},

            {"h": "MECHANISM: assert COMPILES TO A CHECK GUARDED BY __debug__", "body": r"""An assert statement is not always guaranteed to run - Python compiles assert <expr> into a check guarded by the built-in __debug__ flag, roughly equivalent to if __debug__ and not <expr>: raise AssertionError(...), and __debug__ is True in normal execution but becomes False the moment Python starts with the -O (optimize) flag, at which point the compiler strips every assert statement out of the bytecode ENTIRELY - not merely skips them at runtime, removes them at compile time, so the expression inside is not even evaluated. This has a concrete, important consequence: assert must never be used to validate untrusted input or enforce a genuine runtime invariant your program's correctness depends on in production, because assert validate_permissions(user), 'access denied' can be silently deleted by running python -O main.py, turning a security check into a no-op with no warning whatsoever. asserts are for catching YOUR OWN bugs during development and testing - internal invariants you believe must hold if your code is correct - never for gatekeeping real users or real data, which belongs in an explicit if statement raising a real exception (ValueError, PermissionError) regardless of any optimization flag."""},

            {"h": "WORKED EXAMPLE: FIVE ASSERTS THAT ACTUALLY EARN THEIR PLACE", "body": r"""Given def add(a, b): return a + b, five asserts that each earn their place cover genuinely different classes of input, not five near-duplicates of the same case:

    assert add(2, 3) == 5          # the ordinary case
    assert add(-1, 1) == 0         # negative plus positive
    assert add(0, 0) == 0          # the identity/zero case
    assert add(-5, -7) == -12      # both negative
    assert add(1000000, 1) == 1000001   # a boundary-ish large value

Five asserts that all resembled assert add(1,1)==2, assert add(2,2)==4, assert add(3,3)==6 would test the SAME code path five times and miss an entire class of bug - a function that only breaks on negative numbers, or only on zero, would sail through all five and still be broken. The actual skill being practiced is not "write five asserts," it is partitioning the input space into meaningfully different regions first (normal, zero/empty, negative, boundary/large, wrong-type if relevant) and writing one assert per region - precisely the mental model real test suites and, later, automated fuzzers scale up mechanically far beyond what you could enumerate by hand."""},

            {"h": "FAILURE MODES: FLOATING-POINT ASSERTS AND TESTS THAT LEAK STATE BETWEEN EACH OTHER", "body": r"""Two test-writing bugs are common enough to name explicitly. First, asserting exact equality on floating point results: assert 0.1 + 0.2 == 0.3 actually FAILS, not because addition is broken, but because 0.1 and 0.2 have no exact binary floating-point representation, so their sum is 0.30000000000000004, a tiny bit off from the literal 0.3 - the fix is never comparing floats with ==, instead checking the difference is within a small tolerance, assert abs((0.1 + 0.2) - 0.3) < 1e-9, or using math.isclose(a, b), which does this correctly by default. Second, tests silently leaking state into each other through shared mutable objects: if two test functions both call a helper that mutates a module-level list or a shared fixture object, the ORDER the tests happen to run in can change their outcome - a test that passes alone but fails only when run after another specific test is almost always this exact bug, and it is one of the most frustrating to diagnose precisely because the failing test code looks completely correct in isolation; the fix is ensuring every test constructs its own fresh data rather than reusing anything mutable from a previous test or a shared global."""},

            {"h": "HOW A PROFESSIONAL SCALES ASSERT-THINKING INTO REAL TEST SUITES AND FUZZING", "body": r"""Professionals keep the exact mental model from asserts - partition the input space, write a claim, check it mechanically - but scale it up in two directions. unittest or pytest replace manually run assert scripts with automatic test DISCOVERY (every test_*.py file and test_* function found and run without listing them by hand) and a report of exactly which of hundreds of assertions failed, rather than a single script halting at its first failed assert and never running the rest - a real limitation of raw asserts you have likely already felt. Mocking replaces a real dependency (a network call, a database, the current time) with a fake, controllable stand-in so a test can assert exact behavior without depending on network I/O actually succeeding - the underlying claim-and-check idea is unchanged, only what you check against is now fully under your control. Fuzzing is the mechanical extreme of the edge-case mindset: instead of a human hand-picking "zero, negative, huge" as boundary cases, a fuzzer generates enormous numbers of essentially random or mutated inputs automatically and asserts a much weaker, universal claim - "this must never crash, hang, or corrupt memory, no matter what bytes you feed it" - exactly how real vulnerabilities are found in production software today, at a scale no human writing individual asserts could ever match."""},

            {"h": "WHERE THIS IS GOING: THE EDGE-CASE MINDSET AS SECURITY THINKING", "body": r"""The habit this lesson is really building - systematically asking "what is the smallest input, the empty one, the negative one, the huge one, the wrong-typed one" before trusting a function - is the exact same mental habit that later becomes vulnerability research. A buffer overflow, an integer overflow, an injection bug: every one of these is, at its root, a case the original developer's mental test suite never considered, an input from a region of the space nobody partitioned out and checked, exactly like the untested negative case in a home-grown add() function, just with more severe consequences than a wrong sum. Security researchers and CTF players spend enormous energy doing deliberately, by hand or with fuzzing tools, exactly what this lesson asks you to do on your own five-line functions: enumerate the input space more completely than whoever wrote the code originally did, and check a claim about what SHOULD happen at each boundary. Treat every "think in edge cases" habit built here as directly transferable, not a separate skill picked up later - the difference between testing your own stats.py and testing someone else's authentication endpoint is scale and adversarial intent, not method."""},
        ],
    },

}
