# depth_asm.py — extended teaching content for the asm track.
# Auto-attached by depth.py. One entry per lesson id.
# Environment: Windows x64, nasm + gcc (MSYS2 ucrt64), Intel syntax, Microsoft x64 calling
# convention (args rcx/rdx/r8/r9, 32-byte shadow space, 16-byte alignment, `default rel`).
DEPTH = {
    "asm-1": {
        "title_check": "Registers & moving data",
        "sections": [
            {"h": "MENTAL MODEL: REGISTERS ARE THE CPU'S ONLY FAST HANDS", "body": r"""A CPU cannot compute on memory directly the way a high-level language pretends. Almost every operation works on registers - a tiny set of on-chip slots, sixteen general-purpose ones on x86-64, each 64 bits wide. Think of RAM as a warehouse and registers as the few items on your desk: to add two numbers living in memory, the CPU must first MOVE each into a register, ADD register-to-register, then MOVE the result back out. That load-compute-store rhythm is the shape of nearly all assembly. The sixteen 64-bit registers are rax, rbx, rcx, rdx, rsi, rdi, rbp, rsp, and r8 through r15. Some carry historical roles baked into the instruction set (rax is the implicit accumulator for mul/div; rsp is the stack pointer; rcx is a loop/shift counter), but most are yours to use freely once you respect the calling convention. The single most important shift from thinking in C is that a register has no type - it is 64 raw bits. Whether those bits mean a signed integer, an unsigned count, a pointer, or a character is decided entirely by which instruction you apply to them. mov never cares; add treats them as integers; the comparison you choose (signed vs unsigned jump) is what imposes meaning."""},
            {"h": "MECHANISM: SUB-REGISTERS AND THE 32-BIT ZERO-EXTENSION RULE", "body": r"""Each 64-bit register exposes smaller views of its low bytes, inherited from decades of x86 evolution. rax's low 32 bits are eax; its low 16 are ax; ax splits into ah (bits 8-15) and al (bits 0-7). The newer r8-r15 use suffixes: r8d (32-bit), r8w (16-bit), r8b (8-bit). Writing a sub-register affects only those bits - with ONE crucial exception that trips up everyone. Writing any 32-bit register automatically ZEROES the upper 32 bits of the full 64-bit register. Writing 8- or 16-bit registers does NOT; those leave the high bits untouched.
    mov rax, 0x1111111111111111
    mov eax, 5          ; rax is now 0x0000000000000005, not 0x1111111100000005
    mov al, 5           ; rax keeps its high bits: ...11110005
This asymmetry exists because 64-bit mode was designed to make the common case (32-bit math) cheap and predictable, avoiding a partial-register stall. In practice it means `xor eax, eax` is the idiomatic, shortest way to zero the entire rax - the implicit zero-extension clears all 64 bits for free."""},
            {"h": "WORKED EXAMPLE: MOVING AND COMBINING VALUES", "body": r"""Here is a minimal program that computes 7 + 5 and returns it as the process exit code, so you can read the answer from the shell. Assemble and run it in the MSYS2 ucrt64 shell:
    default rel
    global main
    section .text
    main:
        mov eax, 7        ; eax = 7  (also zeroes the top half of rax)
        add eax, 5        ; eax = 12
        ret               ; return value is in eax/rax by convention
Build and check the result:
    nasm -f win64 add.asm -o add.obj
    gcc add.obj -o add.exe
    ./add.exe; echo $?      # prints 12
`echo $?` reads the last program's exit status, which C runtime takes from eax. Notice we used eax, not rax: the return value is only an int here, and writing eax zero-extends so rax is a clean 12. Every line is load-compute: put a literal in a register, operate, hand the register back. There is no `add 7, 5` that works on bare numbers - operands must be registers, memory, or immediates in the shapes each instruction allows."""},
            {"h": "FAILURE MODES: SIZE MISMATCHES AND OPERAND RULES", "body": r"""Three mistakes dominate early assembly. First, mixing operand sizes: `mov rax, ebx` is illegal because the sizes differ - the assembler expects both operands the same width. To widen deliberately you use movzx (zero-extend) or movsx (sign-extend): `movzx rax, bl` takes a byte and fills the upper bits with zeros; `movsx rax, bl` copies the sign bit, so 0xFF (-1 as a signed byte) becomes 0xFFFFFFFFFFFFFFFF. Choosing the wrong one silently corrupts signed values. Second, memory-to-memory moves do not exist: `mov [x], [y]` is invalid because at most one operand may be a memory reference; you must go through a register. Third, forgetting the zero-extension rule and assuming `mov al, 0` cleared the whole register, then reading rax and finding stale high bytes. When a value looks impossibly large in a debugger, suspect leftover high bits from a sub-register write. The assembler catches size errors at build time, but the zero-extension and sign-extension bugs compile cleanly and only show up as wrong numbers at runtime - exactly the class of bug assembly is infamous for."""},
            {"h": "READING COMPILER OUTPUT: gcc -S AND objdump -d", "body": r"""You rarely write large assembly by hand; you READ what the compiler produced. Two tools make this a habit. `gcc -S -masm=intel prog.c -o prog.s` stops after compilation and writes human-readable Intel-syntax assembly, letting you see exactly how a C statement became instructions. `objdump -d -M intel prog.exe` disassembles a finished binary. Try compiling `int add(int a,int b){return a+b;}` and you will see something close to:
    add:
        lea eax, [rdi + rsi]   ; on Linux/SysV: args in edi, esi
        ret
On Windows the same function uses ecx and edx for the first two args - the calling convention differs, which is why knowing YOUR ABI matters. Reading disassembly trains pattern recognition: you start to recognize a function prologue (push rbp; mov rbp, rsp), a loop (a compare and a conditional jump backward), and argument shuffling. This is the core skill of reverse engineering and debugging optimized code where no source is handy - the compiler is a translator, and assembly is how you check its work."""},
            {"h": "WHERE THIS GOES: REGISTERS UNDERPIN EVERYTHING AHEAD", "body": r"""Every later lesson builds on this one. Control flow (next lesson) is registers plus the flags a comparison sets. The stack is just memory addressed through rsp, with call and ret moving a return address in and out. Calling conventions are a rulebook for which registers carry arguments (rcx, rdx, r8, r9 on Windows) and which a function must preserve. Addressing modes are the syntax for computing a memory address inside the brackets of a mov. Master the idea that a register is 64 untyped bits you shuttle values through, and that only the instruction decides what those bits mean, and the rest of x86-64 becomes a set of variations on that theme. A concrete habit to build now: whenever you read a line of assembly, silently narrate the data flow - "this loads a pointer into rax", "this adds the loop counter" - because assembly has no names, only registers and offsets, and the narration is how you rebuild the lost meaning that variable names used to give you for free."""},
        ],
    },
    "asm-2": {
        "title_check": "Control flow & flags",
        "sections": [
            {"h": "MENTAL MODEL: THERE ARE NO IF-STATEMENTS, ONLY JUMPS", "body": r"""High-level control flow - if, while, for, switch - does not exist in the machine. There are only two primitives: unconditional jumps (jmp, which sets the instruction pointer to a new address) and conditional jumps (je, jl, jg, and friends, which jump only if a condition holds). Everything structured is built from these plus a comparison. The CPU executes instructions in address order until a jump redirects it. An `if (a > b) { X } else { Y }` becomes: compare a and b, conditionally jump over X to Y, and put an unconditional jump at the end of X so it skips Y. A `while` loop is a compare-and-jump at the bottom (or top) that sends the instruction pointer backward. Once you internalize that all control flow is "compute a condition, then jump or fall through", disassembly stops looking like noise. The condition itself is never passed directly to the jump - it is left behind in a special register, the FLAGS register, by whatever instruction ran last. The jump then reads those flags. This decoupling - one instruction sets flags, a later one acts on them - is the mechanism that makes x86 control flow work, and the thing beginners most often miss."""},
            {"h": "MECHANISM: THE FLAGS REGISTER, cmp, AND test", "body": r"""RFLAGS is a register whose individual bits record facts about the last arithmetic or logical result. The four that matter most: ZF (zero flag, set when the result was zero), SF (sign flag, the top bit of the result), CF (carry flag, unsigned overflow/borrow), and OF (overflow flag, signed overflow). Ordinary instructions like add, sub, and and set these as a side effect. Two instructions exist purely to set flags without keeping a result. `cmp a, b` computes a - b, sets the flags, and throws the difference away - so afterward ZF means a == b, and the sign/overflow relationship tells you which was larger. `test a, b` computes a AND b and discards it; `test rax, rax` is the standard way to ask "is rax zero?" because ANDing a value with itself is the value, so ZF ends up set exactly when rax is zero. The conditional jump you write must match the SIGNEDNESS of your data: je/jne read ZF, jl/jg (signed: "less/greater") read SF and OF together, jb/ja (unsigned: "below/above") read CF. Choosing jl where you meant jb is a real, silent bug when comparing pointers or sizes."""},
            {"h": "WORKED EXAMPLE: A LOOP THAT SUMS 1..N", "body": r"""This computes 1+2+...+5 = 15 and returns it. Follow the flags reasoning as you read:
    default rel
    global main
    section .text
    main:
        xor eax, eax          ; sum = 0
        mov ecx, 1            ; i = 1
    .loop:
        cmp ecx, 5           ; compare i with 5 -> sets flags
        jg .done             ; if i > 5 (signed greater), exit
        add eax, ecx         ; sum += i
        inc ecx              ; i++
        jmp .loop            ; go back and test again
    .done:
        ret                  ; sum (15) is in eax
Read it as the machine does: at .loop we compare i to 5, which sets ZF/SF/OF; jg inspects those flags and either falls through (keep looping) or jumps to .done. The backward `jmp .loop` is the entire "loop" - there is no loop keyword. Labels beginning with a dot are nasm local labels, scoped to the surrounding global label, so you can reuse .loop in another function without a clash. Trace it once on paper: i=1..5 adds into eax, i=6 fails the jg test, done."""},
            {"h": "FAILURE MODES: STALE FLAGS AND SIGNED/UNSIGNED MIXUPS", "body": r"""The commonest control-flow bug is a jump reading flags set by the wrong instruction. Because many instructions modify flags, inserting an innocent-looking `add` or `mov`-that-is-really-`inc` between your cmp and your conditional jump can change the outcome - though note mov itself does NOT touch flags, which is why it is safe to shuffle data between a cmp and a jcc, but inc/dec/add are not. The second classic bug is signedness. Comparing two large unsigned values (say two 64-bit addresses) with jl/jg treats the high bit as a sign, so an address of 0x8000000000000000 looks "negative" and compares as less than a small address - use jb/ja for unsigned. The third is off-by-one from testing at the wrong edge: `jg` vs `jge` shifts the loop bound by one iteration, the assembly equivalent of `<` vs `<=`. When a loop runs one time too many or too few, the conditional jump's exact variant is the first thing to check. None of these are assembler errors; they compile and simply produce wrong answers, so reading the jump condition carefully is the discipline that replaces the type checker you no longer have."""},
            {"h": "READING DISASSEMBLY: RECOGNIZING LOOPS AND BRANCHES", "body": r"""In disassembled code, structured control flow leaves recognizable fingerprints. A forward conditional jump whose target is just past a small block is an `if`. A conditional jump forward plus an unconditional jump at the block's end is an `if/else`. A conditional (or unconditional) jump BACKWARD to an earlier address is a loop - the backward edge is the giveaway. Compilers often arrange loops so the condition is tested at the bottom (a single conditional jump backward), with an initial jump to that test, because it produces one branch per iteration instead of two. When you run `objdump -d -M intel` on optimized code you will see cmp/test immediately followed by a jcc over and over; annotating each jcc with "this is the loop back-edge" or "this skips the else" is how you reconstruct the original structure. This reading skill is the foundation of debugging release builds and of reverse engineering, where the source is gone and the jump graph is all you have to recover the program's logic."""},
            {"h": "WHERE THIS GOES: BRANCHES + STACK = FUNCTIONS", "body": r"""Conditional jumps and flags are half of what makes real programs; the other half, coming next, is the stack, which lets control flow nest - call a function, run its branches and loops, and return exactly where you left off. call is really "push a return address, then jmp"; ret is "pop that address into the instruction pointer". So the same jump machinery you just learned scales up into function calls once you add a place to remember where to come back to. Flags also feed conditional MOVES (cmovg and friends) and the SET instructions (setg al) that turn a comparison into a 0/1 byte - the assembly of a C boolean expression. Keep practicing the two-step read: find the instruction that set the flags, then the jump that consumed them. That pairing, repeated, is the literal grammar of every branch and loop the CPU will ever run, and fluency in it is what lets you follow code that has no names, no indentation, and no comments."""},
        ],
    },
    "asm-3": {
        "title_check": "The stack, call & ret",
        "sections": [
            {"h": "MENTAL MODEL: THE STACK IS MEMORY THAT GROWS DOWNWARD", "body": r"""The stack is an ordinary region of RAM plus one register, rsp, that points at its current top. What makes it a stack is a convention: it grows toward LOWER addresses. `push rax` subtracts 8 from rsp and stores rax at the new [rsp]; `pop rax` loads [rsp] into rax and adds 8 back. So "down" (smaller addresses) is deeper into the stack, and the newest item sits at the lowest address. This backwards-growing layout is a historical choice, but it is universal on x86-64 and you must picture it correctly or every stack diagram you draw will be upside down. The stack serves three jobs: it remembers return addresses so functions can nest, it holds local variables that do not fit in registers, and it preserves registers a function must not clobber. Because it is just memory, you can also address it directly - [rsp+8], [rsp+16] - to reach values below the top without popping them, which is how locals and spilled arguments are accessed. The register rbp is often used as a stable "frame pointer" anchored at the function's entry so locals can be named as fixed offsets from rbp even as rsp moves around during the function."""},
            {"h": "MECHANISM: call PUSHES, ret POPS, THE RETURN ADDRESS", "body": r"""`call target` does two things atomically: it pushes the address of the NEXT instruction (the place to resume) onto the stack, then jumps to target. `ret` reverses it: it pops that saved address off the stack into the instruction pointer, so execution continues right after the original call. This is the whole mechanism of function nesting - the stack naturally supports it because calls unwind in last-in-first-out order, exactly matching how functions return in reverse of how they were called.
    main:
        call foo        ; pushes return addr, jumps to foo
        ; <- ret in foo comes back HERE
        ret
    foo:
        ret             ; pops the saved address, returns to main
Crucially, ret trusts whatever is on top of the stack to be a valid return address. If your function pushed something and forgot to pop it, ret will jump to garbage. The stack pointer's balance across a function - every push matched by a pop, every `sub rsp, N` matched by an `add rsp, N` - is therefore not a style preference but a correctness requirement enforced by ret at runtime."""},
            {"h": "WORKED EXAMPLE: A FUNCTION WITH A PROPER FRAME", "body": r"""A function that uses the stack for a local and calls printf, following the Windows x64 rules (32 bytes of shadow space, 16-byte alignment):
    default rel
    global main
    extern printf
    section .data
    fmt db "sum=%d", 10, 0
    section .text
    main:
        push rbp             ; save caller's frame pointer
        mov rbp, rsp         ; establish our frame
        sub rsp, 32          ; shadow space for the printf call
        lea rcx, [fmt]       ; 1st arg: format string
        mov edx, 12          ; 2nd arg: the value
        call printf
        xor eax, eax         ; return 0
        add rsp, 32          ; release shadow space
        pop rbp              ; restore caller's frame pointer
        ret
The push rbp / mov rbp, rsp pair is the standard prologue; the matching pop rbp / ret is the epilogue. The `sub rsp, 32` reserves the shadow space every Windows x64 call requires, and the matching `add rsp, 32` releases it, keeping rsp balanced. Miss either half and ret finds the wrong value on top."""},
            {"h": "FAILURE MODES: IMBALANCE, ALIGNMENT, AND SMASHED FRAMES", "body": r"""Stack bugs are the most dramatic in assembly because they corrupt control flow itself. An unbalanced stack - a push without a pop, or reserving N bytes and freeing a different amount - leaves rsp pointing at the wrong place, so ret reads a non-address and the program jumps into oblivion, usually crashing instantly but sometimes executing random bytes. A subtler Windows/x64 failure is misalignment: the ABI requires rsp to be 16-byte aligned at the point of a call, and some library functions (especially those using SIMD) will fault if it is not. Because call itself pushes 8 bytes, your prologue arithmetic must account for that - this is why you often see `sub rsp, 40` (32 shadow + 8 to realign) rather than 32. Finally, writing past the end of a local buffer overwrites the saved return address sitting higher on the stack, so the function returns to a corrupted location - the mechanism behind an entire class of memory-safety failures, and the reason modern compilers insert stack canaries and the OS randomizes stack addresses (ASLR) as defenses."""},
            {"h": "READING DISASSEMBLY: SPOTTING PROLOGUES AND LOCALS", "body": r"""When you disassemble any nontrivial function, the first few instructions almost always reveal the frame. `push rbp; mov rbp, rsp` is the textbook prologue - see it and you know rbp now anchors the frame, and locals will appear as [rbp-8], [rbp-16], and so on, while arguments spilled to the stack appear as [rbp+16] and up (past the saved rbp and return address). A `sub rsp, N` right after tells you N bytes of locals/shadow space were reserved. Optimized code may omit the frame pointer (compiling with something like -fomit-frame-pointer) and address everything off rsp directly, which is faster but harder to read because rsp moves. Recognizing the prologue/epilogue pair lets you mentally bracket a function and know where its locals live, which is the first step in understanding or debugging code you did not write. In a debugger, dumping memory around rsp and rbp and matching offsets to the disassembly is how you inspect a live call frame."""},
            {"h": "WHERE THIS GOES: THE STACK IS THE SPINE OF CALLING CONVENTIONS", "body": r"""Everything about how functions talk to each other - which registers carry arguments, who must preserve what, where extra arguments and return addresses live - is layered on top of the stack you just learned. The next lessons formalize that as the calling convention and the ABI. The shadow space you reserved here is a Windows-specific stack rule; the alignment requirement is another; the distinction between caller-saved and callee-saved registers determines which values you must push before a call to protect them. Because the stack is also where a program's live call history is recorded, it is what a debugger walks to produce a backtrace, and its predictable layout is exactly what memory-corruption defenses (canaries, non-executable stacks, ASLR) are designed to protect. Keep the core invariant in mind above all: leave rsp exactly as you found it, because ret stakes the entire program's control flow on the value sitting at the top of the stack when your function ends."""},
        ],
    },
    "asm-4": {
        "title_check": "Syscalls & reading disassembly",
        "sections": [
            {"h": "MENTAL MODEL: HOW A PROGRAM ASKS THE OS FOR SOMETHING", "body": r"""User code cannot write to a file or a screen by itself - those are privileged operations only the operating system kernel may perform. A program crosses that boundary through a system call: it puts a request number and arguments in agreed-upon registers and executes a special instruction that traps into the kernel. On Linux x86-64 that instruction is `syscall`; the call number goes in rax and arguments in rdi, rsi, rdx, r10, r8, r9. On Windows the picture is different and important to understand: applications almost never issue raw syscalls, because Microsoft does not guarantee stable syscall numbers between OS versions. Instead you call documented functions in system DLLs (kernel32.dll, ntdll.dll) - for example WriteFile or printf from the C runtime - and those libraries perform the actual transition internally. So on your MSYS2/Windows setup, "making a syscall" in practice means calling a library function with the Windows x64 convention (rcx, rdx, r8, r9 plus shadow space), and letting the C runtime or Win32 layer bridge to the kernel. Knowing that a call to printf ultimately becomes a kernel transition explains why these calls are relatively expensive and why the ABI around them is so strict."""},
            {"h": "MECHANISM: THE WINDOWS PATH VS THE LINUX syscall INSTRUCTION", "body": r"""Contrast the two worlds directly. On Linux, printing "hi" can be done with a raw syscall to write (call number 1):
    ; Linux SysV - shown for contrast, NOT your Windows setup
    mov rax, 1          ; sys_write
    mov rdi, 1          ; fd 1 = stdout
    lea rsi, [msg]      ; buffer
    mov rdx, 2          ; length
    syscall
On Windows you instead call a library function under the Microsoft x64 convention:
    default rel
    global main
    extern printf
    section .data
    msg db "hi", 10, 0
    section .text
    main:
        sub rsp, 40         ; shadow space + alignment
        lea rcx, [msg]      ; 1st arg in rcx (not rdi!)
        call printf
        add rsp, 40
        xor eax, eax
        ret
The argument registers differ (rdi/rsi on Linux vs rcx/rdx on Windows), and Windows demands shadow space that Linux does not. Mixing the two conventions up - a habit if you learn from Linux tutorials - is the single most common reason a Windows assembly program crashes on its first library call."""},
            {"h": "WORKED EXAMPLE: DISASSEMBLING A REAL BINARY", "body": r"""The practical skill this lesson builds is reading disassembly, because that is how you understand compiled code and library calls. Compile a tiny C program and inspect it:
    // hello.c
    #include <stdio.h>
    int main(void){ puts("hi"); return 0; }
    gcc hello.c -o hello.exe
    objdump -d -M intel hello.exe | less
Search for `<main>:` and you will see something like:
    main:
        sub    rsp, 0x28            ; reserve shadow space + align
        lea    rcx, [rip+0x...]     ; load address of "hi" into rcx
        call   ... <puts>           ; call the library function
        xor    eax, eax             ; return 0
        add    rsp, 0x28
        ret
Every element from the previous sections is visible: the shadow-space reservation (0x28 = 40 bytes), the first argument passed in rcx via a RIP-relative lea (that is `default rel` in action), the call, and the balanced cleanup. Reading real objdump output like this - rather than only hand-written examples - is what turns assembly from a writing exercise into a comprehension skill."""},
            {"h": "FAILURE MODES: WRONG ABI, MISSING SHADOW SPACE, BAD lea", "body": r"""When a library call misbehaves, suspect the boundary rules first. Passing the first argument in rdi because you copied a Linux example means the Windows function reads rcx and finds garbage - a crash or nonsense output. Omitting shadow space means the callee writes into your stack frame's return-address area, corrupting the return and crashing on ret. Using `mov rcx, [msg]` when you meant `lea rcx, [msg]` passes the first eight bytes of the string interpreted as a pointer instead of the string's address - the classic mov-vs-lea confusion, fatal here because printf then dereferences a bogus pointer. And forgetting `default rel` on data can produce addresses that are wrong once the loader places the image, since without RIP-relative addressing the assembler may emit an absolute address the position-independent image cannot honor. All of these compile cleanly; they are runtime faults. The debugging move is to set a breakpoint at the call, inspect rcx/rdx/r8/r9 and rsp's alignment, and confirm each matches what the function's documented prototype expects."""},
            {"h": "PROFESSIONAL PRACTICE: objdump, gdb, AND FOLLOWING CALLS", "body": r"""Analysts live in the disassembler. Beyond `objdump -d -M intel`, a debugger like gdb (available in MSYS2) lets you step instruction by instruction: `layout asm`, `starti`, then `stepi`/`nexti`, watching registers with `info registers` at each call boundary. The workflow for understanding an unfamiliar function is: find its prologue to bracket it, identify each `call` and the argument registers set just before it (that tells you the function's signature by convention), and follow conditional jumps to reconstruct its logic. When a call targets an imported library function, the import name usually survives in the binary's import table, so `call <printf>` is legible even without source. This is precisely the method used in malware analysis and vulnerability research done defensively - understanding what a binary does by reading its instructions and the OS/library calls it makes - and it is the reason a defender learns assembly: to comprehend software whose source they will never have."""},
            {"h": "WHERE THIS GOES: FROM INSTRUCTIONS TO CONVENTIONS", "body": r"""You now have every ingredient of a function that talks to the outside world: registers to hold values, flags and jumps for logic, a stack for nesting and locals, and the calling convention for crossing into libraries and the kernel. The final lesson pulls the convention together explicitly - the full rulebook of which registers are volatile, which are preserved, how the return value comes back, and how the stack is arranged at the moment of a call. The habit to carry forward is to always know WHICH ABI you are reading: the same instruction stream means different things under Windows x64 and Linux SysV because the register roles differ. Every time you see a call, mentally list the argument registers for your platform and check they were set. That discipline is what keeps hand-written assembly correct and what lets you read compiled binaries fluently, which is the durable, transferable skill this whole track is building toward."""},
        ],
    },
    "asm-5": {
        "title_check": "Addressing modes & memory operands",
        "sections": [
            {"h": "MENTAL MODEL: THE BRACKETS ARE A TINY ADDRESS CALCULATOR", "body": r"""In Intel syntax, square brackets mean "the memory at this address", and what goes inside is not just a register - it is a small arithmetic expression the CPU evaluates in hardware to produce an address. The full form is [base + index*scale + displacement], where base and index are registers, scale is 1, 2, 4, or 8, and displacement is a constant. `mov rax, [rbx]` reads memory at the address in rbx. `mov rax, [rbx + 8]` reads 8 bytes further on - the pattern for a struct field. `mov rax, [rbx + rcx*8]` reads the rcx-th 8-byte element of an array based at rbx - a scaled index, which is why scale exists: it matches element sizes (8 for a 64-bit array, 4 for int, 1 for bytes). This one addressing form directly encodes array indexing and struct access, the two operations high-level languages spend most of their time on. Understanding that the brackets compute an address before touching memory is the key: the CPU does base + index*scale + disp internally, then loads or stores at the result. It is a free multiply-add built into the instruction, which is also why lea (next section) is so useful for plain arithmetic."""},
            {"h": "MECHANISM: lea COMPUTES THE ADDRESS WITHOUT THE LOAD", "body": r"""`lea` (load effective address) uses the exact same bracket expression but does NOT touch memory - it computes the address and puts that NUMBER in the destination. This is the single most misunderstood instruction in x86.
    mov rax, [rbx + rcx*4 + 8]   ; rax = the VALUE stored at that address
    lea rax, [rbx + rcx*4 + 8]   ; rax = the ADDRESS itself (rbx + rcx*4 + 8)
Because the address calculation is a general base + index*scale + disp, compilers exploit lea as a fast arithmetic instruction that has nothing to do with pointers: `lea rax, [rbx + rbx*4]` computes rax = rbx*5 in one instruction, no multiply unit needed. So when you read disassembly, a lea might be a genuine "take the address of this array element" OR it might be the compiler doing math. You tell them apart by context: is the result later dereferenced (used inside brackets) or just used as a number? On Windows with `default rel`, taking the address of a global uses RIP-relative form, `lea rcx, [msg]`, which the assembler encodes as an offset from the instruction pointer so the image stays position-independent."""},
            {"h": "WORKED EXAMPLE: WALKING AN ARRAY WITH A SCALED INDEX", "body": r"""Sum a small array of 32-bit integers using base + index*scale addressing:
    default rel
    global main
    section .data
    arr dd 10, 20, 30, 40        ; four 4-byte ints
    section .text
    main:
        lea rbx, [arr]           ; rbx = base address of the array
        xor eax, eax             ; sum = 0
        xor ecx, ecx             ; index i = 0
    .loop:
        cmp ecx, 4
        jge .done
        add eax, [rbx + rcx*4]   ; sum += arr[i]; scale 4 = int size
        inc ecx
        jmp .loop
    .done:
        ret                      ; returns 100
The heart is `add eax, [rbx + rcx*4]`: the CPU computes rbx + rcx*4 to land exactly on element i (because each int is 4 bytes), reads that memory, and adds it. Change the array to `dq` (8-byte quadwords) and the scale must become 8 to match - the scale is not decoration, it is the element size, and mismatching it reads halfway into elements and returns nonsense. This is literally how `arr[i]` compiles in C."""},
            {"h": "FAILURE MODES: WRONG SCALE, mov/lea CONFUSION, SIZE AMBIGUITY", "body": r"""Three addressing bugs recur. First, a scale that does not match the element size: using rcx*4 to index an array of 8-byte values reads overlapping, misaligned garbage - the assembly version of pointer arithmetic on the wrong type. Second, the mov/lea mix-up in both directions: writing `mov rax, [x]` when you wanted the address gives you the value, and `lea rax, [x]` when you wanted the value gives you the address; downstream, one of them dereferences a number that was never a pointer and crashes. Third, size ambiguity when storing an immediate to memory: `mov [rbx], 5` is ambiguous because the assembler cannot tell if you mean a byte, word, dword, or qword, so you must write `mov dword [rbx], 5` to specify. Forgetting the size qualifier is a build error (helpfully caught), but the scale and mov/lea bugs compile silently and surface as wrong values or crashes. When array code returns garbage, the scale is the first suspect; when a pointer faults, ask whether a lea should have been a mov or vice versa."""},
            {"h": "READING DISASSEMBLY: ADDRESSING MODES REVEAL DATA STRUCTURES", "body": r"""Addressing modes are how you reverse-engineer data layout from code with no type information. `[rbx + rcx*8]` in a loop screams "array of 8-byte elements indexed by rcx". A constant displacement like `[rax + 0x10]` repeated with different offsets (0x0, 0x8, 0x10) is almost certainly struct field access - the offsets are the field positions, and their spacing tells you the field sizes and any padding. A RIP-relative `[rip + 0x...]` is a reference to a global or a string literal. By cataloguing the addressing forms a function uses, you can reconstruct the shape of the structures it operates on even when the original type declarations are long gone - a core technique in binary analysis. Tools like a disassembler's cross-reference view build on exactly this: they follow the base registers and offsets to infer that some object has fields at 0, 8, and 16. Practicing "what data structure does this addressing imply?" turns opaque memory accesses into a readable map of the program's data."""},
            {"h": "WHERE THIS GOES: ADDRESSING IS POINTERS MADE CONCRETE", "body": r"""This lesson is the machine-level meaning of everything C teaches about pointers and arrays. `arr[i]` is base + index*scale; `p->field` is base + displacement; `&x` is a lea; `*p` is a mov through brackets. Seeing that equivalence makes both languages clearer - C's pointer arithmetic is no longer mysterious once you know it compiles to a scaled index, and assembly's brackets are no longer cryptic once you map them back to array and struct access. The last lesson, calling conventions, will use addressing constantly: arguments beyond the register set live on the stack at [rsp + offset], and locals are accessed as [rbp - offset]. Carry forward the two habits from here - always match the scale to the element size, and always know whether an instruction wants the value (mov) or the address (lea). Those two checks catch the majority of memory-operand bugs and are exactly what you scan for when reading someone else's disassembled code."""},
        ],
    },
    "asm-6": {
        "title_check": "Calling conventions & the ABI",
        "sections": [
            {"h": "MENTAL MODEL: THE ABI IS A CONTRACT BETWEEN FUNCTIONS", "body": r"""A calling convention is an agreement that lets separately-compiled functions call each other without knowing each other's internals. It answers: where do arguments go, where does the return value come back, and which registers must a function leave untouched for its caller. Without such a contract, a function could clobber a register its caller was relying on, and nothing would work. The Application Binary Interface (ABI) is the full written version of this contract for a platform. Windows x64 and Linux/macOS (System V) use DIFFERENT ABIs, which is the single most important fact for you: the same assembly means different things depending on which contract is in force. The whole point is modularity - because everyone follows the same rules, code from a compiler, a hand-written routine, and a system DLL all interoperate. When you call printf, you are honoring the same contract printf's authors assumed. Getting the contract wrong is not a syntax error; it is a silent breach that corrupts data or crashes, because the callee will confidently read the registers the ABI told it to read, whatever you actually put there."""},
            {"h": "MECHANISM: THE WINDOWS X64 RULES IN FULL", "body": r"""Your platform is Microsoft x64. Its rules: the first four integer/pointer arguments go in rcx, rdx, r8, r9 in that order; arguments five and up go on the stack. Floating-point arguments use xmm0-xmm3. The return value comes back in rax (or xmm0 for floats). Every call requires 32 bytes of SHADOW SPACE reserved on the stack by the caller - room the callee may use to spill those four register arguments - even if the function takes fewer than four. The stack must be 16-byte aligned at the moment of the call. Registers split into two groups: VOLATILE (caller-saved) - rax, rcx, rdx, r8, r9, r10, r11 - which a called function may freely destroy, so if you need their values after a call you must save them yourself; and NON-VOLATILE (callee-saved) - rbx, rbp, rdi, rsi, r12-r15, rsp - which a function must preserve, restoring them before it returns if it uses them. Contrast Linux SysV: args in rdi, rsi, rdx, rcx, r8, r9, no shadow space, a 128-byte "red zone" below rsp, and a different volatile/non-volatile split. Learn YOUR rules cold; consult the other's only when reading foreign code."""},
            {"h": "WORKED EXAMPLE: A CONFORMING FUNCTION THAT CALLS ANOTHER", "body": r"""A function that takes two ints, adds them, prints the result, and returns it - honoring every Windows rule:
    default rel
    global main
    extern printf
    section .data
    fmt db "result=%d", 10, 0
    section .text
    main:
        push rbx             ; rbx is non-volatile: save before we use it
        sub rsp, 32          ; shadow space (stack now aligned: push+sub = 40)
        mov ebx, 30          ; keep a value across the printf call...
                             ; ...in rbx precisely because it is callee-saved
                             ; (printf must preserve it), unlike rcx/rdx
        lea rcx, [fmt]       ; arg1: format
        mov edx, ebx         ; arg2: the value
        call printf          ; printf may trash rax,rcx,rdx,r8-r11
        mov eax, ebx         ; return the preserved value
        add rsp, 32
        pop rbx              ; restore caller's rbx
        ret
Notice the deliberate choice of rbx to hold a value across the call: because the ABI marks rbx non-volatile, printf is contractually required to give it back unchanged. Had we used rcx or r8, printf could have destroyed it."""},
            {"h": "FAILURE MODES: THE FOUR CLASSIC ABI BREACHES", "body": r"""ABI violations are the hardest assembly bugs because they crash far from their cause. First, wrong argument registers - using Linux's rdi/rsi on Windows - so the callee reads uninitialized rcx/rdx; ubiquitous when learning from cross-platform tutorials. Second, missing or misaligned shadow space: without the 32 bytes, the callee's spills overwrite your return address; with the stack misaligned to 8 rather than 16, SIMD-using library code faults. Third, trusting a volatile register across a call - stashing a value in rcx, calling a function, and finding rcx changed, because the ABI explicitly permits that; the fix is to use a non-volatile register or push/pop around the call. Fourth, a function that clobbers a non-volatile register without saving it, breaking its OWN caller - the mirror image, and the reason you push rbx before using it. Every one of these compiles cleanly and fails at runtime, often with a corrupted stack that makes the backtrace itself unreliable. The diagnostic ritual: at each call boundary check argument registers, stack alignment, and shadow space against the callee's documented prototype."""},
            {"h": "READING DISASSEMBLY: THE ABI IS YOUR ROSETTA STONE", "body": r"""The calling convention is what lets you infer a function's signature from its disassembly without any source. If the code reads rcx and rdx before a call, that callee takes at least two integer arguments (on Windows). A `sub rsp, 0x28` prologue is the shadow-space-plus-alignment idiom (32 + 8). Saved non-volatile registers pushed in the prologue (push rbx, push rsi, push r12) and popped in the epilogue tell you which registers the function chose to use for values that must survive its internal calls. The value left in rax before ret is the return value. By reading assembly THROUGH the lens of the ABI, an untyped instruction stream regains its structure: you recover argument counts, return types, and the function's internal register discipline. This is the master skill the whole track builds toward - the ability to take a compiled binary with no symbols and reconstruct what its functions do and how they interface, which is the foundation of debugging optimized builds, analyzing untrusted software defensively, and understanding exactly what the machine is doing beneath your high-level code."""},
            {"h": "SYNTHESIS: EVERYTHING THE TRACK BUILT", "body": r"""Step back and see how the six lessons compose. Registers are the CPU's working set of untyped 64-bit values (lesson 1). Flags and jumps turn comparisons into control flow with no if-statements in sight (lesson 2). The stack gives control flow the ability to nest and gives functions their locals, with call/ret trusting its top for the return address (lesson 3). System and library calls cross into the OS under a strict register protocol (lesson 4). Addressing modes are pointers and arrays made concrete as base + index*scale + displacement (lesson 5). And the ABI is the contract binding it all together so independently written code interoperates (lesson 6). The through-line is that assembly has no names and no types - only registers, memory, and conventions - so fluency means constantly reconstructing the meaning that high-level languages gave you for free: narrating data flow, matching jumps to their flags, tracking the stack's balance, and reading every call through the ABI. That reconstruction skill, not memorizing mnemonics, is what makes you able to understand any program at the level the machine actually runs it."""},
        ],
    },
}
