# depth_linux.py — extended teaching content for the linux track.
# Auto-attached by depth.py. One entry per lesson id.
DEPTH = {
    "lx-1": {
        "title_check": "Move and manage",
        "sections": [
            {"h": "MENTAL MODEL: EVERYTHING IS A FILE UNDER ONE TREE", "body": r"""Linux has no drive letters. There is a single hierarchy rooted at /, and every disk, USB stick, and even many devices are grafted somewhere onto that one tree by mounting. Your home is /home/you; the root user's is /root; system binaries live in /bin and /usr/bin; configuration in /etc; running-kernel and process information in the virtual filesystems /proc and /sys, which are not real files on disk at all but a window into kernel state exposed AS files. This "everything is a file" philosophy means the same tools - cd, ls, cat, cp - work uniformly whether you are looking at a text document, a device, or live process data. A path is either absolute (starts with /, unambiguous from the root) or relative (interpreted from your current directory). Two names are always present in every directory: `.` means "here" and `..` means "the parent". Understanding that there is exactly one tree, and that your shell always sits at some current position within it (shown by `pwd`), is the foundation - every navigation command is just moving your position or naming a spot relative to it. Unlike Windows, filenames are case-sensitive: File.txt and file.txt are different files."""},
            {"h": "MECHANISM: cd, ls, AND WHAT THE FLAGS REALLY DO", "body": r"""`ls` lists a directory, but its power is in flags. `ls -l` gives the long form: permission bits, link count, owner, group, size, modification time, name. `ls -a` reveals hidden entries - any name starting with a dot, a convention (not a filesystem feature) for config files like .bashrc. `ls -la` combines them; `ls -lh` makes sizes human-readable (4.0K instead of 4096); `ls -lt` sorts by time, newest first, and `ls -ltr` reverses it so the newest is at the bottom near your prompt - the single most useful "what changed recently?" command. `cd` with no argument returns to your home directory (equivalent to `cd ~`); `cd -` jumps back to the previous directory you were in, a toggle that saves enormous time. Tab completion is not optional in practice: type a few letters and press Tab to complete a name, or Tab twice to list candidates. These are not conveniences layered on top - they are how fluent users actually move, and building the reflex early is the difference between crawling and flying in a shell."""},
            {"h": "WORKED EXAMPLE: SETTING UP A PROJECT FROM SCRATCH", "body": r"""Walk through creating and organizing a small project, narrating each step:
    cd ~                     # start at home
    mkdir -p proj/src proj/docs   # -p makes parents AND is silent if they exist
    cd proj
    touch src/main.c docs/README.md   # create empty files
    ls -R                    # -R recurses: shows the whole tree
    cp src/main.c src/main.c.bak      # keep a backup copy
    mv docs/README.md README.md       # move it up to the project root
    ls -la
The `-p` flag on mkdir does double duty: it creates intermediate directories (proj AND src in one call) and it does not error if the directory already exists, which makes it safe in scripts. `touch` creates an empty file if absent, or updates a file's timestamp if present. `cp src dst` copies; `mv src dst` moves OR renames (they are the same operation - moving to a new name in the same directory is a rename). Notice mv both relocated and renamed README in one step. Building the habit of composing these small commands into a workflow, rather than reaching for a file manager, is what shell fluency looks like in practice."""},
            {"h": "FAILURE MODES: THE COMMANDS THAT DELETE WITHOUT ASKING", "body": r"""Unix tools assume you meant what you typed and rarely ask for confirmation, which makes a few mistakes catastrophic. `rm` deletes immediately with no recycle bin; `rm -r dir` deletes a directory and everything under it; `rm -rf dir` adds "force", suppressing all prompts and errors. The infamous `rm -rf /` (or worse, `rm -rf $VAR/` where VAR is accidentally empty, expanding to `rm -rf /`) can erase a system - always double-check a variable is set before using it in a destructive command. `mv` and `cp` silently OVERWRITE the destination if it exists; `mv important.txt existing.txt` destroys existing.txt without a word. Use `-i` (interactive) to force a prompt: `rm -i`, `cp -i`, `mv -i`. A wildcard mistake is especially dangerous: `rm *` in the wrong directory, or `rm * .txt` with an accidental space (which means "remove everything AND a file named .txt"), deletes far more than intended because the SHELL expands the wildcard before rm ever sees it. The discipline: pause before any rm with a wildcard or a variable, and consider running the same pattern with `ls` first to preview exactly what will match."""},
            {"h": "PROFESSIONAL PRACTICE: NAVIGATION AS MUSCLE MEMORY", "body": r"""Experienced users treat the shell as a fast cockpit. They lean on Tab completion for every path, use `cd -` to bounce between two working directories, and pipe `ls` into other tools rather than eyeballing long listings (`ls | wc -l` to count entries, `ls -lt | head` to see the five most-recent files). They know `find` for locating files by criteria when they do not know the path (`find . -name '*.log'`), and they use pushd/popd to maintain a stack of directories for deep navigation. Absolute paths go in scripts (predictable regardless of where the script runs); relative paths and Tab completion go in interactive use. On a pentest or an incident, the first minutes on a new box are pure navigation - `pwd`, `ls -la` in home and /tmp, checking /etc for config, reading /proc for running processes - so this apparently basic skill is exactly what you do most under pressure. The goal is that finding and moving files never breaks your train of thought; the commands should be as automatic as walking."""},
            {"h": "WHERE THIS GOES: FILES ARE THE INTERFACE TO EVERYTHING", "body": r"""Because Linux exposes so much as files, mastering navigation unlocks far more than file management. The next lessons build directly on it: pipes and redirection send the OUTPUT of commands into files and other commands; permissions govern which files you may read, write, or execute; processes are inspected through the /proc filesystem you now know how to browse; scripts are just files you make executable. Text-processing tools operate on file contents. SSH and networking move files between machines. The single tree, the current-directory model, and the small composable commands are the substrate all of it runs on. Carry forward two reflexes above all: use `ls -la` as your first move in any unfamiliar directory to see everything including hidden files and permissions, and treat every destructive command (rm, and overwriting mv/cp) as a moment to slow down, because Unix will do exactly what you said, instantly and without a safety net."""},
        ],
    },
    "lx-2": {
        "title_check": "Pipes, grep & redirection",
        "sections": [
            {"h": "MENTAL MODEL: SMALL TOOLS CONNECTED BY STREAMS", "body": r"""The Unix philosophy is that each program does one thing well and reads/writes plain text, so you build power by CONNECTING small tools rather than using one big one. Every process starts with three open streams: standard input (stdin, fd 0), standard output (stdout, fd 1), and standard error (stderr, fd 2). By default stdin is your keyboard and stdout/stderr are your terminal. A pipe, written `|`, connects one command's stdout directly to the next command's stdin, so `ls | grep log` feeds the file listing into grep, which prints only matching lines. Data flows left to right through the pipeline as a stream - the second command can start processing the first's output before the first even finishes. This is genuinely different from running commands separately: no temporary file exists, the connection is a kernel buffer in memory. The mental shift is to stop thinking "which program does X?" and start thinking "which sequence of small transformations produces X?" - filter with grep, rearrange with sort, count with wc, extract columns with cut. A long pipeline is a sentence, each command a verb transforming the stream flowing through it."""},
            {"h": "MECHANISM: REDIRECTION AND THE 2>&1 ORDER TRAP", "body": r"""Redirection points a stream at a file instead of the terminal. `cmd > out.txt` sends stdout to out.txt, OVERWRITING it; `cmd >> out.txt` APPENDS instead. `cmd < in.txt` feeds in.txt as stdin. Crucially, stdout and stderr are SEPARATE streams: `>` only redirects stdout, so error messages still appear on your terminal. To redirect errors, use the stream number: `cmd 2> errors.txt`. To combine both into one file, you write `cmd > out.txt 2>&1`, and the ORDER matters in a way that trips up everyone. `2>&1` means "make fd 2 point wherever fd 1 currently points". So `cmd > out.txt 2>&1` first sends stdout to the file, THEN points stderr at the same file - both land in out.txt. But `cmd 2>&1 > out.txt` points stderr at wherever stdout goes NOW (the terminal), and only afterward moves stdout to the file - so errors still hit the terminal and only normal output reaches the file. They look symmetric but behave completely differently. The modern shorthand `cmd &> out.txt` redirects both unambiguously. `/dev/null` is the black hole: `cmd 2>/dev/null` discards errors entirely."""},
            {"h": "WORKED EXAMPLE: FINDING SOMETHING IN A PILE OF LOGS", "body": r"""A realistic investigation - find every failed SSH login and count them per source IP:
    grep "Failed password" /var/log/auth.log \
      | grep -oE "from [0-9.]+" \
      | awk '{print $2}' \
      | sort \
      | uniq -c \
      | sort -rn \
      | head
Read it as a pipeline of transformations. grep pulls only the failure lines. `grep -oE` with -o prints only the matched part (not the whole line) and -E enables extended regex, isolating "from 1.2.3.4". awk grabs the second field (the IP). sort groups identical IPs together (uniq only collapses ADJACENT duplicates, so you must sort first - a classic gotcha). `uniq -c` prefixes each unique line with its count. `sort -rn` sorts numerically (-n) in reverse (-r) so the worst offender is on top. `head` shows the top few. Each stage is trivial; the combination is a real security tool. This compositional style - and the sort-before-uniq requirement - is the heart of shell text processing."""},
            {"h": "MECHANISM: grep, THE WORKHORSE, AND ITS FLAGS", "body": r"""grep searches input for lines matching a pattern and is probably the tool you will use most. Core flags: `-i` case-insensitive; `-r` recursive through a directory tree; `-n` show line numbers; `-v` INVERT, printing lines that do NOT match (invaluable for filtering out noise); `-c` count matches instead of printing them; `-o` print only the matched text, not the whole line; `-E` extended regex (enables +, ?, |, () without backslashes); `-w` match whole words only; `-l` list only the filenames that contain a match. Combine freely: `grep -rin "todo" src/` finds every case-insensitive "todo" under src/ with line numbers. `grep -v "^#"` strips comment lines from a config file (^ anchors to line start). The pattern is a regular expression by default, so characters like . * [ ] ^ $ have special meaning - `grep "error."` matches "error" plus any character, while `grep -F "error."` (fixed strings) matches the literal dot. Knowing grep deeply pays off daily because it is the universal filter in nearly every pipeline you will write."""},
            {"h": "FAILURE MODES: UNSORTED uniq, GREEDY GLOBS, LOST STDERR", "body": r"""Three pipeline bugs are near-universal. First, `uniq` without a preceding `sort`: uniq only removes CONSECUTIVE duplicate lines, so unsorted input yields duplicate "unique" entries scattered through the output; always `sort | uniq` (or use `sort -u`). Second, confusing shell globs with grep regex: the shell expands `*` before the command runs, so `grep *.log` may not do what you expect if the glob matches files - quote your pattern (`grep "pattern" *.log`) so grep receives the pattern literally while the shell still expands the file list. Third, forgetting that `>` misses stderr, so `cmd > out.txt` silently drops error messages and you wonder why the file is empty when the command "printed" an error - the error went to the terminal, not the file; use `2>&1` in the correct position or `&>`. A fourth subtle one: redirecting a file into itself, `sort file > file`, truncates the file to empty BEFORE sort reads it, destroying your data - use a temp file or `sort -o file file`. These are silent logic errors, not crashes, which is exactly why they are worth memorizing."""},
            {"h": "WHERE THIS GOES: PIPELINES ARE THE UNIX SUPERPOWER", "body": r"""Pipes and redirection are the mechanism that makes the entire "small sharp tools" philosophy work, and everything ahead composes through them. The next lesson's text processors - cut, sort, sed, awk - are pipeline stages you have already started using. Bash scripts capture pipelines into reusable files. Process inspection (`ps aux | grep`) and network reconnaissance (`netstat | grep LISTEN`) are pipelines. For security work specifically, log analysis is almost entirely grep/sort/uniq/awk pipelines like the SSH example above, and the ability to compose a novel filter on the spot - to answer a question no single tool anticipated - is precisely what separates someone who can drive a Linux box from someone who merely knows commands. Internalize the stream model (stdin/stdout/stderr as fds), the 2>&1 ordering rule, and the sort-before-uniq requirement, and you can build arbitrarily sophisticated data processing from a handful of tiny programs connected by vertical bars."""},
        ],
    },
    "lx-3": {
        "title_check": "Permissions & processes",
        "sections": [
            {"h": "MENTAL MODEL: OWNERSHIP AND THE THREE CLASSES", "body": r"""Every file has an owner (a user) and a group, and its permissions are defined for three CLASSES of people: the owner (u), the group (g), and everyone else (o, "others"). For each class there are three permissions: read (r), write (w), and execute (x). `ls -l` shows them as a ten-character string like `-rwxr-xr--`: the first character is the file type (- regular, d directory, l symlink), then three triplets for owner/group/other. So `-rwxr-xr--` means the owner can read/write/execute, the group can read/execute, others can only read. This model is deliberately simple and coarse, which is both its strength (easy to reason about) and its limit (fine-grained control needs ACLs or other mechanisms). For DIRECTORIES the meanings shift subtly: read lets you list the names inside, write lets you create/delete entries within it, and execute lets you ENTER it (cd into it) and access files by name - so a directory you can read but not execute shows you names but denies access to the files, a genuinely confusing situation until you know the rule. Ownership plus these nine bits is the whole classic permission system."""},
            {"h": "MECHANISM: chmod IN SYMBOLIC AND OCTAL FORM", "body": r"""`chmod` changes permissions two ways. Symbolic form names who and what: `chmod u+x script.sh` adds execute for the owner; `chmod go-w file` removes write from group and others; `chmod a+r file` grants read to all (a = all three classes). Octal form encodes all nine bits as three digits, where r=4, w=2, x=1, summed per class: `chmod 755 script.sh` means owner 7 (4+2+1 = rwx), group 5 (4+1 = r-x), others 5 (r-x) - the classic setting for an executable everyone may run but only the owner may modify. `644` (rw-r--r--) is the standard for a normal file: owner reads/writes, everyone else reads. `600` (rw-------) is private: only the owner, used for SSH keys and secrets. `chmod -R` applies recursively to a tree, but be careful - blindly `chmod -R 755` on a directory of mixed files may make data files executable. `chown user:group file` changes ownership (usually needs root). Making a script runnable is the everyday case: `chmod +x deploy.sh`, then `./deploy.sh`. Without the execute bit, the file exists but the kernel refuses to run it."""},
            {"h": "WORKED EXAMPLE: LOCKING DOWN AN SSH KEY AND A SCRIPT", "body": r"""Two common real tasks. First, SSH refuses to use a private key that others can read - a deliberate safety check:
    ls -l ~/.ssh/id_ed25519          # suppose it shows -rw-r--r-- (644, too open)
    chmod 600 ~/.ssh/id_ed25519      # now -rw------- : only you can read it
    ssh -i ~/.ssh/id_ed25519 host    # SSH is satisfied
If you skip the chmod, ssh prints "UNPROTECTED PRIVATE KEY FILE" and refuses - a security feature, not a bug. Second, writing and running a script:
    echo '#!/bin/bash'  >  hello.sh
    echo 'echo hi'      >> hello.sh
    ./hello.sh                       # Permission denied - no execute bit yet
    chmod +x hello.sh
    ./hello.sh                       # now it runs and prints hi
The `#!/bin/bash` first line (the shebang) tells the kernel which interpreter to use, but it only takes effect once the file is executable and you invoke it as a program. Alternatively `bash hello.sh` runs it without the execute bit because you are launching bash explicitly and handing it the file as input."""},
            {"h": "MECHANISM: PROCESSES, ps, AND SIGNALS", "body": r"""A process is a running program with its own memory, a numeric PID, an owner, and a parent. `ps aux` lists every process with owner, PID, CPU and memory use, and the command line - `ps aux | grep firefox` finds a specific one. `top` (or the friendlier `htop`) shows them live, sorted by resource use. Each process has a parent (the one that launched it), forming a tree rooted at PID 1 (init/systemd). You control processes with SIGNALS sent by `kill`: `kill PID` sends SIGTERM (15), a polite "please shut down" the program can catch to clean up; `kill -9 PID` sends SIGKILL, an uncatchable "die now" the kernel enforces immediately, used only when SIGTERM is ignored because it gives the process no chance to save or clean up. `kill -STOP`/`-CONT` pause and resume. `pkill firefox` kills by name. In the foreground, Ctrl-C sends SIGINT (interrupt) and Ctrl-Z sends SIGTSTP (suspend, leaving the job stopped - resume it with `fg` or background it with `bg`). Appending `&` to a command runs it in the background from the start. Understanding signals as the OS's inter-process messaging is what lets you manage runaway or stuck programs deliberately rather than by guesswork."""},
            {"h": "FAILURE MODES: OVER-PERMISSIVE FILES AND SIGKILL ABUSE", "body": r"""Permission and process mistakes have real consequences. Making files world-writable (`chmod 777`, a lazy "fix" for permission errors) is a genuine security hole - any user or compromised process can modify them, and 777 on a script anyone can also edit means anyone can make it do anything; the correct fix is almost always to adjust OWNERSHIP or use a narrower mode, not to open it to everyone. Recursively chmod-ing a tree to 644 strips execute from directories, which then cannot be entered (remember: x on a directory means "enter"), locking you out of your own files. On the process side, reaching for `kill -9` first is a bad habit: SIGKILL gives the program no chance to flush buffers, close files cleanly, or release locks, which can corrupt data or leave stale lock files - always try plain `kill` (SIGTERM) first and escalate to -9 only if it truly ignores you. Killing the wrong PID because you misread `ps` output, or killing a parent and orphaning its children, are common under pressure. And running something in the background with `&` then closing the terminal may kill it (SIGHUP) unless you used nohup or a terminal multiplexer - a surprise when a long job dies on logout."""},
            {"h": "WHERE THIS GOES: PERMISSIONS AND PROCESSES ARE THE SECURITY MODEL", "body": r"""This lesson is where Linux administration and security truly begin. Permissions are the OS's primary access-control mechanism, so understanding them is prerequisite to hardening a system, to spotting a misconfiguration (a world-writable sensitive file, a private key with loose permissions), and to privilege-escalation analysis in security work - much of local attack and defense revolves around which files a process can write and which it can execute. Processes and signals underpin service management, debugging (attaching a debugger, sending signals to reproduce behavior), and incident response (identifying and stopping a malicious process). The concepts feed directly forward: scripts you write will set permissions and manage background processes; SSH depends on strict key permissions; system services are processes controlled by signals. Carry forward the octal mental model (rwx = 4/2/1), the special meaning of x on directories, the 600-for-secrets convention, and the SIGTERM-before-SIGKILL discipline - together they are the everyday language of running and securing a Linux machine."""},
        ],
    },
    "lx-4": {
        "title_check": "Your first bash script",
        "sections": [
            {"h": "MENTAL MODEL: A SCRIPT IS A SAVED SEQUENCE OF SHELL COMMANDS", "body": r"""A bash script is nothing more exotic than the commands you would type, saved in a file and run in order. That is the whole idea, and it is why shell scripting is so immediately useful: anything you can do interactively, you can automate by pasting it into a file. The file starts with a SHEBANG line, `#!/bin/bash`, which tells the kernel "run this file with /bin/bash". You make it executable with `chmod +x script.sh` and run it as `./script.sh`, or run it without the execute bit via `bash script.sh`. Inside, each line is a command; lines starting with `#` (after the shebang) are comments. The shell reads top to bottom, running each command and moving on. Variables, conditionals, and loops add logic, but the core remains: a script is a recipe of ordinary commands. This is different from a compiled program - there is no build step, the shell interprets the text directly each time, which makes scripts fast to write and modify but means errors surface at runtime, line by line, as the shell reaches them. The mental model to hold is "I am teaching the shell a sequence I would otherwise type", and everything else is refinement."""},
            {"h": "MECHANISM: VARIABLES, QUOTING, AND COMMAND SUBSTITUTION", "body": r"""Assign a variable with NO spaces around the equals sign: `name=world` (writing `name = world` fails, because the shell reads it as running the command `name` with arguments). Read it back with a `$`: `echo "$name"`. The quoting rules are the heart of correct scripting. Double quotes allow variable expansion but keep the value as one word: `echo "$name"` prints the value, and `"$file"` protects a filename containing spaces from being split into multiple arguments. Single quotes are literal - `echo '$name'` prints the text $name, expanding nothing. Leaving a variable UNQUOTED is the classic bug: if `file="my document.txt"` then `rm $file` becomes `rm my document.txt` (two arguments!), while `rm "$file"` is correct. Command substitution captures a command's output into a value: `today=$(date +%F)` runs date and stores its output; the modern `$(...)` form nests cleanly, unlike the old backtick form. Arithmetic uses `$(( ))`: `count=$((count + 1))`. Special variables carry context: `$1 $2` are the script's arguments, `$#` the argument count, `$0` the script name, `$?` the exit status of the last command, `$@` all arguments. Mastering quoting alone eliminates most script bugs."""},
            {"h": "WORKED EXAMPLE: A BACKUP SCRIPT WITH ARGUMENTS AND CHECKS", "body": r"""A small but real script that backs up a directory given as an argument:
    #!/bin/bash
    set -euo pipefail                 # safety: see the failure-modes section

    src="$1"                          # first argument
    if [ -z "$src" ]; then            # -z: is the string empty?
        echo "usage: $0 <dir>" >&2    # error to stderr
        exit 1                        # nonzero exit = failure
    fi
    if [ ! -d "$src" ]; then          # ! -d: NOT a directory
        echo "no such directory: $src" >&2
        exit 1
    fi
    stamp=$(date +%Y%m%d-%H%M%S)      # command substitution
    dest="backup-$stamp.tar.gz"
    tar -czf "$dest" "$src"           # quotes protect names with spaces
    echo "backed up $src -> $dest"
Trace it: it reads the target directory from $1, validates that the argument exists and is really a directory (failing early with a message to stderr and a nonzero exit), builds a timestamped filename via command substitution, and creates the archive. Every variable is quoted, so a path with spaces works. The `>&2` sends usage/errors to stderr where they belong, keeping stdout clean for real output."""},
            {"h": "MECHANISM: CONDITIONALS, LOOPS, AND TESTS", "body": r"""Bash logic centers on the `test` command, usually written as `[ ... ]`. String tests: `[ -z "$s" ]` true if empty, `[ -n "$s" ]` true if non-empty, `[ "$a" = "$b" ]` string equality. File tests: `[ -f path ]` is a regular file, `[ -d path ]` is a directory, `[ -e path ]` exists, `[ -x path ]` is executable. Numeric comparisons use word operators: `[ "$n" -gt 5 ]`, -lt, -eq, -ge, -le (using `>` there would be redirection, a real trap). The structure is `if [ test ]; then ... elif [ test ]; then ... else ... fi`. Loops: `for f in *.txt; do echo "$f"; done` iterates over glob matches; `for i in $(seq 1 5)` counts; `while [ condition ]; do ...; done` repeats until false; `while read -r line; do ...; done < file` reads a file line by line (the `-r` prevents backslash mangling). The exit status drives everything - a command that succeeds returns 0, and `if cmd; then` runs the branch when cmd succeeded, so you can test commands directly: `if grep -q pattern file; then` acts on whether the pattern was found. Understanding that `[` is really a command, and that spaces around it and its operators are mandatory, prevents the most frustrating syntax errors."""},
            {"h": "FAILURE MODES: UNQUOTED VARS, [ SPACING, AND SILENT ERRORS", "body": r"""Scripting bugs cluster in a few spots. Unquoted variables cause word-splitting and glob expansion disasters: `for f in $files` breaks on spaces, and `rm $x` with an empty x can expand to `rm` with surprising results - always quote (`"$f"`, `"$x"`). Missing spaces inside `[ ]` are fatal: `[ "$a"="$b" ]` (no spaces around =) is always TRUE because it is testing a single non-empty string, not comparing two - the spaces are required. Using `=` for numbers or `>` for comparison instead of `-eq`/`-gt` either compares as strings ("10" < "9" lexically!) or performs redirection. The biggest silent killer is a script that plows on after a command fails, because by default bash ignores errors and continues to the next line - so a failed `cd` followed by `rm -rf *` runs the rm in the WRONG directory. The remedy is the safety header `set -euo pipefail`: -e exits on any command failure, -u errors on unset variables (catching typos), and pipefail makes a pipeline fail if any stage fails. Add it to the top of every script and a whole category of dangerous, silent bugs simply cannot happen."""},
            {"h": "WHERE THIS GOES: AUTOMATION IS LEVERAGE", "body": r"""Scripting is where the shell stops being a place you type commands and becomes a place you BUILD tools. Everything prior feeds in: scripts run pipelines, set permissions, manage processes, and process text. Everything ahead is scriptable: the text-processing tools of the next lesson become powerful when wrapped in loops over many files; SSH commands get automated across fleets of machines; scheduled tasks (cron) run your scripts unattended. For security work, scripting is constant - automating reconnaissance, parsing tool output, chaining exploits in a lab, building small utilities on a target box where you cannot install software. The compounding value is real: a five-minute script that saves ten minutes a day pays for itself in a week and forever after. Carry forward the non-negotiables - quote every variable, put spaces around `[` and its operators, use the numeric comparison words, and start every script with `set -euo pipefail` - and your scripts will be both correct and safe, which in a shell with no undo is exactly what matters."""},
        ],
    },
    "lx-5": {
        "title_check": "Text processing: sort, uniq, cut, sed, awk",
        "sections": [
            {"h": "MENTAL MODEL: LINE-ORIENTED TOOLS ON STREAMS OF TEXT", "body": r"""Unix text tools share a worldview: input is a stream of LINES, and most tools process one line at a time, often splitting each line into FIELDS separated by whitespace or a chosen delimiter. This is why log files, CSVs, and command output - all line-and-field shaped - are so easy to manipulate. Each tool has a specialty. `sort` reorders lines. `uniq` collapses adjacent duplicates. `cut` extracts specific columns. `sed` does line-based find-and-replace and editing. `awk` is a small programming language for field-oriented processing. You compose them in pipelines, each transforming the stream. The key insight is to match the tool to the job rather than reaching for one Swiss-army tool: grep to FILTER lines, cut or awk to EXTRACT columns, sort to ORDER, uniq to COUNT, sed to SUBSTITUTE. Knowing which tool owns which verb lets you assemble a solution quickly. And because they all read stdin and write stdout, any of them slots into any pipeline. The recurring theme across this track returns here in its purest form: small tools, each doing one transformation, connected into a sentence that answers a question no single program was built to answer."""},
            {"h": "MECHANISM: sort, uniq, AND cut", "body": r"""`sort` orders lines lexically by default; `-n` sorts numerically (so 10 comes after 9, not before it as text sorting would do), `-r` reverses, `-k2` sorts by the second field, `-t,` sets the delimiter to comma, and `-u` removes duplicates in one step. `sort -t, -k3 -n file.csv` sorts a CSV numerically by its third column. `uniq` only collapses ADJACENT identical lines, so it is almost always preceded by sort; `uniq -c` prefixes each line with its occurrence count (the counting idiom), `uniq -d` shows only duplicated lines, `uniq -u` only unique ones. The `sort | uniq -c | sort -rn` pattern - sort to group, count, then sort by count descending - is the canonical "what are the most frequent values?" pipeline. `cut` extracts columns: `cut -d, -f1,3` takes fields 1 and 3 from comma-delimited input; `cut -c1-10` takes characters 1 through 10 by position; the default delimiter is TAB, which surprises people feeding it space-separated data (use awk for whitespace-delimited fields, since cut cannot treat runs of spaces as one separator). These three tools handle the ordering, counting, and column-extraction that most log analysis needs."""},
            {"h": "MECHANISM: sed FOR SUBSTITUTION AND EDITING", "body": r"""`sed` (stream editor) transforms text as it flows past, most often for search-and-replace. The core command is `s/pattern/replacement/`: `sed 's/foo/bar/' file` replaces the FIRST "foo" on each line with "bar"; adding the `g` flag, `s/foo/bar/g`, replaces ALL occurrences on each line. By default sed writes to stdout, leaving the file unchanged - use `-i` to edit the file IN PLACE (`sed -i 's/foo/bar/g' file`), which is powerful and dangerous because there is no undo, so test without -i first. The pattern is a regular expression, so `sed 's/[0-9]\+/N/g'` replaces every run of digits with N (basic regex needs `\+`; `sed -E` enables extended regex with plain `+`). You can choose a different delimiter when the pattern contains slashes, e.g. paths: `sed 's#/usr/local#/opt#g'` avoids escaping every slash. Beyond substitution, `sed -n '5,10p'` prints only lines 5 to 10 (-n suppresses default printing, p explicitly prints), and `sed '/pattern/d'` deletes matching lines. sed shines for mechanical edits across many lines or files - renaming a variable throughout a codebase, rewriting config values, stripping unwanted characters - the kind of repetitive editing that would be error-prone by hand."""},
            {"h": "MECHANISM: awk FOR FIELD-AWARE PROCESSING", "body": r"""`awk` is the most powerful of these tools - a compact language built for columnar data. Its model is "for each line, split into fields $1, $2, ... ($0 is the whole line), and run my program". The simplest use extracts a column: `awk '{print $2}'` prints the second whitespace-separated field of every line - and unlike cut, awk treats any run of whitespace as one separator, which is why it handles command output better. Add conditions: `awk '$3 > 100 {print $1}'` prints field 1 only for lines where field 3 exceeds 100 - filtering and extraction together. Change the delimiter with -F: `awk -F, '{print $1}'` for CSV. awk can accumulate: `awk '{sum += $1} END {print sum}'` totals the first column, using a variable that persists across lines and an END block that runs after the last line (there is a matching BEGIN block for setup). `awk -F: '{print $1}' /etc/passwd` lists usernames from the colon-delimited password file. Because awk combines field-splitting, conditions, arithmetic, and variables in one tool, a single awk invocation often replaces a chain of cut/grep/wc - it is the go-to when you need to compute across columns rather than just filter or reorder."""},
            {"h": "WORKED EXAMPLE AND FAILURE MODES TOGETHER", "body": r"""Combine them to answer "which users have the most processes?":
    ps -eo user | tail -n +2 | sort | uniq -c | sort -rn | head
`ps -eo user` prints just the user column; `tail -n +2` skips the header line; sort groups, uniq -c counts, sort -rn ranks, head trims. Now the failure modes. The dominant one recurs: `uniq` without `sort` first, giving wrong counts because uniq only sees adjacent duplicates. Second, `sort` without `-n` on numbers sorts them as text, so 100 sorts before 9 - always -n for numeric data. Third, `cut -f` on space-separated data silently fails or misbehaves because cut defaults to TAB and cannot collapse multiple spaces; reach for awk when fields are whitespace-separated. Fourth, `sed -i` with a bad pattern destroys a file irreversibly - preview without -i, or keep a backup (`sed -i.bak` writes a .bak copy on GNU sed). Fifth, forgetting that basic sed regex needs `\+`, `\?`, `\(` escaped while `sed -E` (extended) does not, leading to patterns that silently do not match. Each is a silent wrong-output bug, not a crash, so the habit of eyeballing intermediate pipeline output (build it stage by stage) is the real defense."""},
            {"h": "WHERE THIS GOES: TEXT PROCESSING IS DATA ANALYSIS ON THE SHELL", "body": r"""These five tools turn the shell into a capable data-analysis environment for anything line-and-field shaped, which in the Unix world is nearly everything: logs, config files, CSV exports, and the output of every other command. The skills compound with the rest of the track - pipelines connect them, scripts wrap them into reusable analyzers, and loops apply them across many files. For security and systems work this is daily bread: parsing authentication logs for intrusion patterns, extracting indicators from tool output, summarizing scan results, transforming data between formats, and triaging incidents where the evidence is megabytes of text. A practitioner who can fluently compose sort/uniq/cut/sed/awk answers questions in seconds that would otherwise need a custom program. Carry forward the tool-to-verb mapping (filter=grep, extract=cut/awk, order=sort, count=uniq -c, substitute=sed), the sort-before-uniq and -n-for-numbers rules, and the caution around sed -i, and you have a text-processing toolkit that will serve you for a lifetime of working with data on the command line."""},
        ],
    },
    "lx-6": {
        "title_check": "SSH, networking & packages",
        "sections": [
            {"h": "MENTAL MODEL: SSH IS AN ENCRYPTED SHELL ON ANOTHER MACHINE", "body": r"""SSH (Secure Shell) gives you an encrypted terminal session on a remote computer, as if you were typing at its keyboard. `ssh user@host` opens a login shell on host as user, encrypting everything so no one on the network can read your commands or the machine's responses. This is the backbone of remote administration - servers usually have no monitor, and SSH is how you reach them. Beyond an interactive shell, SSH can run a single command and return (`ssh user@host 'uptime'`), which is what makes it scriptable across many machines. It also carries other traffic: `scp` and `rsync` copy files over the same encrypted channel, and port forwarding tunnels arbitrary connections through it. The trust model is built on cryptographic keys, not just passwords: the FIRST time you connect, SSH shows the server's host key fingerprint and asks you to confirm, then remembers it in ~/.ssh/known_hosts - so a later warning that the host key CHANGED is a genuine security alert (a possible man-in-the-middle, or a legitimately rebuilt server). Understanding SSH as "a secure, scriptable pipe to a shell elsewhere" frames everything it does, from a quick login to automated deployment across a fleet."""},
            {"h": "MECHANISM: KEY-BASED AUTHENTICATION", "body": r"""Password logins are weak and tedious; SSH keys are the standard. You generate a key PAIR with `ssh-keygen -t ed25519`: a PRIVATE key (~/.ssh/id_ed25519, kept secret, never shared) and a PUBLIC key (id_ed25519.pub, safe to distribute). The math is asymmetric: the public key can verify a signature that only the matching private key could produce, so the server stores your public key and challenges you to prove you hold the private one, without the private key ever crossing the network. You install your public key on a server with `ssh-copy-id user@host`, which appends it to the server's ~/.ssh/authorized_keys. After that, `ssh user@host` logs in with no password. Permissions are strictly enforced: the private key must be mode 600 (readable only by you) and ~/.ssh must be 700, or SSH refuses to use them - a safety check, since a key others can read is a key others can steal. An ssh-agent can hold your decrypted key in memory so you type its passphrase once per session. Key auth is both more secure (no password to brute-force or phish) and more convenient (no typing), and it is what makes automated, scripted SSH across many hosts practical."""},
            {"h": "MECHANISM: NETWORK INSPECTION FROM THE SHELL", "body": r"""A handful of tools reveal a machine's networking. `ip addr` (the modern replacement for ifconfig) shows your interfaces and their IP addresses; `ip route` shows the routing table (where packets go, including the default gateway). `ping host` tests basic reachability by sending ICMP echoes. `ss -tulpn` (the modern replacement for netstat) lists listening sockets: -t TCP, -u UDP, -l listening only, -p the owning process, -n numeric ports - so `ss -tulpn` answers "what services are listening on this box and which programs are they?", a first-move on any machine. `curl` fetches URLs from the command line (`curl -I https://site` for just headers, `curl -s` silent); `wget` downloads files. `dig name` or `nslookup name` resolves DNS. `nc` (netcat) opens raw TCP/UDP connections for testing a port. For diagnosing "why can't I reach X?", the ladder is: is the interface up and addressed (ip addr), is there a route (ip route), does the name resolve (dig), does the host respond (ping), is the port open and listening (ss on the server, nc from the client). Each tool isolates one layer, and running them in order localizes the failure precisely."""},
            {"h": "MECHANISM: PACKAGE MANAGERS INSTALL AND UPDATE SOFTWARE", "body": r"""Linux installs software through package managers that resolve dependencies and pull from curated repositories, rather than downloading random installers. The manager depends on the distribution family. Debian/Ubuntu use apt: `sudo apt update` refreshes the package index (do this first), `sudo apt install nmap` installs, `sudo apt upgrade` updates everything, `apt search term` finds packages, `apt remove pkg` uninstalls. Red Hat/Fedora use dnf (formerly yum) with parallel commands: `sudo dnf install`, `sudo dnf update`. Arch uses pacman (`sudo pacman -S pkg`). Your MSYS2 environment uses pacman too (`pacman -S mingw-w64-ucrt-x86_64-gcc` is how gcc and nasm got there). The manager tracks what is installed, handles dependencies automatically (installing a tool pulls in the libraries it needs), and updates everything from trusted signed repositories - which is a security property, since packages are cryptographically verified. `sudo` runs a single command as root (the administrator), required for system-wide installs because they modify protected directories; it prompts for YOUR password and logs the action, a safer model than logging in as root directly. Knowing your distro's manager is essential because it is how every tool, from a text editor to a security scanner, gets onto the machine."""},
            {"h": "FAILURE MODES: HOST-KEY WARNINGS, LOOSE KEYS, sudo MISTAKES", "body": r"""Several remote-work pitfalls deserve care. A "REMOTE HOST IDENTIFICATION HAS CHANGED" warning is not noise to click through - it means the server's host key differs from what you recorded, which is either a legitimately rebuilt server or a genuine man-in-the-middle attack; verify out-of-band before removing the old known_hosts entry. A private key with permissions looser than 600 makes SSH refuse it (and rightly - it is exposed); never `chmod 777` a key to "fix" an error. Committing a private key to a git repository or copying it to a shared location leaks it permanently - private keys never leave the machine they were generated on. On packages, forgetting `apt update` before `apt install` can install a stale version or fail to find a package that exists, because the local index is outdated. Running the wrong thing under sudo is dangerous precisely because sudo removes the guardrails - `sudo rm -rf` ignores ownership protections, and piping a script straight from the internet into `sudo bash` runs unreviewed code as root. The disciplines: treat host-key changes as security events, keep private keys at 600 and never share them, refresh the package index before installing, and read anything before running it as root."""},
            {"h": "WHERE THIS GOES: THE SHELL REACHES BEYOND ONE MACHINE", "body": r"""This lesson extends everything you have learned from a single computer to networks of them, which is where real systems live. SSH turns your local shell skills into remote administration; combined with scripting, it automates tasks across many servers at once, the foundation of configuration management and deployment. Network tools are the diagnostic layer for distributed systems and a core part of security reconnaissance - enumerating what a host exposes, testing connectivity, and understanding a network's shape are early steps in both defense and authorized testing. Package managers are how you provision a machine with the tools to do any of it. For a security career specifically, SSH key hygiene, the ability to inspect listening services with ss, DNS and connectivity troubleshooting, and safe use of sudo are daily fundamentals. The track has taken you from moving files in one directory to operating, scripting, analyzing, and now networking a Linux system - a complete working competence. Carry forward the security-minded reflexes especially: key permissions, host-key verification, index-before-install, and read-before-root, because on real systems those habits are what separate a safe operator from a liability."""},
        ],
    },
}
