# depth_csharp.py — extended teaching content for the csharp track.
# Auto-attached by depth.py. One entry per lesson id.

DEPTH = {

    "cs-1": {
        "title_check": "Java → C# in one sitting",
        "sections": [
            {"h": "MENTAL MODEL: SOURCE TO IL TO JIT - THE SAME SHAPE AS javac TO JVM BYTECODE", "body": r"""C#'s build pipeline has almost the exact same shape as the one you already know from Java, with different names for each stage. javac compiles .java source to .class files containing JVM bytecode, which the JVM's JIT compiler turns into native machine code as the program runs; csc (invoked for you by dotnet build) compiles .cs source into an assembly (a .dll or .exe) containing CIL, Common Intermediate Language, sometimes just called IL, and the CLR's JIT compiler turns that into native machine code as the program runs, method by method, the first time each one is actually called. Both are managed runtimes with garbage collection, both ship a large standard library alongside the runtime (java.lang/java.util versus System/System.Collections.Generic), and both let you inspect the intermediate form directly - javap for JVM bytecode, ildasm or dotnet's own tooling for CIL - if you ever want to see exactly what your source compiled into. The practical upshot: almost every mental habit you have from write Java, run on the JVM transfers directly to write C#, run on the CLR, which is exactly why this lesson can spend its time on the genuine deltas rather than re-teaching what a managed, garbage-collected, JIT-compiled language even is."""},

            {"h": "MECHANISM: WHAT AN AUTO-PROPERTY ACTUALLY COMPILES TO", "body": r"""public string Name { get; set; } is not a special language feature that skips normal method dispatch - the compiler expands it, before your code is even turned into IL, into a private backing field with a compiler-generated name, plus two ordinary methods: get_Name() returning the field, and set_Name(value) assigning it. Calling p.Name = "Dan" compiles to a call to set_Name("Dan"); reading p.Name compiles to a call to get_Name() - at the IL level there is no such thing as property access, only these two method calls, exactly the getX()/setX() pattern you already write by hand in Java, just generated for you. This matters practically the moment you need validation logic: you cannot add a body to an auto-property's accessors, so the moment Name needs to reject an empty string, you write out the backing field explicitly (private string name;) and give get and set real bodies, at which point the syntax looks almost identical to a Java getter/setter pair, because underneath it always was one. Interfaces can declare properties too (string Name { get; set; };), which compiles to declaring the get_Name/set_Name method signatures in the interface - again no new mechanism, just the same expansion applied one level up."""},

            {"h": "WORKED EXAMPLE: TRANSLATING A VALIDATING JAVA SETTER INTO A C# PROPERTY", "body": r"""A Java class enforcing an invariant in its setter:

    public class Account {
        private double balance;
        public void setBalance(double b) {
            if (b < 0) throw new IllegalArgumentException("negative balance");
            this.balance = b;
        }
        public double getBalance() { return balance; }
    }

translates to a C# property with an explicit backing field and a real body in the setter, not an auto-property:

    public class Account {
        private double balance;
        public double Balance {
            get => balance;
            set {
                if (value < 0) throw new ArgumentException("negative balance");
                balance = value;
            }
        }
    }

value is an implicit parameter name inside any set accessor, the equivalent of the Java setter's explicit parameter b, and callers still write account.Balance = -5; as ordinary field-like syntax, with the validation running invisibly underneath exactly as it would inside Java's explicit setBalance(-5) call. The behavior is identical; only the calling syntax changed from a method call to what looks like plain field assignment."""},

            {"h": "FAILURE MODES: BOXING, AND == MEANING SOMETHING DIFFERENT THAN IN JAVA", "body": r"""Assigning a value type to a variable of type object - int x = 5; object o = x; - triggers BOXING: the CLR allocates a new object on the heap, copies x's 4 bytes into it, and o now references that heap box; reading it back out, int y = (int)o;, is UNBOXING, and requires the exact runtime type to match or it throws InvalidCastException - unboxing a boxed int as a long fails even though the implicit numeric conversion int-to-long is normally allowed. This bites hardest with the legacy non-generic ArrayList, which stores everything as object: adding a million ints to an ArrayList boxes every single one individually, a real, measurable memory and performance cost that List<int> avoids entirely by storing unboxed ints inline. Second, == behaves differently from Java in a way that surprises transplants in the opposite direction from what they expect: in Java, == on any object reference (never overloadable) always means identity, full stop - Java's String is the one everyone gets burned by, since == on two strings compares references, not content, and .equals() is required for value equality. In C#, == CAN be operator-overloaded per type, and string specifically overloads it to mean VALUE equality directly, so a == b on two C# strings with the same content is true even if they are different objects - the reverse of the Java gotcha, catching developers who defensively write a.Equals(b) out of habit when a == b would have worked fine."""},

            {"h": "HOW A PROFESSIONAL NAMES AND SHAPES A C# CLASS DIFFERENTLY FROM A JAVA ONE", "body": r"""A professional writing idiomatic C# does not simply write Java with semicolons in different places - naming and shape conventions genuinely differ and reviewers notice. Methods and properties are PascalCase (DescribeVehicle(), Balance), not Java's camelCase (describeVehicle(), balance) - this single convention difference is the fastest tell of code translated mechanically rather than written idiomatically. Where a Java class exposes mutable state through a private field plus a getter/setter pair as the default habit, a C# professional defaults to an auto-property unless validation is genuinely needed, and increasingly reaches for record types (public record Point(int X, int Y);) for small, immutable, value-like data - a single line replacing a constructor, properties, ToString, and equality all at once, with no Java equivalent until Java's own records arrived years later. Nullable reference types (enabled per-project, string? meaning this may be null versus string meaning the compiler expects this is never null) are a C#-specific static-analysis layer Java's type system does not have at all, and idiomatic modern C# annotates for it deliberately rather than leaving every reference type ambiguously nullable the way Java always has."""},

            {"h": "WHERE THIS IS GOING: VALUE-TYPE GENERICS AND INTERFACES BOTH BUILD ON THIS", "body": r"""The property mechanism from this lesson, a getter/setter pair the compiler generates or you write by hand, is not an isolated syntax quirk - it is the same idea interfaces rely on (cs-3's material) when they declare a property signature rather than a field, and the same idea that makes auto-implemented properties interact cleanly with inheritance, since a derived class can override a virtual property's get and set independently. Boxing, covered here as a failure mode, is exactly what cs-6's lesson on generics explains how to AVOID - List<int> versus the legacy ArrayList is a direct, concrete before-and-after of boxing on every element versus no boxing at all, and understanding boxing here is the prerequisite for that payoff making sense later rather than being taken on faith. And the == overloading behavior from this lesson resurfaces the moment you write a generic method that needs to compare two values of a type parameter T - without a constraint, C# will not even let you write a == b inside a generic method, precisely because the compiler cannot know in advance whether T's == does identity, value equality, or nothing at all, exactly the kind of concrete detail cs-6 returns to directly."""},
        ],
    },

    "cs-2": {
        "title_check": "Collections & LINQ",
        "sections": [
            {"h": "MENTAL MODEL: A LINQ CHAIN IS A RECIPE, NOT A RESULT", "body": r"""nums.Where(n => n % 2 == 0).OrderBy(n => n).Select(n => n * 10) does not filter, sort, and transform nums the instant that line executes - it builds up a RECIPE, an object describing what would need to happen, without touching a single element yet. Nothing runs until something actually asks for values one at a time: a foreach loop, a call to .ToList() or .ToArray(), or another operator like .First() that only needs the first element and can stop early. This is the same lazy pipeline idea Java 8 Streams use - filter/map/collect map almost one-to-one onto Where/Select/ToList - so if you already think of a Stream as a description of work rather than a result, LINQ asks for the identical mental shift, just with different method names and, crucially, the ability to chain the same Where()/Select() vocabulary over plain in-memory collections, database queries, XML, and more, unified under one interface. The consequence worth internalizing immediately: a LINQ expression sitting in a variable, unenumerated, has done zero work and caught zero bugs in whatever it queries - only pulling values out of it actually runs the recipe."""},

            {"h": "MECHANISM: EACH LINQ OPERATOR WRAPS THE PREVIOUS ITERATOR IN A NEW ONE", "body": r"""Where(predicate) does not loop over its source and build a new list - it returns a new object implementing IEnumerable<T> that holds a reference to the source sequence and the predicate delegate, and only when that object's GetEnumerator().MoveNext() is called does it pull one item from the source, test the predicate, and either yield it or move to the next source item and try again. Chaining .Select(f) on top wraps that Where-iterator in yet another thin iterator that, on each MoveNext(), asks the Where-iterator for its next passing item and then applies f to it - so a three-operator chain is really three small iterator objects nested inside each other, and pulling one final value walks all the way down through all three layers for just that one element before the next MoveNext() call repeats the whole walk for the next element. This is implemented internally almost exactly like yield-based generators - each LINQ operator is, under the hood, a compiler- or library-generated state machine advancing one step per MoveNext(), which is precisely why a LINQ chain over an infinite sequence works fine as long as you only ever pull a bounded number of results from the far end, like Take(5)."""},

            {"h": "WORKED EXAMPLE: IEnumerable VS IQueryable - WHERE THE FILTERING ACTUALLY RUNS", "body": r"""    var inMemory = products.Where(p => p.Price < 50);            // IEnumerable<Product>
    var fromDb    = dbContext.Products.Where(p => p.Price < 50);  // IQueryable<Product>

Both lines look identical, but they compile against different interfaces and behave very differently once enumerated. products.Where(...) over an in-memory List<Product> compiles the lambda into an actual delegate (compiled IL, runs as ordinary C# when invoked) and filters element by element in your process's memory, exactly as described in the previous section. dbContext.Products.Where(...) instead compiles that same-looking lambda into an EXPRESSION TREE, a data structure describing the lambda's logic as data, not executable code, which Entity Framework then translates into an actual SQL WHERE clause and sends to the database; the filtering never happens in your C# process's memory at all, it happens inside the database engine, and only the already-filtered rows are pulled back across the network into objects. Writing p.Price < 50 && ExpensiveLocalHelper(p) inside an IQueryable chain can fail at runtime, or silently not translate, precisely because the database has no idea what your local C# helper method means - a mistake invisible from the syntax alone, since IEnumerable and IQueryable share almost the entire same-looking method surface."""},

            {"h": "FAILURE MODES: MULTIPLE ENUMERATION AND THE LOOP-VARIABLE CAPTURE TRAP", "body": r"""Multiple enumeration is the most common real LINQ bug: var evens = nums.Where(n => n % 2 == 0); if (evens.Any()) { foreach (var e in evens) ... } enumerates the same lazy query twice - once inside Any() (which pulls just enough to find one match, then stops), once inside the foreach (which starts the whole Where-iterator over again from scratch) - harmless for a cheap in-memory filter, but genuinely expensive or even semantically wrong if the source is a database query (two round trips instead of one) or, worse, if the source involves side effects or changes between the two enumerations, producing a different result the second time. Second, capturing a loop variable inside a lambda built across iterations of a for loop repeats a classic trap: for (int i = 0; i < 3; i++) { actions.Add(() => Console.WriteLine(i)); } prints 3, 3, 3 when the actions run later, because all three lambdas share the same captured variable i, and by the time any of them runs, the loop has finished with i at 3 - a foreach (var x in collection) loop does NOT have this problem since C# 5, because each iteration gets its own fresh x, but a plain for loop's counter variable is still one single shared variable across every iteration."""},

            {"h": "HOW A PROFESSIONAL DECIDES WHEN TO MATERIALIZE", "body": r"""A professional decides deliberately, not by accident, whether a LINQ expression should stay lazy or be materialized immediately with .ToList() or .ToArray(). Materialize when a result will be enumerated more than once (fixing the multiple-enumeration bug from the previous section at the source, by paying the cost once and reusing a real, finished collection), when the underlying source might change between now and when you actually need the data, or when you are about to return the result from a method whose caller has no idea it was ever lazy in the first place, which can otherwise leak a live connection or a captured variable in a way the caller cannot see. Conversely, professionals deliberately leave a query un-materialized when composing it further before it runs (adding another Where or OrderBy onto an existing IQueryable so the database still sees, and can optimize, the combined query as one unit) or when only the first few results actually matter - Take(10) after an OrderBy on a huge IQueryable pushes give me only 10 rows down into the SQL itself, which is dramatically cheaper than pulling everything into memory and taking 10 in C#."""},

            {"h": "WHERE THIS IS GOING: THE SAME LAZY-PIPELINE IDEA POWERS ASYNC STREAMS", "body": r"""The lazy, pull-based pipeline you have just learned is not LINQ's private trick - it is the same shape cs-4's async material builds on top of with IAsyncEnumerable<T> and await foreach, where each MoveNextAsync() call can genuinely await an I/O operation between elements, combining do not compute until asked with do not block a thread while waiting in one construct. It is also the same conceptual foundation as generators in other languages: an iterator producing one value per pull, maintaining its own position between calls, is a cross-language idea, not a C#-only feature - only the exact syntax for building one differs. Once you reach IAsyncEnumerable, everything from this lesson still applies unchanged: multiple enumeration is still wasteful (now wasting an await round trip, not just CPU), materializing early is still sometimes the right call, and the mental model of this is a recipe, not a result, until something pulls from the end is exactly the model you will need for streaming data over a real network connection rather than a database."""},
        ],
    },

    "cs-3": {
        "title_check": "Interfaces, abstract classes & destructors",
        "sections": [
            {"h": "MENTAL MODEL: TWO ANSWERS TO GUARANTEE A SHAPE WITHOUT AN IMPLEMENTATION", "body": r"""An abstract class and an interface solve the same surface problem, guarantee callers a method exists without necessarily saying how it works yet, but the CLR dispatches calls through them differently underneath, and the difference explains real design constraints, not just style preference. Every object carries a hidden pointer to a method table for its concrete class, and a virtual or abstract method call (including one declared in an abstract base class) is resolved by indexing into that same class's method table at a fixed slot number, decided once, at compile/load time, for the whole class hierarchy - fast, direct, and why a class can only extend ONE abstract base: there is only one method table, one set of slots, per object. Interface dispatch historically works through a separate mechanism, an interface map associating each interface a class implements with the specific slots in ITS method table that satisfy that interface's methods, which is exactly what allows a single class to implement many unrelated interfaces without any slot-numbering conflict between them, at a historically slightly higher dispatch cost than a plain virtual call, though modern CLR versions have narrowed that gap considerably. The is-a shared base, one slot versus can-do capability, many allowed rule of thumb falls directly out of this structural difference."""},

            {"h": "MECHANISM: THE FULL DISPOSE PATTERN, NOT JUST using", "body": r"""Cleaning up a class that wraps a genuinely scarce resource correctly requires more machinery than a single ~ClassName() finalizer or a single Dispose() method alone - the real Dispose pattern uses both, coordinated through one shared protected method: public void Dispose() calls GC.SuppressFinalize(this), then calls a protected virtual void Dispose(bool disposing); the finalizer ~ClassName() calls Dispose(false), nothing else; and Dispose(bool disposing) itself releases unmanaged resources unconditionally, but only touches other managed, disposable objects when disposing is true. The reasoning: if a caller properly calls Dispose() (or uses using), disposing is true, so both managed and unmanaged cleanup run, and SuppressFinalize tells the GC to skip queuing this object for finalization entirely, since cleanup already happened deterministically. If a caller forgets and the object is only ever finalized by the GC instead, disposing is false, because by the time a finalizer runs, other managed objects this instance references may already have been finalized in an unpredictable order, and touching them from a finalizer risks touching already-finalized memory - only unmanaged handles, which the GC does not know how to clean up itself, are safe to release unconditionally from that path."""},

            {"h": "WORKED EXAMPLE: A CLASS WRAPPING A REAL UNMANAGED-STYLE RESOURCE CORRECTLY", "body": r"""    public class TempResource : IDisposable {
        private FileStream stream;
        private bool disposed = false;

        public TempResource(string path) {
            stream = new FileStream(path, FileMode.Create);
        }

        protected virtual void Dispose(bool disposing) {
            if (disposed) return;
            if (disposing) {
                stream?.Dispose();     // safe to touch managed objects here
            }
            disposed = true;
        }

        public void Dispose() {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        ~TempResource() { Dispose(false); }
    }

The disposed guard makes Dispose() safe to call more than once - the second call returns immediately instead of re-disposing an already-released resource, which matters because IDisposable's contract explicitly requires Dispose() to be idempotent, unlike a constructor which by definition only ever runs once. GC.SuppressFinalize(this) is the line most beginners skip; without it, even a properly-disposed object still gets queued for finalization later, wasting a GC cycle checking a finalizer that, thanks to the disposed guard, will now do nothing at all."""},

            {"h": "FAILURE MODES: DOUBLE DISPOSE, FORGOTTEN SuppressFinalize, AND FINALIZER-ONLY CLEANUP", "body": r"""Forgetting GC.SuppressFinalize(this) inside Dispose() is a subtle, non-crashing bug: the object still gets cleaned up correctly (the disposed guard prevents double-cleanup), but it now survives to be placed on the GC's finalization queue anyway, meaning it takes at least one extra garbage collection generation to actually reclaim the object's memory - a real, measurable cost under load for a class instantiated frequently, even though nothing about program correctness looks wrong in ordinary testing. Relying on the finalizer ALONE for something like a database connection, skipping Dispose()/using entirely and hoping ~ClassName() eventually cleans up, is dangerous specifically because finalization timing is fundamentally non-deterministic - the GC decides when, or if before process exit, to run finalizers, based on memory pressure, not on how badly your connection pool needs that connection back right now - so under load, a program relying on finalizers alone can exhaust a limited resource long before the GC gets around to finalizing the objects holding them. A Dispose() implementation that is NOT idempotent, one that unconditionally disposes stream without the disposed guard, throws ObjectDisposedException or NullReferenceException the second time anything calls Dispose() on the same instance, which happens more often than beginners expect, since both a using block's automatic call and an explicit manual call can easily target the same object."""},

            {"h": "HOW A PROFESSIONAL USES using DECLARATIONS AND IAsyncDisposable", "body": r"""Modern C# (8 and later) offers a using DECLARATION - using var resource = new TempResource(path); with no braces at all - which disposes the resource at the end of the enclosing block rather than an explicitly nested one, letting you avoid a deep pyramid of nested using blocks when a method needs several disposable resources open simultaneously; the compiler still generates the equivalent try/finally underneath, this is purely a readability improvement, not a different guarantee. For genuinely async cleanup, releasing a resource that itself requires an asynchronous operation, like flushing a network stream, IAsyncDisposable's DisposeAsync() method pairs with await using, so cleanup can itself be awaited rather than forced to block synchronously inside an ordinary Dispose(), which would otherwise defeat the entire purpose of writing async code elsewhere in the same class. Static analysis tools (Roslyn analyzers like CA2000, built into most IDEs) flag a disposable object that is created but never disposed along any code path, catching exactly the forgot Dispose entirely mistake at compile/review time rather than discovering it later as a slow resource leak in production - professionals treat a CA2000 warning as a real bug, not noise to suppress."""},

            {"h": "WHERE THIS IS GOING: DETERMINISTIC CLEANUP AS A SECURITY PROPERTY", "body": r"""Deterministic cleanup is not merely tidiness - in security-relevant code specifically, WHEN a resource is released can matter as much as whether it eventually is. A cryptographic key held in an unmanaged buffer, a lock protecting a security-critical section, a socket serving an authenticated session: leaving any of these open longer than necessary, because cleanup was left to an unpredictable finalizer pass instead of an immediate Dispose(), extends the window during which that resource is available to be misused, inspected, or exhausted by an attacker deliberately triggering the same code path repeatedly, a denial-of-service technique against connection or handle limits that is very real, not theoretical. This lesson's Dispose pattern reappears directly in cs-5's file-handling material (using statements guaranteeing a file closes even when an exception is thrown mid-read) and in cs-4's async material (IAsyncDisposable extending the exact same guarantee into asynchronous code) - by the end of this track you will have seen the identical acquire, guarantee release even under an exception idea implemented three different ways in three different contexts, a strong signal it is not a C#-specific quirk but a fundamental resource-safety pattern every language you use professionally will require you to get right."""},
        ],
    },

    "cs-4": {
        "title_check": "Delegates, events & async",
        "sections": [
            {"h": "MENTAL MODEL: A DELEGATE IS A FUNCTION POINTER THAT REMEMBERS ITS TARGET", "body": r"""A C# delegate is a type-safe object that holds both a reference to a method and, for an instance method, a reference to the target object that method should run against - calling the delegate calls the method on that remembered target, exactly as if you had written obj.Method() yourself, just through an indirection you can pass around, store in a field, or invoke later without the caller needing to know which concrete method, or even which class, is on the other end. Java has no direct equivalent language feature - the closest historical analogs were an anonymous inner class implementing a single-method interface, and modern Java lambdas targeting a functional interface (Runnable, Function<T,R>) achieve a similar effect, but a C# delegate type is closer to the interface itself being auto-generated for you, and crucially, delegates in C# are natively MULTICAST - a single delegate variable can hold a whole ordered list of methods (built with +=) and invoking it calls every one of them in sequence, which is precisely the mechanism an event is built from: an event is essentially a delegate field with the assignment operator hidden from outside subscribers, who are only allowed += and -=."""},

            {"h": "MECHANISM: async/await IS A COMPILER-GENERATED STATE MACHINE", "body": r"""An async method's body is not executed straight-through the way it visually reads - the C# compiler rewrites it entirely into a class implementing IAsyncStateMachine, with the method's local variables becoming fields on that class (so they survive across suspension) and the method's logic becoming the body of a single MoveNext() method containing a state number and a switch over it. Each await point becomes a state transition: the first time MoveNext() runs, it executes code up to the first await, calls GetAwaiter() on the awaited value, checks IsCompleted, and if the awaited operation has not finished yet, registers a continuation (via OnCompleted) that will call MoveNext() again later, then RETURNS immediately, freeing the current thread entirely rather than blocking it. When the awaited operation eventually finishes, on whatever thread happens to run the continuation, MoveNext() runs again, the switch jumps straight to the state saved from before, calls GetResult() to retrieve the awaited value, and continues executing until the next await or the method's end. This is precisely why async does not create new threads by itself - it is a mechanical way of splitting one method into resumable chunks connected by callbacks, letting a single thread serve many in-flight async operations by never sitting idle waiting on any one of them."""},

            {"h": "WORKED EXAMPLE: WHAT THE COMPILER ACTUALLY BUILDS FROM TWO AWAITS", "body": r"""    async Task<string> FetchAsync() {
        var a = await StepOneAsync();   // state 0 -> suspends here
        var b = await StepTwoAsync(a);  // state 1 -> suspends here
        return a + b;                   // state 2 -> completes
    }

The compiler-generated MoveNext() roughly corresponds to: state 0 runs StepOneAsync(), and if it is not already finished, saves state=1 and returns; when resumed, state 1 retrieves a, runs StepTwoAsync(a), and if not finished, saves state=2 and returns; when resumed again, state 2 retrieves b, computes a + b, and marks the returned Task as completed with that result. Notice the local variable a must survive from state 0 all the way to state 2, which is exactly why it becomes a FIELD on the compiler-generated state machine class rather than a true stack-local variable, since the method's actual call stack frame is long gone by the time StepTwoAsync finishes; only the heap-allocated state machine object keeps a alive across the gap, the same underlying trick as a suspended generator frame, applied to a different syntax."""},

            {"h": "FAILURE MODES: async void, FORGOTTEN await, AND THE CLASSIC .Result DEADLOCK", "body": r"""async void is meant for exactly one situation, a UI event handler whose signature is fixed by an existing framework delegate type and cannot be Task-returning, and it is a trap everywhere else: exceptions thrown inside an async void method cannot be caught by whoever called it (there is no Task to observe or await), so they propagate directly to the synchronization context and typically crash the process instead of being handled anywhere sensible; prefer async Task for every async method that is not literally a legacy event handler. Forgetting to await a call that returns a Task, StepOneAsync(); instead of await StepOneAsync();, an easy thing to type past, compiles cleanly (with a CS4014 warning, easy to miss in a crowded build log) and launches the async work without the current method waiting for it, so execution moves on to the next line with that work still running in the background, unfinished, and any exception it eventually throws goes essentially nowhere anyone is watching. The classic async deadlock, calling asyncMethod().Result or .Wait() from code running on a context that only allows one thread at a time (historically ASP.NET's request context, or a WPF/WinForms UI thread), happens because .Result blocks that one thread waiting for the async method to finish, but the async method's continuation after its own internal await is specifically scheduled to resume ON that same captured context, which is now permanently blocked waiting for it - two things each waiting on the other, forever."""},

            {"h": "HOW A PROFESSIONAL STRUCTURES ASYNC CODE AND EVENT SUBSCRIPTION SAFELY", "body": r"""Library code, anything not directly touching a UI, should call ConfigureAwait(false) on every internal await, telling the runtime not to bother capturing and resuming on the original synchronization context, since a library does not know or care whether its caller has a UI thread to worry about - this both sidesteps the exact deadlock class from the previous section and avoids unnecessary context-switching overhead; application-level code closer to the UI generally omits it, because that code specifically needs to resume on the UI thread to touch UI controls safely afterward. When a method needs several independent async operations, awaiting them one at a time sequentially needlessly serializes work that could run concurrently - Task.WhenAll(A(), B()) starts both immediately and awaits their combined completion, the async equivalent of realizing two independent LINQ queries do not need to wait on each other. For events specifically, professionals subscribe and unsubscribe symmetrically (a handler added in a constructor or Load method should be removed in the matching Dispose or Unload, or the publisher keeps the subscriber object alive indefinitely, a subtle memory leak) and invoke an event defensively, EventName?.Invoke(this, args), because a race between an unsubscribe on one thread and an invoke on another can otherwise null-reference on the invoke itself."""},

            {"h": "WHERE THIS IS GOING: NON-BLOCKING I/O IS HOW REAL SERVERS SCALE", "body": r"""The entire reason async/await exists is to let a relatively small number of threads serve an enormous number of concurrent, mostly-waiting operations - a web server handling ten thousand simultaneous slow client connections with a thread-per-connection model would need ten thousand threads, each expensive in memory and context-switch overhead, while the exact same server built on async I/O needs only as many threads as it has CPU cores, because a connection merely waiting on the network holds no thread hostage at all, freeing it to serve a different connection during that wait. This is the direct C# analog of the GIL and blocking I/O releasing the GIL for other threads to run in Python - different mechanism, a compiler-generated state machine here versus cooperative thread scheduling there, identical underlying goal: do not let a thread sit idle just because one particular operation is slow. It also matters directly for anything you will eventually build or analyze in a security context: understanding that a service handles many connections through cooperative, non-blocking scheduling rather than one thread apiece is exactly the background needed to reason about resource-exhaustion attacks, what actually happens if ten thousand connections all deliberately never send their final byte, against a real async server, versus a naive thread-per-connection one."""},
        ],
    },

    "cs-5": {
        "title_check": "Exceptions & files",
        "sections": [
            {"h": "MENTAL MODEL: AN EXCEPTION UNWINDS THE STACK - AND C# LETS YOU FILTER WHILE IT DOES", "body": r"""Like Java, a thrown C# exception unwinds the call stack looking for a matching catch, running any finally blocks it passes through along the way - but C# has one real feature Java lacks entirely: exception FILTERS, the catch (IOException ex) when (condition) syntax, which lets a catch clause inspect the exception, or any other state, and decide NOT to handle it after all, letting it continue unwinding past this catch to search for a different handler further up, all without the cost and side effects of catching and immediately re-throwing. This matters because catching broadly and then re-throwing based on an if check inside the catch block is subtly different from a real filter: the naive version still runs, and can still be observed by, debugger first-chance exception breakpoints and any code watching for that catch to have been entered, while a genuine when filter that evaluates false means this catch clause was never truly entered at all - the exception simply kept unwinding as if this catch clause did not match in the first place, closer to what the programmer usually actually means by handle only if."""},

            {"h": "MECHANISM: throw; VS throw ex; - THE STACK TRACE BUG THAT SURVIVES FROM JAVA HABITS", "body": r"""Inside a catch block, writing bare throw; (no expression after it) re-throws the CURRENTLY CAUGHT exception while preserving its original stack trace completely intact - the trace still shows exactly which line first threw it, deep in whatever method originally failed. Writing throw ex; instead, naming the caught exception variable explicitly, is a genuinely common and damaging mistake: it also re-throws the same exception object, but it RESETS the stack trace's starting point to this throw ex; line itself, permanently destroying the information about where the exception truly originated, exactly what a developer debugging a production log later needs most and now cannot recover. This is a real, easy-to-miss trap for Java transplants specifically, because Java's exact same-looking idiom, throw e; inside a catch block, does NOT reset anything - Java's stack trace is captured once, at the exception's construction site, and stays fixed regardless of how many times it is subsequently re-thrown, so a habit completely harmless in Java becomes a real bug the moment it is typed unchanged into C#. The safe rule with no exceptions: use bare throw; to rethrow the current exception, and reserve throw someNewException(...) only for genuinely wrapping it in a new, different exception, ideally with the original attached as InnerException."""},

            {"h": "WORKED EXAMPLE: LAYERED STREAMS AND WHY File.ReadAllText ISN'T ALWAYS RIGHT", "body": r"""    using var fs = new FileStream("data.txt", FileMode.Open);
    using var reader = new StreamReader(fs);
    string line;
    while ((line = reader.ReadLine()) != null) {
        Process(line);
    }

FileStream here is the raw channel onto the actual OS file handle; StreamReader wraps it, adding text decoding (bytes to characters, respecting an encoding) and buffered line-oriented reading - two layers, each with a single clear job, composed together rather than one class trying to do both. File.ReadAllText("data.txt") hides both layers behind one call and is genuinely the right choice for a small config file you need entirely in memory anyway, but it allocates a single string holding the ENTIRE file's contents at once - for a multi-gigabyte log file, that one line can exhaust available memory outright, where the layered StreamReader.ReadLine() approach above processes one line at a time and never holds more than a small buffer plus the current line in memory regardless of the file's total size, the same memory-versus-convenience tradeoff that shows up anywhere a large file must be read lazily."""},

            {"h": "FAILURE MODES: SWALLOWED EXCEPTIONS AND THE OUT-OF-MEMORY SURPRISE", "body": r"""An empty or near-empty catch block, catch (Exception ex) { } or worse, catch { } with no logging, no rethrow, nothing, is the single most damaging exception-handling mistake in real codebases, not because the immediate code crashes (it deliberately does not), but because it converts a genuine, actionable failure into total silence: the operation quietly did not do what it was supposed to, no log entry exists anywhere, and the bug report that eventually arrives has zero trace of a root cause anywhere in the logs, because the exception carrying that exact root cause was thrown away the instant it was caught. Second, the memory surprise from the previous section is not theoretical - File.ReadAllText or File.ReadAllLines on a file that turns out to be far larger than expected (a log file that grew unexpectedly, a user-supplied upload with no size limit enforced) can throw OutOfMemoryException in a program that otherwise looks completely correct, precisely because the convenience method's contract is load the whole thing, with no partial-failure mode - the fix is either a size check before choosing which API to call, or defaulting to the streaming StreamReader approach whenever the file's size is not already known to be small and bounded."""},

            {"h": "HOW A PROFESSIONAL LOGS, FILTERS, AND CHOOSES A READ STRATEGY", "body": r"""Professional logging captures the exception OBJECT, not ex.Message - logger.LogError(ex, "export failed for order {Id}", orderId) preserves the full exception, including its StackTrace, InnerException chain, and HResult, a numeric error code C# inherited from its COM ancestry, still populated on many system exceptions and occasionally the only reliable way to distinguish two different underlying OS failures that otherwise throw the exact same exception TYPE - throwing away everything but .Message discards precisely the detail a real incident review needs. Exception filters are the professional's tool for handling ONE specific failure mode of a broader exception type without swallowing every other case: a filtered catch on IOException checking a specific HResult handles file is currently open elsewhere specifically, while letting every other IOException, disk full, path too long, permissions, continue unwinding to a more general handler elsewhere, which a plain catch with an if/return inside cannot cleanly express without accidentally also swallowing those other cases. For file reads, the professional default is to ask do I need the whole file in memory at once, or can I process it as a stream before reaching for File.ReadAllText out of habit, exactly because the convenient API and the correct API are not always the same one."""},

            {"h": "WHERE THIS IS GOING: WHAT AN EXCEPTION REVEALS IS A SECURITY QUESTION TOO", "body": r"""Everything an exception carries, a message, a stack trace, an HResult, an inner exception chain, is potentially valuable to YOU during debugging and potentially valuable to an ATTACKER if it reaches somewhere they can see it, exactly why a production API that returns a raw exception's ToString() or stack trace in an HTTP response body is a real, common vulnerability class: it discloses file system layout, internal class and method names, sometimes library versions with known CVEs, all for free, to anyone who can trigger an error condition on purpose. The throw; versus throw ex; distinction from this lesson is not merely a style nitpick either - a stack trace reset to the wrong location in a production log is a genuine incident-response cost, sending an investigator hunting in the wrong part of the codebase entirely while the real defect sits untouched. And the streaming-versus-load-it-all-at-once choice from this lesson has a direct security reading too: an endpoint that calls File.ReadAllText or an equivalent on a user-influenced path or size, with no bound, is a resource-exhaustion vector - an attacker who can cause your service to load an arbitrarily large file into memory on demand has found a low-effort denial-of-service, the exact failure mode this lesson already walked through, just aimed on purpose instead of discovered by accident."""},
        ],
    },

    "cs-6": {
        "title_check": "Generics & the type system",
        "sections": [
            {"h": "MENTAL MODEL: C# GENERICS ARE REAL AT RUNTIME - JAVA'S ARE ERASED", "body": r"""Java generics are ERASED: List<Integer> and List<String> are, at runtime, both literally the exact same class, List, with the compiler inserting invisible casts at every point you read an element back out, and no way to ask a Java List<T> at runtime what T even was, the classic Java limitation where a method cannot do new T() or check if (x instanceof T) without an explicit Class<T> token passed in manually as a workaround. C# generics are REIFIED instead: List<int> and List<string> are genuinely different, distinct types at runtime, each fully aware of its own type argument, and typeof(T) works correctly from inside a generic method with zero workaround needed, because the type parameter is not a compile-time-only fiction erased before execution, it is real information the CLR retains and can act on. This is arguably the single largest conceptual gap between Java's and C#'s type systems, bigger in practice than any syntax difference covered in cs-1, and it directly explains why C# generic collections avoid the boxing problem from cs-1 entirely: the runtime genuinely knows, for a List<int> object, that it holds actual ints, not just objects that were ints once and got cast back with a leap of faith."""},

            {"h": "MECHANISM: HOW THE JIT SPECIALIZES A GENERIC FOR EACH VALUE TYPE", "body": r"""The CLR does not generate one universal implementation of List<T> and reuse it unchanged for every T - it takes a middle path more efficient than full C++-template-style duplication for every type, and dramatically better than Java's erasure for value types specifically. For any REFERENCE type argument (List<string>, List<object>, your own List<Customer>), the JIT generates and shares ONE compiled implementation, because every reference is just a pointer of the same size, and the generic code can treat them uniformly, with the correct type still tracked in metadata for typeof and casts, just not needing separate machine code per reference type. For any VALUE type argument (List<int>, List<double>, List<YourStruct>), the JIT generates a SEPARATE, SPECIALIZED compiled implementation the first time that particular closed generic type is actually used, with the value type's real size and layout baked directly into the generated machine code, which is exactly how a List<int> stores actual 4-byte ints inline in its backing array with zero boxing, a genuinely different, dedicated code path from List<string>'s, not the same code pretending to work for both. This hybrid strategy, share for reference types, specialize for value types, is precisely what lets C# have both memory efficiency and a manageable number of compiled code paths, rather than choosing one extreme or the other."""},

            {"h": "WORKED EXAMPLE: typeof(T) AND GetType() DOING SOMETHING JAVA SIMPLY CANNOT", "body": r"""    public class Box<T> {
        public T Value { get; set; }
        public Box(T v) { Value = v; }
        public void Describe() {
            Console.WriteLine($"Box holds a {typeof(T).Name}");
            if (typeof(T) == typeof(int)) {
                Console.WriteLine("this box specifically holds an int");
            }
        }
    }
    new Box<int>(5).Describe();       // Box holds a Int32 / this box specifically holds an int
    new Box<string>("hi").Describe(); // Box holds a String

typeof(T) inside Describe() genuinely reflects whichever T this particular closed instantiation, Box<int> versus Box<string>, was built with - there is no equivalent in Java without manually threading a Class<T> parameter through the constructor yourself, because erasure has already thrown that information away by the time any Java method body runs. new Box<int>(5).GetType() and new Box<string>("hi").GetType() likewise return two genuinely DIFFERENT Type objects, each reporting a distinct, fully specified generic type - proof, visible at runtime, that these are not secretly the same erased class wearing different casts, the way they would be in Java."""},

            {"h": "FAILURE MODES: default(T), TYPE-CHECKING INSIDE GENERIC CODE, AND == WITHOUT A CONSTRAINT", "body": r"""default(T) resolves differently depending on what T turns out to be, and code that assumes ONE behavior across all possible T breaks the moment someone instantiates the generic with the other kind of type: for a reference type, default(T) is null; for a value type, default(T) is the type's zero-equivalent, 0 for int, false for bool, a struct with every field zeroed, NEVER null, because a value type genuinely cannot hold null unless wrapped in Nullable<T> (T?). Code that checks value == default(T) intending to test was this never set works fine for reference types but silently means something different for an int, since 0 is a perfectly valid, deliberately-set int, indistinguishable from never set by this check. Second, writing a chain of if (typeof(T) == typeof(string)) branches inside a generic method is close to always a design smell - it means the method is not genuinely generic at all, just a disguised series of type-specific branches wearing a single signature, and it will not scale to a third caller's type without editing this method's source, defeating the entire point of writing it generically. Third, a == b inside a generic method, where a and b are both plain T with no constraint applied, does not compile - the compiler cannot know in advance whether T's == means identity, value equality, or is even defined at all, so it refuses the comparison outright unless you add a constraint or fall back to EqualityComparer<T>.Default.Equals(a, b)."""},

            {"h": "HOW A PROFESSIONAL CHOOSES CONSTRAINTS OVER RUNTIME TYPE CHECKS", "body": r"""A professional facing the my generic method needs to behave differently depending on T urge reaches for a CONSTRAINT rather than a runtime type check almost every time: where T : IComparable<T> lets you write a.CompareTo(b) directly inside a fully generic method, working correctly for every T that satisfies the constraint, with the compiler enforcing at the CALL SITE, not discovered at runtime, that only appropriate types can be substituted in at all - a caller trying Box<SomeType> where SomeType does not implement IComparable<T> gets a compile error immediately, rather than your typeof-branching code silently doing nothing sensible for a type nobody anticipated. where T : class, where T : struct, and where T : new() unlock, respectively, treating T as nullable-capable, guaranteeing default(T) behaves like a genuine value type, and calling new T() inside the generic method, impossible without the constraint, since the compiler cannot otherwise guarantee every possible T even has a public parameterless constructor, three narrow, specific promises about T that the compiler then lets you rely on. Naming conventions matter too: a single unconstrained type parameter is T by convention, while multiple or more specific ones use TKey/TValue/TResult/TItem, purely a readability convention, but one every professional C# codebase follows closely enough that deviating from it reads as a translated-from-somewhere-else oddity."""},

            {"h": "WHERE THIS IS GOING: REIFIED GENERICS EXPLAIN EARLIER LESSONS IN THIS TRACK", "body": r"""Reification is not an isolated fact about this one lesson - it retroactively explains WHY several earlier lessons in this track worked the way they did. cs-1's boxing discussion, a value type only boxes when stored as object, and List<int> avoids it, only holds because List<T> is reified and specializes per value type exactly as this lesson describes - in an erased generic system, every element of every generic collection would need boxing, with no way around it, since a single shared implementation would have to treat every T uniformly as an object reference. cs-2's entire LINQ surface is itself generic from top to bottom, IEnumerable<T>, Where<T>, Select<TSource,TResult>, and reification is exactly why a LINQ query over a List<int> genuinely processes unboxed ints element by element rather than silently boxing every single one along the way, a real performance property Java's erased Stream<Integer> cannot match without its own boxing cost baked in permanently. Beyond this track, reified generics with zero forced boxing for value types are a meaningful reason C# and the wider .NET runtime get used for performance-sensitive and systems-adjacent work in ways plain, erasure-based Java historically could not reach without considerable extra effort, a fitting closing fact for a track that began with C# is Java plus some deltas, because this is one delta whose consequences run all the way through everything else you have just learned."""},
        ],
    },

}
