# depth_cyber_low.py — extended teaching content for the cyber_low track.
# Auto-attached by depth.py. One entry per lesson id.

DEPTH = {

    "cl-1": {
        "title_check": "Bases & bitwise",
        "sections": [
            {"h": "MENTAL MODEL: THERE IS NO SUCH THING AS A HEX NUMBER IN MEMORY", "body": r"""Every value a computer ever manipulates - an integer, a character, part of a floating-point number, even a CPU instruction - is, physically, nothing but a fixed number of bits: electrical high or low, magnetic domains, transistor states. Decimal, binary and hexadecimal are not three different kinds of data; they are three different NOTATIONS for describing the exact same bit pattern, and the conversion between them is always exact, never a rounding approximation like converting miles to kilometers. Binary is what the hardware actually is. Hex exists purely for human convenience, because one hex digit maps exactly onto a group of 4 bits (a nibble), so a full byte (8 bits) is always exactly two hex digits, ranging from 00 to FF, which is 0 to 255 in decimal. That clean 4-bits-per-digit relationship is why programmers write hex instead of binary or decimal when talking about raw memory: 0xFF instantly tells you "both nibbles maxed out," something 255 hides and 11111111 makes tedious to parse at a glance.

The deeper lesson hiding inside this: a byte in memory has no inherent meaning as "a number," "a letter," or "an instruction." The value 0x41 is the character A in ASCII, the decimal integer 65, and could equally be read as a raw opcode byte by a disassembler - which interpretation is correct depends entirely on what is reading it and what it declared that byte to be. This ambiguity is not a flaw; it is the single fact that makes type-confusion bugs and clever reverse-engineering both possible."""},

            {"h": "THE FIVE BITWISE OPERATORS, BIT BY BIT", "body": r"""Five operations move every bit independently, with no carrying between bit positions - which is exactly what makes them fast (one CPU instruction, one cycle) and predictable. AND (&) sets a result bit only if BOTH input bits are 1 - used to mask off bits you do not want: x & 0x0F keeps only the low nibble, zeroing the rest. OR (|) sets a bit if EITHER input bit is 1 - used to force specific bits on: flags | 0x04 turns bit 2 on regardless of its previous state. XOR (^) sets a bit if the two input bits differ - it is both a bit-flipper (x ^ 0xFF flips every bit) and a comparator (a ^ b is zero exactly where a and b already agree). NOT (~) simply flips every bit of a single value. Shifts move bits sideways: x << n multiplies by 2^n (bits move toward the high end, filling with zero from the low end), x >> n divides by 2^n (an arithmetic right shift on signed types preserves the sign bit by copying it in, so negative numbers stay negative).

Two's complement is what makes signed integers work on this same hardware: to negate a value, invert every bit then add 1. That single rule is why a signed byte covers -128 to 127, not -127 to 127: 0x80 (1000 0000) inverted is 0x7F, plus 1 is 0x80 again - meaning -128 has no positive counterpart, and negating it overflows right back to itself."""},

            {"h": "A WORKED DUMP: FOUR BYTES, READ THREE WAYS", "body": r"""Take a tiny 4-byte blob you might see at the start of any hex dump:

    offset 00: 5A 9A 3C 07

Byte 0 is 0x5A = 0101 1010 binary = 90 decimal. Byte 1 is 0x9A = 1001 1010 binary = 154 decimal - notice the top bit is set, so if this byte were read as a SIGNED 8-bit value instead of unsigned, two's complement says invert (0110 0101) and add 1 (0110 0110 = 0x66 = 102), so signed it reads as -102, not 154. Same eight bits, two legitimate readings - the type you declare decides which one your program computes with.

Now apply real operations: byte0 & 0x0F = 0x0A (the low nibble only). byte0 | 0x01 = 0x5B (forces the lowest bit on). byte0 ^ byte1 = 0x5A ^ 0x9A = 1100 0000 = 0xC0 (every bit position where the two bytes disagree). Finally, (byte1 << 8) | byte0 combines two bytes into one 16-bit value, 0x9A5A - and the ORDER you combined them in (byte1 as the high byte) is a decision, not a law of physics; get that decision backwards and you have accidentally reinvented the exact confusion endianness exists to name, which is where cl-2 picks up."""},

            {"h": "FAILURE MODES: WRAPAROUND, SIGN CONFUSION, AND WEAK XOR 'ENCRYPTION'", "body": r"""Two's complement wraparound is a real, exploitable bug class, not a textbook curiosity. If a signed 8-bit counter is at 127 and gets incremented, the bit pattern rolls over to 1000 0000 - which reads as -128, not 128. Code that assumes "counters only go up" (a loop bound, a size check, a reference count) can be pushed through this wrap by an attacker who controls how many times it increments, flipping a "this is way too big, reject it" check into "this looks negative or small, allow it." This exact class of bug - integer overflow leading to a bypassed bounds check - has caused countless real memory-corruption vulnerabilities in shipped software.

Signed/unsigned confusion is the sibling bug: if an unsigned size_t is compared against a signed int that could be negative, the signed value gets silently converted to unsigned first, turning a negative number into a huge positive one - a check like "if (len < 0) reject" can be dead code that never fires once len's type does not match the comparison. And XOR is often misused as "encryption": XOR-ing data with a repeating single-byte or short key is trivially broken by frequency analysis or by XOR-ing two ciphertexts together, because XOR is its own inverse - it deters a casual glance, not a real attacker, and should never be presented as genuine security."""},

            {"h": "HOW AN ANALYST WORKS IN MULTIPLE BASES WITHOUT A CALCULATOR", "body": r"""Fluency here means never reaching for a calculator mid-investigation. In gdb, p/x var prints a variable in hex, p/t prints it in binary, and p/d forces decimal - switching formats on the same value while debugging is instant and constant during real work. Python's built-ins do the same outside a debugger: hex(181), bin(181), and int("b5", 16) round-trip between all three notations in one line, which is why interactive Python is a standard scratchpad for reverse engineers, not just a scripting language.

The real payoff is pattern recognition: a permissions value like chmod 755 is read as three octal digits (7=rwx, 5=r-x, 5=r-x) because each digit is exactly 3 bits, mirroring hex's 4-bits-per-digit trick at a different grouping. A TCP flags byte of 0x12 is recognized on sight as SYN+ACK (0x02 | 0x10) by anyone fluent in bitwise OR, with no chart needed. An IP header's version+IHL byte of 0x45 is read instantly as "version 4, header length 5 words (20 bytes)" because the top nibble and bottom nibble were packed independently. Every one of these is the exact same skill from sections 1-3, just applied to a different field name in a different protocol."""},

            {"h": "WHERE THIS GOES NEXT", "body": r"""Nothing in this track works without this lesson underneath it. cl-2 is this lesson applied across MULTIPLE bytes at once - endianness is simply "which order do the bytes of a multi-byte value get stored in," a question that only makes sense once you accept a byte as the atomic unit and hex as its readable form. cl-3's process memory map is made of nothing but sequences of these bytes, addressed by number. cl-4's PE and ELF headers are, byte for byte, exactly this kind of bit-packed field you just decoded for an IP header - a magic number, a version nibble, a set of flag bits, all sitting at fixed offsets. cl-5's IEEE-754 floats are a sign bit, exponent bits and mantissa bits packed into one word using precisely the AND/OR/shift vocabulary from section 2. And cl-6's stack overflow is "the wrong bytes end up in the wrong place" expressed as a security failure rather than an arithmetic one.

If the conversions and masks in this lesson ever feel like busywork, remember: every later lesson is this lesson wearing a different hat, on a bigger pile of bytes."""},
        ],
    },

    "cl-2": {
        "title_check": "Endianness & hex dumps",
        "sections": [
            {"h": "MENTAL MODEL: ENDIANNESS ORDERS BYTES, NEVER BITS", "body": r"""A single byte has exactly one meaning regardless of endianness - 0x9A is 0x9A, full stop, on every machine ever built. Endianness only becomes a question the instant a value needs MORE than one byte to represent - a 16-bit short, a 32-bit int, a 64-bit pointer - because now there is a genuine choice: does the most significant byte (the "big end") go at the lowest memory address, or does the least significant byte (the "little end") go there instead? Big-endian stores the big end first; little-endian stores the little end first. That is the entire concept, and it is critical to be precise about what it does NOT mean: endianness never touches the order of BITS inside a single byte. Bit 7 of a byte is always its most significant bit, on every architecture, regardless of endianness - only the arrangement of whole BYTES within a multi-byte value ever changes.

x86 and x86-64 (what your machine almost certainly runs) are little-endian. Network protocols - and therefore anything crossing the wire, from an IP address to a TCP port number - use big-endian by convention, historically called "network byte order." This is precisely why code that reads raw packet bytes must explicitly convert (ntohs/ntohl in C) before using the value as a normal integer, and why getting this backwards silently produces a wrong-but-plausible-looking number instead of a crash."""},

            {"h": "THE SAME FOUR BYTES, TWO VALID READINGS", "body": r"""Take the 32-bit value 0x12345678 and store it starting at memory address 0x1000. On a little-endian machine, the bytes appear in memory, address ascending, as: 0x1000 = 78, 0x1001 = 56, 0x1002 = 34, 0x1003 = 12 - the LEAST significant byte (78) sits at the LOWEST address. On a big-endian machine, the same value at the same starting address appears as: 0x1000 = 12, 0x1001 = 34, 0x1002 = 56, 0x1003 = 78 - the MOST significant byte sits first. Read either sequence back the way it was written (lowest address to highest) and reinterpret it as one number, and you reconstruct 0x12345678 correctly only if you knew which convention produced it; read a little-endian sequence assuming big-endian (or vice versa) and you get 0x78563412 instead - a completely different, silently-wrong number, with no error raised anywhere.

This is exactly why a hex dump display groups bytes left to right in ADDRESS order, not value order: xxd or a hex editor always shows you memory exactly as it sits, address ascending, and it is your job as the reader to know the endianness convention before assembling adjacent bytes into a multi-byte number. The tool never does that reassembly for you unless you explicitly tell it the field width and byte order."""},

            {"h": "READING A REAL xxd-STYLE DUMP", "body": r"""A typical xxd line looks like this - offset, then sixteen hex bytes, then their ASCII rendering (a dot for anything unprintable):

    00000000: 4d5a 9000 0300 0000 0400 0000 ffff 0000  MZ..............
    00000010: b800 0000 0000 0000 4000 0000 0000 0000  ........@.......

Reading left to right: offset 0x00000000, then the bytes 4d 5a - exactly the ASCII characters M and Z shown honestly in the right-hand column - the unmistakable DOS header magic number that opens every Windows PE executable. Compare that against an ELF binary's opening bytes, 7f 45 4c 46 (7F followed by the ASCII letters E, L, F), a PNG's 89 50 4e 47 (a non-ASCII byte deliberately chosen so text-mode file transfers that mangle line endings get detected), or a ZIP's 50 4b 03 04 (PK, an homage to Phil Katz, PKZIP's author). None of these magic numbers depend on the file's extension - a malicious .txt file can start with 4d 5a and still be a valid, runnable PE executable if something naive enough executes it, which is precisely why real tools identify file type by reading these first bytes, never by trusting the name after the last dot."""},

            {"h": "FAILURE MODES: WRONG-ENDIAN PARSERS AND MAGIC-NUMBER GAMES", "body": r"""A file-format parser that reads a length field with the wrong endianness does not usually crash immediately - it computes a plausible-looking but wrong number and acts on it, which is far more dangerous than an outright error. A 4-byte length field of 00 00 01 00, meant as big-endian (value 256), read instead as little-endian becomes 0x00010000 (65536) - if that number is then used to size a buffer or a loop bound, you get either a massive over-allocation (denial of service) or an under-allocation elsewhere in the same parser feeding off a different field with the same mistake, producing a classic memory-corruption bug from nothing but a byte-order error, no attacker cleverness required beyond crafting the input.

Deliberately, attackers exploit the extension-versus-magic-number gap directly: a "polyglot" file is crafted to be simultaneously valid as two different formats depending on which parser reads it, by placing one format's magic number first and hiding the second format's content in a region the first parser ignores. Malware droppers also routinely rename or double-extension files (invoice.pdf.exe) counting on a user or a naive filter checking only the visible extension - the actual magic bytes, and therefore the actual file type, never lie, which is exactly why they are the correct thing to check."""},

            {"h": "HOW AN ANALYST VERIFIES FORMAT AND BYTE ORDER", "body": r"""The Linux file command is the fast first move on any unidentified file: it reads a database of known magic numbers and byte-offset signatures and reports "ELF 64-bit LSB executable" or "PE32+ executable (console) x86-64" without trusting the extension at all - LSB there literally means "least significant byte first," i.e. little-endian, printed explicitly because analysts need to know it. readelf -h binary goes further on an ELF file specifically, printing the e_ident bytes decoded field by field, including a Data: line that reads "2's complement, little endian" straight from the byte that encodes it - confirming byte order is a standard first check before trusting any multi-byte field elsewhere in the same file.

For anything without a friendly parsing tool yet, xxd file | head or hexdump -C file dumps the raw bytes so you can manually check the first several against a reference list of known magic numbers, and manually walk any suspicious length or offset field using the endianness the format specifies - never assuming your own machine's native endianness applies to a file that might have been produced on, or designed for, different hardware. This is the discipline of not trusting metadata over the actual bytes, applied one layer more literally than in section 4."""},

            {"h": "WHERE THIS GOES NEXT", "body": r"""Every subsequent lesson hands you a bigger dump built from exactly this skill. cl-3's process memory map is a set of regions you locate and reason about using the same byte-by-byte discipline. cl-4 puts real names to the magic numbers you can already recognize - MZ and 7F 45 4C 46 stop being "a pattern to memorize" and become "the first field of a structured header you can now read in full," including its own explicit endianness field. cl-5's IEEE-754 floats are themselves multi-byte values with a byte order, meaning a float dumped from a little-endian machine needs the exact same reassembly discipline as the 0x12345678 example in section 2 before its sign/exponent/mantissa bits mean anything. cl-6's stack-smashing discussion depends on knowing exactly which bytes of an overflowing buffer land on which bytes of the saved return address - and that mapping is, again, an endianness question.

The single habit worth keeping from this lesson: never assemble multi-byte fields in your head without first asking "which end is which," and never trust a file's claimed type over its first few bytes."""},
        ],
    },

    "cl-3": {
        "title_check": "How a process is laid out",
        "sections": [
            {"h": "MENTAL MODEL: AN ADDRESS SPACE IS A PRIVATE ILLUSION", "body": r"""Every running process is handed a private illusion: its own address space, as if it owned the machine's entire memory range alone, from address 0 up to some architecture-defined maximum. This is virtual memory - the addresses your program's instructions actually use (virtual addresses) are translated by the CPU's MMU (memory management unit), consulting page tables the OS maintains, into real physical RAM addresses that may be scattered anywhere, shared, or not even resident (paged to disk) at any given moment. Two processes can both believe they own address 0x00400000 simultaneously without conflict, because the translation - not the number itself - decides where the byte actually lives.

Within that private space, a running process's memory is organized into named regions, conventionally low addresses to high: .text (compiled instructions, read + execute, no write), .data (initialized globals and statics), .bss (zero-initialized globals), then the heap (dynamic allocation, grows upward), a large unused gap, and finally the stack (local variables and call frames, growing downward from a high address toward the heap). A virtual address is a position in this private map - it is NOT a file offset, and not a physical RAM address; confusing the three is one of the most common early mistakes when moving from reading source code to reading memory dumps or disassembly."""},

            {"h": "WHAT'S IN THE FILE VS WHAT EXISTS ONLY AT RUNTIME", "body": r"""Not every region you can see in a running process actually exists inside the executable file on disk - this is a distinction worth being exact about. .text and .data must be stored in the file, because their exact byte content (instructions, initial values) is meaningful and cannot be reconstructed from nothing. .bss, by contrast, is NOT stored in the file at all - the file only records a SIZE ("reserve this many zeroed bytes"), and the loader allocates and zero-fills that much memory at load time. This is a genuine, deliberate optimization: a 10 MB zero-initialized global array costs the executable file zero extra bytes, only a size field, because zeros need no storage, only an instruction to the loader.

The stack and heap do not exist in the file whatsoever; they are created fresh by the OS and the allocator, respectively, the moment the process starts running. A single stack frame - the memory a function uses for one call - conventionally holds, in order: the function's arguments, the saved return address (where execution resumes after this function returns), the saved previous frame pointer (so the frame can be torn down cleanly), and finally the function's own local variables. The heap has no such fixed layout; instead the allocator keeps its own metadata - chunk sizes, free-list pointers - interleaved between your actual allocated blocks, invisible to your code but very visible in a raw memory dump."""},

            {"h": "A WORKED MEMORY MAP, LOW TO HIGH", "body": r"""Picture a small program: a string literal "hello", a global int total = 0;, a global int count = 5; (non-zero initializer), a heap array from malloc, and a local int i inside main. Laid out low to high address (illustrative values, since real systems randomize the actual numbers via ASLR):

    0x00400000  .text     : compiled instructions, incl. main's code
    0x00401000  .rodata   : "hello" (read-only string data)
    0x00402000  .data     : count = 5           (real initial value, stored in file)
    0x00403000  .bss      : total = 0           (zero-filled at load, NOT stored in file)
    0x00500000  heap      : malloc'd array       (grows upward as you allocate more)
              ... unused gap ...
    0x7ffffff0  stack     : local i, saved return address, saved frame pointer

Every one of those five variables sits in a DIFFERENT, specific region for a specific reason: "hello" never changes, so it is read-only; count has a real non-zero starting value, so it must be stored in the file; total starts at zero, so it costs nothing to store, hence .bss; the malloc'd array's size was only known at runtime, hence heap; and i only needs to exist for the duration of one function call, hence stack. Reading any memory dump starts with asking exactly this question - which region is this address in, and what does that tell me about the variable's lifetime and origin."""},

            {"h": "FAILURE MODES: WHY LAYOUT KNOWLEDGE ENABLES MEMORY CORRUPTION", "body": r"""Every classic memory-corruption bug is, at its core, "code wrote past the boundary of the region it was given, into an adjacent region it had no business touching" - which is only possible to reason about, attack, or defend against once you accept these regions as physically adjacent, unprotected-by-default memory, not separate sealed boxes. A stack buffer overflow happens because a local array and the function's saved return address live in the SAME stack frame, often just a few bytes apart depending on the compiler's layout choices - write past the end of the array with attacker-controlled bytes and you are, mechanically, just continuing to write into whatever comes next in that frame, which cl-6 covers as its own full lesson.

A heap overflow is the same idea one region over: writing past the end of a malloc'd block corrupts either the allocator's own bookkeeping metadata for that chunk, or the START of the NEXT allocated block, silently corrupting a completely unrelated object your program still thinks is intact. Uninitialized-read bugs are the quieter cousin: reading a stack or heap region before writing your own data into it can leak whatever a PREVIOUS function call or PREVIOUS allocation left behind - passwords, pointers (which defeat ASLR if leaked), or other sensitive leftovers, a real and common information-disclosure bug class in shipped software."""},

            {"h": "HOW AN ANALYST READS A LIVE PROCESS'S MEMORY MAP", "body": r"""On Linux, cat /proc/<pid>/maps dumps the exact live region layout for a running process - each line shows a virtual address range, permissions (r/w/x), and which file (if any) is mapped there, letting you directly confirm "this address range is the heap," "this one is a loaded library's .text," or "this one is the stack," for a REAL process rather than a textbook diagram. Inside gdb, info proc mappings shows the same information for a process you are actively debugging, and x/20xw $sp examines the 20 words at the current stack pointer directly, in hex, letting you literally see saved return addresses and local variables sitting where this lesson says they should.

On Windows, Process Hacker or Sysinternals' VMMap give the equivalent view graphically - committed vs reserved memory, which ranges are image (the .exe/.dll's mapped sections), heap, or stack, per process. The single most valuable use of all of this in real investigation: when a program crashes, the faulting address itself tells you a huge amount before you read a single line of code - a crash inside .text with an odd permission fault often means a corrupted function pointer or return address; a crash reading a low address like 0x00000010 usually means a null-pointer-plus-small-offset bug; classifying WHICH region a bad address falls into is often the fastest first step in any crash investigation."""},

            {"h": "WHERE THIS GOES NEXT", "body": r"""This map is the stage every remaining lesson performs on. cl-4's PE and ELF headers are, quite literally, the instructions the loader reads to BUILD the exact layout described in section 3 - a section table entry saying ".bss, size 0x1000" is the file-level instruction behind the zero-filled region you just reasoned about in section 2. cl-5's struct padding happens INSIDE whichever region a given struct instance lives in - a global struct's padding bytes sit in .data or .bss, a heap-allocated struct's padding sits in a malloc'd block, but the padding rule itself does not change based on region. And cl-6 is this lesson's stack region, from section 4's failure-mode paragraph, expanded into a full mechanism: which exact bytes get overwritten, in which order, and what stops it.

Keep this mental picture active for the rest of the track - text, rodata, data, bss, heap, gap, stack, low address to high - because nearly every remaining question in cyber_low is really asking "given this fact about the layout, what does that make possible or impossible.\""""},
        ],
    },

    "cl-4": {
        "title_check": "PE vs ELF",
        "sections": [
            {"h": "MENTAL MODEL: A HEADER IS A LOADER'S INSTRUCTION MANUAL", "body": r"""An executable file sitting on disk is completely inert - no code is running, nothing is "happening" - until an OS loader reads its header and follows instructions encoded there. Every executable format, however different they look, answers the same handful of questions in its header: where does execution begin (the entry point)? what regions of the file need to become which regions of the process's address space from cl-3 (which bytes become .text, which become .data, how big should the zero-filled .bss be)? what OTHER files (shared libraries or DLLs) does this program need loaded first, and which functions does it borrow from them? Windows answers these questions with the PE (Portable Executable) format; Linux answers them with ELF (Executable and Linkable Format). Different byte layouts, identical underlying job.

Treat the header, then, not as trivia to memorize but as a literal instruction manual the loader executes before your first line of code ever runs. A section table entry is simply a row saying "take these bytes starting at file offset X, and place them at virtual address Y, with permissions Z" - once you read it that way, the entire format stops being an arbitrary list of field names and becomes a small, readable program that builds the address space from cl-3, one region at a time."""},

            {"h": "PE AND ELF, FIELD BY FIELD", "body": r"""A PE file opens with the "MZ" DOS stub (a tiny legacy program kept only for backward compatibility) followed by a pointer to the REAL PE header, marked by the 4 bytes P, E, 0, 0. After that: a COFF file header (target machine type, number of sections, a timestamp), then an "optional" header (not actually optional in practice) holding the entry point as an RVA - a Relative Virtual Address, meaning "offset from wherever this image gets loaded in memory" rather than an absolute address, because the loader may place the image at different base addresses under ASLR - plus the preferred image base and the subsystem (console vs GUI). Finally the section table: named rows like .text, .data, .rdata (read-only data, imports live here), each listing both a file offset+size and a virtual address+size, which can legitimately differ (that gap IS the .bss-style zero-fill from cl-3).

ELF's e_ident opens with 7F 45 4C 46, then single bytes for EI_CLASS (32 or 64-bit) and EI_DATA (endianness - a direct callback to cl-2). The ELF header then gives e_type (executable vs shared object), e_machine (CPU architecture), and e_entry (here, a real virtual address, not an RVA). ELF then splits its layout description into TWO tables serving different consumers: program headers describe segments - what the LOADER needs to map to run the program - while section headers describe sections like .text/.data/.bss/.symtab - what a LINKER or debugger needs, and can even be stripped entirely without breaking execution."""},

            {"h": "A WORKED readelf AND dumpbin READOUT", "body": r"""readelf -h ./program on a typical 64-bit Linux binary prints something like:

    Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
    Class:                             ELF64
    Data:                              2's complement, little endian
    Type:                              DYN (Position-Independent Executable)
    Entry point address:               0x1060
    Start of section headers:          13328 (bytes into file)

Reading it field by field: the Magic line is the raw e_ident bytes - 7f454c46 confirms ELF, the next byte 02 confirms 64-bit (EI_CLASS), 01 confirms little-endian (EI_DATA), matching "Class: ELF64" and "Data: ... little endian" printed just below in human-readable form. "Type: DYN" rather than "EXEC" tells you this binary is PIE (Position-Independent Executable) - built to support ASLR by being loadable at any base address, which is why its entry point (0x1060) is small and clearly relative rather than looking like a full memory address.

dumpbin /headers program.exe on Windows shows the PE equivalent: a FILE HEADER block listing machine type and number of sections, an OPTIONAL HEADER block listing the entry point as an RVA and the image base, and a section table listing .text/.data/.rdata with both "virtual size" and "size of raw data" columns per row - when virtual size exceeds raw data size for a section, that difference is exactly the zero-fill gap, PE's version of .bss."""},

            {"h": "FAILURE MODES: RVA/OFFSET CONFUSION AND HEADER-LEVEL DECEPTION", "body": r"""The single most common manual-analysis mistake with PE files is confusing a Relative Virtual Address with a raw file offset - they are only equal by coincidence, never by rule. To go from an RVA to the actual byte position inside the FILE, you must find which section's virtual-address range contains that RVA, then compute file_offset = RVA - section.VirtualAddress + section.PointerToRawData. Skip that translation and you will read the wrong bytes entirely from a hex editor while believing you are looking at, say, the entry point - a mistake that has sent real analysts down false trails.

Malware authors exploit the same header fields defenders trust for a fast read: a section marked executable, writable, AND readable simultaneously (RWX) is a strong red flag, since legitimate compilers almost never emit that combination (it violates W^X, discussed more in cl-6) - it usually signals a self-modifying or packed/unpacking stub. An entry point RVA pointing OUTSIDE the .text section, or a section table with a suspiciously small raw size but a huge virtual size, both suggest the real code is unpacked or decrypted into memory only at runtime, specifically to defeat a static scan of the file on disk. Import table abuse is subtler still: a loader-level trick like DLL search-order hijacking can substitute a malicious file at load time for a legitimately-named import, without the PE header itself containing anything technically false."""},

            {"h": "HOW AN ANALYST TRIAGES AN UNKNOWN BINARY'S HEADER", "body": r"""A fast, standard first pass on an unknown ELF binary: readelf -h for the overview (class, endianness, type, entry point), readelf -S for the full section table (names, sizes, flags - watch for W+X together), and readelf -l for program headers (which segments actually get loaded, and with what permissions) - objdump -x prints a broadly similar combined view in one command if you prefer a single tool. On PE files, dumpbin /headers gives the same overview, while dumpbin /imports lists every external function the binary declared it needs (a fast behavioral fingerprint - a program importing process-injection style functions is worth far more scrutiny than one importing only basic I/O) and dumpbin /exports shows what it offers to others, relevant for DLLs.

Beyond the header itself, analysts cross-check: does the declared machine type (x86 vs x64 vs ARM) match how the file actually behaves when run in a sandbox? Are section permissions sane (.text execute-only, .data/.bss read-write-NOT-execute)? Is the entry point inside a named, expected section? Any header field that looks "technically valid but structurally strange," as opposed to outright malformed, is exactly the kind of anomaly that took a human, tool-assisted eye to notice - which is the entire reason this lesson insists on reading these fields directly instead of only trusting a single antivirus verdict."""},

            {"h": "WHERE THIS GOES NEXT", "body": r"""This lesson is where cl-1 through cl-3 become a single readable artifact. The magic-number recognition from cl-2 is literally the first bytes of the header you just decoded field by field. The regions from cl-3 - text, data, bss, heap, stack - are exactly what the section table (PE) or program headers (ELF) instruct the loader to build; a section table row is nothing more than "here is a region from cl-3, here is its size, here is its file location, here is its permission bits," expressed in the bit-packed, hex-addressed vocabulary from cl-1. cl-5's struct layout and padding rules govern how the header's own fields (many of which ARE just structs, defined precisely in the PE/ELF specifications) are packed inside the file you have been reading.

And cl-6 depends directly on one specific fact from this lesson: which sections are marked executable and which are not is what DEP/NX actually enforces at the hardware level - a security feature that only makes sense once you have seen, as you just did in sections 3 and 4, that section permissions are an explicit, inspectable field in every executable's header, not an assumption."""},
        ],
    },

    "cl-5": {
        "title_check": "Representing chars, floats & struct padding",
        "sections": [
            {"h": "MENTAL MODEL: THE BITS DON'T CHANGE, ONLY THE AGREED READING DOES", "body": r"""Three more "interpretations of bits" complete the picture cl-1 opened: characters, floating-point numbers, and structs. A char is simply a small integer with an agreed-upon mapping to a printable symbol - ASCII fixes A as exactly the integer 65 (0x41), which is why char arithmetic works at all: 'A' + 1 legitimately equals 'B' (66), and 'a' - 'A' is always 32 (0x20), the fixed bit-difference between upper and lower case in ASCII, which is precisely why case conversion can be implemented as a single bit-flip in the simplest case. Nothing about a char is intrinsically textual - it is an integer wearing a font.

A float is a far more radical piece of agreed-upon interpretation: IEEE-754 packs a sign bit, a biased exponent, and a mantissa (fractional significant digits) into one fixed-width word, and the resulting number is fundamentally a BINARY fraction, not a decimal one - meaning many ordinary decimal values (0.1, 0.2, 0.3) have no exact representation at all, only a nearest approximation, in exactly the way 1/3 has no exact finite decimal representation. A struct is the least exotic of the three but still bit-level: the compiler decides not just where each field starts, but often INSERTS extra unnamed padding bytes between fields, purely so each field lands at a hardware-friendly address - a decision you do not control unless you explicitly ask for it."""},

            {"h": "IEEE-754 BIT LAYOUT AND THE ALIGNMENT RULE", "body": r"""A 32-bit IEEE-754 float packs exactly 32 bits as: 1 sign bit (0 = positive), 8 exponent bits (stored with a bias of 127, so the stored byte represents actual_exponent + 127), and 23 mantissa bits (the fractional part of a binary number normalized to start with an implicit leading 1). The value the whole word represents is (-1)^sign times 1.mantissa (read as binary) times 2^(exponent-127). This layout is exactly why 0.1 cannot be stored exactly: 0.1 in binary is an infinitely repeating fraction, the binary analogue of 1/3 being 0.333...repeating in decimal - IEEE-754 must truncate it to 23 mantissa bits, storing the CLOSEST representable value, not 0.1 itself, and that tiny, consistent rounding error is why 0.1 + 0.2 computes to something like 0.30000000000000004 instead of exactly 0.3.

Struct alignment follows one governing rule: a member is placed at the next offset that is a multiple of its own alignment requirement (commonly its own size for basic types - a 4-byte int wants a 4-byte-aligned offset, an 8-byte double wants an 8-byte-aligned offset), and the compiler inserts PADDING bytes before a member if the natural next offset does not already satisfy that. The struct's total size is then rounded UP to a multiple of its largest member's alignment requirement, specifically so that an ARRAY of the struct keeps every element correctly aligned too, not just the first one."""},

            {"h": "A STRUCT'S PADDING, COMPUTED BYTE BY BYTE", "body": r"""Take struct S { char a; int b; char c; }; and place it starting at offset 0. a (1 byte) fits at offset 0 with no padding needed - any offset satisfies a 1-byte alignment. b is a 4-byte int, so it needs an offset divisible by 4; offset 1 (right after a) does not qualify, so the compiler inserts 3 padding bytes (offsets 1, 2, 3) and places b at offsets 4 through 7. c (1 byte) fits at offset 8 with no padding needed. Naive field-size sum says 1+4+1 = 6 bytes; the REAL sizeof(S) is 12, because after c at offset 8, the struct's total size must round up to a multiple of 4 (int's alignment, the largest member) - so 3 more trailing padding bytes are added (offsets 9, 10, 11), giving a final size of 12, not 9.

Contrast that with a clean IEEE-754 case: the float value 1.5 encodes exactly, with no rounding needed - sign=0, exponent stored as 128 (meaning actual exponent 1, since 128-127=1), mantissa=100...0 (just the fraction .5 in binary), giving the full 32-bit word 0x3FC00000 - inspectable directly by taking a float's address, casting the pointer to an unsigned int pointer, and printing THAT in hex, a genuinely useful debugging trick for seeing a float's raw representation instead of its printed decimal approximation."""},

            {"h": "FAILURE MODES: FLOAT EQUALITY, PADDING LEAKS, SIGN-EXTENSION SURPRISES", "body": r"""Comparing floats with == is a real, common bug, not pedantry: because 0.1 and 0.2 are each stored as the nearest representable approximation rather than their exact values, 0.1 + 0.2 == 0.3 evaluates to false in essentially every mainstream language, since the accumulated rounding error makes the computed sum differ from 0.3's own nearest approximation in the very last bit. Correct float comparison uses a tolerance - fabs(a - b) < epsilon - never bare equality, and this single fact explains a large fraction of "my program's math is randomly wrong" bug reports.

Struct padding bytes are an even quieter, security-relevant failure mode: those unnamed padding bytes are NOT guaranteed to be zeroed by the compiler - they typically contain whatever garbage was already sitting in that memory. If a struct is written directly to a file, sent over a network socket, or copied with memcpy/sizeof rather than field-by-field, those padding bytes go along for the ride - a real, documented class of information-disclosure vulnerability. Separately, a plain char is signed on some compilers/platforms and unsigned on others; a byte value of 0xFF read as a signed char is -1, but as unsigned char is 255 - code that assumes one or the other without an explicit annotation can silently misbehave only on the platform where the assumption is wrong."""},

            {"h": "HOW AN ANALYST VERIFIES LAYOUT RATHER THAN ASSUMING IT", "body": r"""A disciplined programmer never assumes a struct's layout by eye - they verify it. offsetof(S, field) (from stddef.h) returns the EXACT compiler-computed byte offset of a field, and printing it alongside sizeof(S) for every field turns section 3's manual arithmetic into a one-line, always-correct check that holds even if you change compilers, platforms, or struct ordering later - a habit worth forming before, not after, a padding-related bug bites you. When a struct is declared with #pragma pack(1) or an equivalent packed attribute, the compiler is explicitly told to SKIP its normal alignment padding - useful for matching an exact on-wire or on-disk format but at the cost of potentially slower unaligned memory access on some architectures, and at the cost of breaking the "array of structs stays aligned" guarantee from section 2.

Reverse engineers face the inverse problem constantly: given a raw memory or file dump of an UNKNOWN struct with no source code, they infer the layout from repeated patterns - a recurring 4-byte-aligned run of similar-looking values suggests an int field at a fixed offset across many instances; unexplained repeated zero bytes at a consistent offset suggest padding rather than a meaningful field. This is exactly cl-2's magic-number-reading skill and cl-3's region-reading skill, aimed now at the finer grain of one data structure's internal shape instead of a whole file or process."""},

            {"h": "WHERE THIS GOES NEXT", "body": r"""This lesson is cl-1's bit vocabulary (sign bits, masks, shifts) applied to two of the most consequential in-memory representations you will ever need to read: floating point numbers and structured data. cl-2's endianness applies here without exception - a multi-byte float or a multi-byte int FIELD inside a struct still has a byte order, and dumping a struct from a little-endian machine requires the exact same reassembly discipline as any other multi-byte value. cl-3's memory regions are simply WHERE a given struct instance happens to live (global struct: .data/.bss; heap-allocated struct: heap; local struct: stack) - the padding rule from this lesson applies identically regardless of which region holds the instance. cl-4's header formats are themselves, quite literally, structs with padding rules exactly like the one you computed by hand in section 3 - reading a PE or ELF header correctly requires knowing exactly this kind of alignment reasoning.

cl-6 closes the track by asking what happens when a BUFFER (an array, which has no padding between elements, unlike a struct) gets overrun - the last mechanism standing between everything you now know about memory layout and an actual security failure."""},
        ],
    },

    "cl-6": {
        "title_check": "How a stack overflow works (conceptually)",
        "sections": [
            {"h": "MENTAL MODEL: A CALL FRAME IS A BLUEPRINT, NOT A SAFE", "body": r"""cl-3 introduced the stack frame's contents - arguments, saved return address, saved frame pointer, locals - but treated them as a list. The security-critical fact is that this list is a single, CONTIGUOUS region with no wall or barrier between its parts by default: a local array and the saved return address are simply neighbors in the same block of memory, and nothing in ordinary hardware stops a write to one from continuing into the other. "Buffer overflow" is a precise, literal description, not a metaphor - it means a write operation continued past the boundary the programmer intended for one variable, into whatever memory happens to sit next, because C, unlike memory-safe languages, performs NO automatic bounds checking on array or pointer writes.

A typical frame layout (details vary by compiler and architecture, but the RELATIVE order is the load-bearing fact): a local char buffer[16] sits at the lowest addresses of the frame, then the saved frame pointer, then the saved return address, sitting adjacent, at a HIGHER address than the buffer. Writing bytes 0 through 15 into buffer is safe; writing byte 16, 17, 18 onward is not a different operation, not a special case the hardware detects - it is the exact same store instruction, at the exact same speed, simply continuing past where the buffer's designer intended it to stop, directly into the saved frame pointer and then the saved return address."""},

            {"h": "WHAT call AND ret ACTUALLY DO, AND WHY OVERWRITING WORKS", "body": r"""Two machine instructions make this entire mechanism possible. call, executed when your code invokes a function, does exactly two things: push the address of the instruction right after the call (so execution knows where to resume), then jump to the function's start. ret, executed when the function returns, does the mirror operation: pop whatever value currently sits at the stack location it expects the return address to be, and jump to it - unconditionally, with absolutely no check that the value is a legitimate code address, or that it has not been modified since call pushed it. ret trusts that memory location completely.

This is precisely the gap unbounded copy functions expose. gets(buffer) reads from input with NO length limit whatsoever regardless of buffer's declared size - if the input is longer than buffer, gets keeps writing, marching straight through the padding, the saved frame pointer, and into the saved return address, byte for byte, exactly as section 1 described. strcpy(dest, src) has the identical flaw if src's length is not independently checked first. sprintf(buf, "%s", input) and scanf("%s", buf) share the same unbounded-write behavior. None of these functions are "buggy" in the sense of malfunctioning - they do exactly what their specification says; the vulnerability is entirely in calling them without first guaranteeing the input cannot exceed the destination's size."""},

            {"h": "A STACK FRAME, BEFORE AND AFTER, BYTE BY BYTE", "body": r"""Picture a frame holding char buffer[16] followed immediately by a saved frame pointer (8 bytes) and a saved return address (8 bytes, x86-64), shown as a dump from low to high address, BEFORE any overflow, with the buffer properly filled with 10 real bytes and 6 bytes untouched:

    buffer[0..15]:  48 65 6c 6c 6f 20 74 68 65 72 65 00 00 00 00 00   ("Hello there")
    saved FP:       7f fe 12 34 00 00 00 00                          (untouched, legitimate)
    saved RET:      00 55 ab cd 12 00 00 00                          (untouched, points into .text)

Now picture 32 bytes copied into that same 16-byte buffer with no bounds check - the first 16 bytes fill buffer exactly as intended, but the NEXT 8 bytes land exactly on the saved frame pointer, and the FINAL 8 land exactly on the saved return address, overwriting it completely with whatever the input contained:

    buffer[0..15]:  41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41   (filler from the input)
    saved FP:       41 41 41 41 41 41 41 41                          (OVERWRITTEN - garbage now)
    saved RET:      41 41 41 41 41 41 41 41                          (OVERWRITTEN - not a valid code address)

When this function's ret instruction executes, it pops that last row, unconditionally, and jumps there - if it happens to be an address chosen deliberately rather than plain filler, execution now continues wherever that value points, which is the entire mechanism, and precisely the reason bounds checking exists."""},

            {"h": "FAILURE MODES, FRAMED FOR DEFENSE: WHAT MAKES THIS POSSIBLE AT ALL", "body": r"""Stack smashing is possible only because SEVERAL independent weaknesses used to line up simultaneously, and modern defenses (section 5) each target one of them specifically. Root cause one: C performs no automatic bounds checking on raw arrays or pointers - the language trusts the programmer completely. Root cause two: several standard library functions (gets especially, but strcpy/sprintf/scanf with %s used carelessly) will happily write past a destination's size if not paired with an explicit length limit. Root cause three: without protection, the stack's data (buffer) and its control-flow-critical data (saved return address) share one undifferentiated region with no hardware barrier between them, and the layout is deterministic enough that an attacker who can see or guess it knows exactly how many filler bytes precede the saved return address.

Off-by-one overflows are the subtler sibling: a loop bound like for (i = 0; i <= 16; i++) buf[i] = ... writes exactly ONE byte past a 16-byte buffer - often not enough to reach the saved return address directly, but enough to corrupt a single adjacent byte, which can still be a real, exploitable bug depending on frame layout. Format string bugs are a related but mechanically DIFFERENT vulnerability: passing untrusted input directly as a printf format string instead of as its argument lets specifiers like %x or %n read or even write memory through printf's own variadic argument handling - a different root cause producing a similarly severe class of memory corruption."""},

            {"h": "HOW AN ANALYST TRIAGES A CRASH THAT LOOKS LIKE STACK CORRUPTION", "body": r"""When a crash's instruction pointer (EIP on x86, RIP on x86-64) holds an address that is not a valid, mapped, executable location - especially a value that looks like ASCII text or an otherwise implausible pattern - that is the classic signature of a corrupted return address, and it is usually the very first thing an analyst checks in a debugger or crash dump. On Linux, a stack-smashing protector (a canary, section 6's very next topic) that detects corruption BEFORE ret executes aborts immediately with a distinctive message, "stack smashing detected," which is itself a diagnostic gift: it tells you definitively that a stack overflow occurred, before the program could do anything worse.

Beyond after-the-fact crash analysis, tools exist specifically to catch this class of bug BEFORE it ships: AddressSanitizer instruments every memory access and flags an overflow the instant it happens, printing the exact line of code responsible, far more precisely than a raw crash address ever could; fuzzers (feeding a program huge volumes of malformed or random input automatically) are the standard way real-world overflow bugs are FOUND in the first place, well before any human writes a targeted input. Modern defenses are always discussed as a STACK of measures rather than any single one, because each closes a different piece of the mechanism from sections 1-4."""},

            {"h": "WHERE THIS GOES NEXT - THE THREE DEFENSES THAT CLOSE THE TRACK", "body": r"""Three defenses, each closing a different piece of the mechanism from sections 1-4, are the concrete answer to everything this lesson described. Stack canaries place a small, random value between the local buffer and the saved frame pointer/return address at function entry, then check it is UNCHANGED right before ret executes - an overflow big enough to reach the return address necessarily overwrites the canary first, so a mismatch means abort immediately, before the corrupted return address is ever used (the exact mechanism behind section 5's crash message). ASLR (Address Space Layout Randomization) randomizes WHERE the stack, heap, and loaded modules sit in memory on every run - directly attacking cl-3's assumption of a fixed, predictable address space, so even if an attacker corrupts a return address, guessing a useful destination address becomes far harder. DEP/NX (Data Execution Prevention / No-eXecute) marks stack and heap memory as non-executable at the hardware page-table level - directly enforcing cl-4's section-permission fields, so even a successfully redirected return address cannot simply jump into injected data sitting on the stack, because the CPU refuses to execute instructions from a page marked non-executable.

This closes the entire cyber_low arc: cl-1's bits were always going to end up somewhere in memory; cl-2's endianness governs how a return address is actually stored; cl-3's regions are the terrain; cl-4's header permission bits are what NX enforces; cl-5's precise-layout discipline is exactly what both attacker and defender need to reason about frame offsets. Six lessons about bits and memory, converging on one sentence: know the layout, and you know both how this breaks and how it is stopped."""},
        ],
    },

}
