# leet_tests.py - expanded test cases for the LeetCode problems in leet.py.
# Generated from known-correct reference solutions (see scratchpad/gen_leet_tests.py).
# Merged onto each problem's `tests` list by leet.py so a partial solution that only
# handles the easy cases fails the edge cases (empty, single, duplicates, negatives, ...).
EXTRA_TESTS = {'two-sum': [{'args': [[2, 7, 11, 15], 9], 'expect': [0, 1]},
             {'args': [[3, 2, 4], 6], 'expect': [1, 2]},
             {'args': [[3, 3], 6], 'expect': [0, 1]},
             {'args': [[-1, -2, -3, -4, -5], -8], 'expect': [2, 4]},
             {'args': [[0, 4, 3, 0], 0], 'expect': [0, 3]},
             {'args': [[1, 5, 9, 12, 20], 21], 'expect': [2, 3]},
             {'args': [[-3, 4, 3, 90], 0], 'expect': [0, 2]},
             {'args': [[5, 75, 25], 100], 'expect': [1, 2]},
             {'args': [[2, 5, 5, 11], 10], 'expect': [1, 2]},
             {'args': [[1, 2, 3, 4, 5, 6, 7], 13], 'expect': [5, 6]}],
 'valid-parentheses': [{'args': ['()'], 'expect': True},
                       {'args': ['()[]{}'], 'expect': True},
                       {'args': ['(]'], 'expect': False},
                       {'args': ['([)]'], 'expect': False},
                       {'args': ['{[]}'], 'expect': True},
                       {'args': [']'], 'expect': False},
                       {'args': ['['], 'expect': False},
                       {'args': [''], 'expect': True},
                       {'args': ['(((((())))))'], 'expect': True},
                       {'args': ['()(()){}[]'], 'expect': True},
                       {'args': ['([{}])'], 'expect': True},
                       {'args': ['{[()()]}'], 'expect': True},
                       {'args': ['(('], 'expect': False},
                       {'args': ['))'], 'expect': False},
                       {'args': ['([]{})('], 'expect': False}],
 'fizzbuzz': [{'args': [1], 'expect': ['1']},
              {'args': [3], 'expect': ['1', '2', 'Fizz']},
              {'args': [5], 'expect': ['1', '2', 'Fizz', '4', 'Buzz']},
              {'args': [15],
               'expect': ['1',
                          '2',
                          'Fizz',
                          '4',
                          'Buzz',
                          'Fizz',
                          '7',
                          '8',
                          'Fizz',
                          'Buzz',
                          '11',
                          'Fizz',
                          '13',
                          '14',
                          'FizzBuzz']},
              {'args': [16],
               'expect': ['1',
                          '2',
                          'Fizz',
                          '4',
                          'Buzz',
                          'Fizz',
                          '7',
                          '8',
                          'Fizz',
                          'Buzz',
                          '11',
                          'Fizz',
                          '13',
                          '14',
                          'FizzBuzz',
                          '16']},
              {'args': [2], 'expect': ['1', '2']},
              {'args': [30],
               'expect': ['1',
                          '2',
                          'Fizz',
                          '4',
                          'Buzz',
                          'Fizz',
                          '7',
                          '8',
                          'Fizz',
                          'Buzz',
                          '11',
                          'Fizz',
                          '13',
                          '14',
                          'FizzBuzz',
                          '16',
                          '17',
                          'Fizz',
                          '19',
                          'Buzz',
                          'Fizz',
                          '22',
                          '23',
                          'Fizz',
                          'Buzz',
                          '26',
                          'Fizz',
                          '28',
                          '29',
                          'FizzBuzz']},
              {'args': [20],
               'expect': ['1',
                          '2',
                          'Fizz',
                          '4',
                          'Buzz',
                          'Fizz',
                          '7',
                          '8',
                          'Fizz',
                          'Buzz',
                          '11',
                          'Fizz',
                          '13',
                          '14',
                          'FizzBuzz',
                          '16',
                          '17',
                          'Fizz',
                          '19',
                          'Buzz']}],
 'max-subarray': [{'args': [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], 'expect': 6},
                  {'args': [[1]], 'expect': 1},
                  {'args': [[5, 4, -1, 7, 8]], 'expect': 23},
                  {'args': [[-3, -1, -2]], 'expect': -1},
                  {'args': [[-1]], 'expect': -1},
                  {'args': [[0]], 'expect': 0},
                  {'args': [[-5, -2, -8, -1]], 'expect': -1},
                  {'args': [[8, -19, 5, -4, 20]], 'expect': 21},
                  {'args': [[1, 2, 3, 4, 5]], 'expect': 15},
                  {'args': [[3, -2, 5, -1]], 'expect': 6},
                  {'args': [[-2, -3, 4, -1, -2, 1, 5, -3]], 'expect': 7}],
 'contains-duplicate': [{'args': [[1, 2, 3, 1]], 'expect': True},
                        {'args': [[1, 2, 3, 4]], 'expect': False},
                        {'args': [[1, 1, 1, 3, 3, 4, 3, 2, 4, 2]], 'expect': True},
                        {'args': [[]], 'expect': False},
                        {'args': [[7]], 'expect': False},
                        {'args': [[0, 0]], 'expect': True},
                        {'args': [[-1, -1]], 'expect': True},
                        {'args': [[0,
                                   1,
                                   2,
                                   3,
                                   4,
                                   5,
                                   6,
                                   7,
                                   8,
                                   9,
                                   10,
                                   11,
                                   12,
                                   13,
                                   14,
                                   15,
                                   16,
                                   17,
                                   18,
                                   19,
                                   20,
                                   21,
                                   22,
                                   23,
                                   24,
                                   25,
                                   26,
                                   27,
                                   28,
                                   29,
                                   30,
                                   31,
                                   32,
                                   33,
                                   34,
                                   35,
                                   36,
                                   37,
                                   38,
                                   39,
                                   40,
                                   41,
                                   42,
                                   43,
                                   44,
                                   45,
                                   46,
                                   47,
                                   48,
                                   49]],
                         'expect': False},
                        {'args': [[0,
                                   1,
                                   2,
                                   3,
                                   4,
                                   5,
                                   6,
                                   7,
                                   8,
                                   9,
                                   10,
                                   11,
                                   12,
                                   13,
                                   14,
                                   15,
                                   16,
                                   17,
                                   18,
                                   19,
                                   20,
                                   21,
                                   22,
                                   23,
                                   24,
                                   25,
                                   26,
                                   27,
                                   28,
                                   29,
                                   30,
                                   31,
                                   32,
                                   33,
                                   34,
                                   35,
                                   36,
                                   37,
                                   38,
                                   39,
                                   40,
                                   41,
                                   42,
                                   43,
                                   44,
                                   45,
                                   46,
                                   47,
                                   48,
                                   49,
                                   49]],
                         'expect': True}],
 'valid-anagram': [{'args': ['anagram', 'nagaram'], 'expect': True},
                   {'args': ['rat', 'car'], 'expect': False},
                   {'args': ['a', 'a'], 'expect': True},
                   {'args': ['', ''], 'expect': True},
                   {'args': ['ab', 'a'], 'expect': False},
                   {'args': ['listen', 'silent'], 'expect': True},
                   {'args': ['aacc', 'ccac'], 'expect': False},
                   {'args': ['abc', 'cba'], 'expect': True},
                   {'args': ['hello', 'olleh'], 'expect': True},
                   {'args': ['night', 'thing'], 'expect': True}],
 'best-time-stock': [{'args': [[7, 1, 5, 3, 6, 4]], 'expect': 5},
                     {'args': [[7, 6, 4, 3, 1]], 'expect': 0},
                     {'args': [[1, 2]], 'expect': 1},
                     {'args': [[2, 4, 1]], 'expect': 2},
                     {'args': [[3, 3, 3]], 'expect': 0},
                     {'args': [[1]], 'expect': 0},
                     {'args': [[]], 'expect': 0},
                     {'args': [[2, 1, 2, 1, 0, 1, 2]], 'expect': 2},
                     {'args': [[1, 4, 2, 7]], 'expect': 6},
                     {'args': [[5, 4, 3, 2, 1, 6]], 'expect': 5}],
 'single-number': [{'args': [[2, 2, 1]], 'expect': 1},
                   {'args': [[4, 1, 2, 1, 2]], 'expect': 4},
                   {'args': [[1]], 'expect': 1},
                   {'args': [[0, 1, 0]], 'expect': 1},
                   {'args': [[7, 3, 3, 7, 9]], 'expect': 9},
                   {'args': [[-1, -1, -2]], 'expect': -2},
                   {'args': [[8, 8, 3]], 'expect': 3},
                   {'args': [[100, 200, 100]], 'expect': 200}],
 'move-zeroes': [{'args': [[0, 1, 0, 3, 12]], 'expect': [1, 3, 12, 0, 0]},
                 {'args': [[0]], 'expect': [0]},
                 {'args': [[1, 0]], 'expect': [1, 0]},
                 {'args': [[0, 0, 1]], 'expect': [1, 0, 0]},
                 {'args': [[1, 2, 3]], 'expect': [1, 2, 3]},
                 {'args': [[0, 0, 0]], 'expect': [0, 0, 0]},
                 {'args': [[]], 'expect': []},
                 {'args': [[4, 0, 5, 0, 0, 6]], 'expect': [4, 5, 6, 0, 0, 0]},
                 {'args': [[1, 0, 2, 0, 3, 0, 4]], 'expect': [1, 2, 3, 4, 0, 0, 0]},
                 {'args': [[0, 0, 0, 1]], 'expect': [1, 0, 0, 0]}],
 'first-unique-char': [{'args': ['leetcode'], 'expect': 0},
                       {'args': ['loveleetcode'], 'expect': 2},
                       {'args': ['aabb'], 'expect': -1},
                       {'args': ['z'], 'expect': 0},
                       {'args': [''], 'expect': -1},
                       {'args': ['abcabd'], 'expect': 2},
                       {'args': ['aabbccddx'], 'expect': 8},
                       {'args': ['swiss'], 'expect': 1},
                       {'args': ['repeller'], 'expect': 2},
                       {'args': ['aabbccddeef'], 'expect': 10}],
 'palindrome-number': [{'args': [121], 'expect': True},
                       {'args': [-121], 'expect': False},
                       {'args': [10], 'expect': False},
                       {'args': [0], 'expect': True},
                       {'args': [1], 'expect': True},
                       {'args': [12321], 'expect': True},
                       {'args': [1221], 'expect': True},
                       {'args': [100], 'expect': False},
                       {'args': [-1], 'expect': False},
                       {'args': [9999], 'expect': True},
                       {'args': [12345], 'expect': False},
                       {'args': [7], 'expect': True}],
 'valid-palindrome': [{'args': ['A man, a plan, a canal: Panama'], 'expect': True},
                      {'args': ['race a car'], 'expect': False},
                      {'args': [' '], 'expect': True},
                      {'args': ['ab_a'], 'expect': True},
                      {'args': ['0P'], 'expect': False},
                      {'args': ['a'], 'expect': True},
                      {'args': [''], 'expect': True},
                      {'args': ['Was it a car or a cat I saw?'], 'expect': True},
                      {'args': ['No lemon, no melon'], 'expect': True},
                      {'args': ['abccba'], 'expect': True}],
 'group-anagrams': [{'args': [['eat', 'tea', 'tan', 'ate', 'nat', 'bat']],
                     'expect': [['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]},
                    {'args': [['']], 'expect': [['']]},
                    {'args': [['a']], 'expect': [['a']]},
                    {'args': [['abc', 'bca', 'cab', 'xyz', 'zyx']],
                     'expect': [['abc', 'bca', 'cab'], ['xyz', 'zyx']]},
                    {'args': [['listen', 'silent', 'enlist', 'google', 'gooogle']],
                     'expect': [['listen', 'silent', 'enlist'], ['google'], ['gooogle']]},
                    {'args': [['', '']], 'expect': [['', '']]},
                    {'args': [['ab', 'ba', 'abc']], 'expect': [['ab', 'ba'], ['abc']]},
                    {'args': [['rat', 'tar', 'art', 'car']],
                     'expect': [['rat', 'tar', 'art'], ['car']]}],
 'top-k-frequent': [{'args': [[1, 1, 1, 2, 2, 3], 2], 'expect': [1, 2]},
                    {'args': [[1], 1], 'expect': [1]},
                    {'args': [[4, 4, 4, 5, 5, 6], 2], 'expect': [4, 5]},
                    {'args': [[1, 2, 3, 4], 4], 'expect': [1, 2, 3, 4]},
                    {'args': [[7, 7, 8, 8, 9], 3], 'expect': [7, 8, 9]},
                    {'args': [[-1, -1, -2, -2, -2], 1], 'expect': [-2]},
                    {'args': [[5, 5, 5, 5], 1], 'expect': [5]},
                    {'args': [[1, 1, 2, 2, 3, 3], 3], 'expect': [1, 2, 3]}],
 'product-except-self': [{'args': [[1, 2, 3, 4]], 'expect': [24, 12, 8, 6]},
                         {'args': [[-1, 1, 0, -3, 3]], 'expect': [0, 0, 9, 0, 0]},
                         {'args': [[2, 3]], 'expect': [3, 2]},
                         {'args': [[1, 1, 1]], 'expect': [1, 1, 1]},
                         {'args': [[5, 0, 2]], 'expect': [0, 10, 0]},
                         {'args': [[0, 0, 3]], 'expect': [0, 0, 0]},
                         {'args': [[9, 0, 0]], 'expect': [0, 0, 0]},
                         {'args': [[1, 2, 3, 4, 5]], 'expect': [120, 60, 40, 30, 24]},
                         {'args': [[-2, -3, -4]], 'expect': [12, 8, 6]},
                         {'args': [[10, 3, 5, 6, 2]], 'expect': [180, 600, 360, 300, 900]}],
 'longest-substring': [{'args': ['abcabcbb'], 'expect': 3},
                       {'args': ['bbbbb'], 'expect': 1},
                       {'args': ['pwwkew'], 'expect': 3},
                       {'args': [''], 'expect': 0},
                       {'args': [' '], 'expect': 1},
                       {'args': ['au'], 'expect': 2},
                       {'args': ['dvdf'], 'expect': 3},
                       {'args': ['abba'], 'expect': 2},
                       {'args': ['tmmzuxt'], 'expect': 5},
                       {'args': ['abcdefg'], 'expect': 7},
                       {'args': ['aab'], 'expect': 2},
                       {'args': ['cdd'], 'expect': 2}],
 'three-sum': [{'args': [[-1, 0, 1, 2, -1, -4]], 'expect': [[-1, -1, 2], [-1, 0, 1]]},
               {'args': [[0, 1, 1]], 'expect': []},
               {'args': [[0, 0, 0]], 'expect': [[0, 0, 0]]},
               {'args': [[]], 'expect': []},
               {'args': [[1, 2, -2, -1]], 'expect': []},
               {'args': [[-2, 0, 1, 1, 2]], 'expect': [[-2, 0, 2], [-2, 1, 1]]},
               {'args': [[3, 0, -2, -1, 1, 2]], 'expect': [[-2, -1, 3], [-2, 0, 2], [-1, 0, 1]]},
               {'args': [[-4, -2, -2, -2, 0, 1, 2, 2, 2, 3, 3, 4, 4, 6, 6]],
                'expect': [[-4, -2, 6],
                           [-4, 0, 4],
                           [-4, 1, 3],
                           [-4, 2, 2],
                           [-2, -2, 4],
                           [-2, 0, 2]]},
               {'args': [[-1, -1, 2]], 'expect': [[-1, -1, 2]]},
               {'args': [[1, 2, 3]], 'expect': []}],
 'coin-change': [{'args': [[1, 2, 5], 11], 'expect': 3},
                 {'args': [[2], 3], 'expect': -1},
                 {'args': [[1], 0], 'expect': 0},
                 {'args': [[1], 2], 'expect': 2},
                 {'args': [[2, 5, 10, 1], 27], 'expect': 4},
                 {'args': [[186, 419, 83, 408], 6249], 'expect': 20},
                 {'args': [[1, 2, 5], 100], 'expect': 20},
                 {'args': [[5], 5], 'expect': 1},
                 {'args': [[3, 7], 5], 'expect': -1},
                 {'args': [[2, 4], 7], 'expect': -1}],
 'num-islands': [{'args': [['11110', '11010', '11000', '00000']], 'expect': 1},
                 {'args': [['11000', '11000', '00100', '00011']], 'expect': 3},
                 {'args': [['000', '000']], 'expect': 0},
                 {'args': [['1']], 'expect': 1},
                 {'args': [['0']], 'expect': 0},
                 {'args': [['101', '010', '101']], 'expect': 5},
                 {'args': [['111', '010', '111']], 'expect': 1},
                 {'args': [['1111', '1001', '1001', '1111']], 'expect': 1},
                 {'args': [['10001', '00000', '10001']], 'expect': 4}],
 'merge-intervals': [{'args': [[[1, 3], [2, 6], [8, 10], [15, 18]]],
                      'expect': [[1, 6], [8, 10], [15, 18]]},
                     {'args': [[[1, 4], [4, 5]]], 'expect': [[1, 5]]},
                     {'args': [[[1, 4]]], 'expect': [[1, 4]]},
                     {'args': [[[1, 4], [2, 3]]], 'expect': [[1, 4]]},
                     {'args': [[[1, 4], [5, 6]]], 'expect': [[1, 4], [5, 6]]},
                     {'args': [[[1, 10], [2, 3], [4, 5]]], 'expect': [[1, 10]]},
                     {'args': [[[2, 3], [1, 4]]], 'expect': [[1, 4]]},
                     {'args': [[[1, 2], [3, 4], [5, 6], [1, 6]]], 'expect': [[1, 6]]},
                     {'args': [[[0, 0], [1, 1]]], 'expect': [[0, 0], [1, 1]]}],
 'binary-search': [{'args': [[-1, 0, 3, 5, 9, 12], 9], 'expect': 4},
                   {'args': [[-1, 0, 3, 5, 9, 12], 2], 'expect': -1},
                   {'args': [[5], 5], 'expect': 0},
                   {'args': [[5], -5], 'expect': -1},
                   {'args': [[], 3], 'expect': -1},
                   {'args': [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 1], 'expect': 0},
                   {'args': [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 10], 'expect': 9},
                   {'args': [[2, 4, 6, 8], 5], 'expect': -1},
                   {'args': [[1, 3, 5, 7, 9], 7], 'expect': 3},
                   {'args': [[0,
                              2,
                              4,
                              6,
                              8,
                              10,
                              12,
                              14,
                              16,
                              18,
                              20,
                              22,
                              24,
                              26,
                              28,
                              30,
                              32,
                              34,
                              36,
                              38,
                              40,
                              42,
                              44,
                              46,
                              48,
                              50,
                              52,
                              54,
                              56,
                              58,
                              60,
                              62,
                              64,
                              66,
                              68,
                              70,
                              72,
                              74,
                              76,
                              78,
                              80,
                              82,
                              84,
                              86,
                              88,
                              90,
                              92,
                              94,
                              96,
                              98],
                             50],
                    'expect': 25},
                   {'args': [[0,
                              2,
                              4,
                              6,
                              8,
                              10,
                              12,
                              14,
                              16,
                              18,
                              20,
                              22,
                              24,
                              26,
                              28,
                              30,
                              32,
                              34,
                              36,
                              38,
                              40,
                              42,
                              44,
                              46,
                              48,
                              50,
                              52,
                              54,
                              56,
                              58,
                              60,
                              62,
                              64,
                              66,
                              68,
                              70,
                              72,
                              74,
                              76,
                              78,
                              80,
                              82,
                              84,
                              86,
                              88,
                              90,
                              92,
                              94,
                              96,
                              98],
                             51],
                    'expect': -1}],
 'trapping-rain': [{'args': [[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], 'expect': 6},
                   {'args': [[4, 2, 0, 3, 2, 5]], 'expect': 9},
                   {'args': [[]], 'expect': 0},
                   {'args': [[1]], 'expect': 0},
                   {'args': [[2, 0, 2]], 'expect': 2},
                   {'args': [[3, 0, 0, 2, 0, 4]], 'expect': 10},
                   {'args': [[1, 2, 3, 4]], 'expect': 0},
                   {'args': [[4, 3, 2, 1]], 'expect': 0},
                   {'args': [[5, 4, 1, 2]], 'expect': 1},
                   {'args': [[0, 0, 0]], 'expect': 0}],
 'longest-valid-paren': [{'args': ['(()'], 'expect': 2},
                         {'args': [')()())'], 'expect': 4},
                         {'args': [''], 'expect': 0},
                         {'args': ['()'], 'expect': 2},
                         {'args': ['()(()'], 'expect': 2},
                         {'args': ['(()())'], 'expect': 6},
                         {'args': ['))(('], 'expect': 0},
                         {'args': ['()(())'], 'expect': 6},
                         {'args': ['(()))())('], 'expect': 4},
                         {'args': [')()())()()('], 'expect': 4},
                         {'args': ['(((('], 'expect': 0},
                         {'args': ['))))'], 'expect': 0}],
 'median-two-sorted': [{'args': [[1, 3], [2]], 'expect': 2.0},
                       {'args': [[1, 2], [3, 4]], 'expect': 2.5},
                       {'args': [[], [1]], 'expect': 1.0},
                       {'args': [[2], []], 'expect': 2.0},
                       {'args': [[1, 2, 3], [4, 5, 6]], 'expect': 3.5},
                       {'args': [[0, 0], [0, 0]], 'expect': 0.0},
                       {'args': [[1], [2, 3, 4, 5]], 'expect': 3.0},
                       {'args': [[1, 5, 9], [2, 3]], 'expect': 3.0},
                       {'args': [[-5, -3], [-2, -1]], 'expect': -2.5},
                       {'args': [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], 'expect': 5.5}]}
